### ISSUE TITLE
HTTP GET DPU doesn't follow redirects

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#100]
HTTP GET DPU doesn't follow redirects. It should either follow redirects by default or have an option to make it follow them.

For example, requesting the namespace IRI of the Data Cube Vocabulary (<http://purl.org/linked-data/cube#>) results in `HTTP 303 See Other` redirect with the `Location` header set to `https://raw.githubusercontent.com/UKGovLD/publishing-statistical-data/master/specs/src/main/vocab/cube.ttl`. However, instead of resolving the IRI in the `Location` header, HTTP GET DPU returns the redirect page.

Tested on 2b9a0f87522cdddf557ae04a856e7adffb7c2241.

**Comment by skodape** [comment]
It follows redirect in the same protocol, but the mentioned redirect is from http to https (try to use https at the first place).  To enable this an option to follow redirect to any address (force redirect follow) has been added.

**Comment by jindrichmynarz** [comment]
Thanks! In this case, the namespace IRI using the `http` protocol is established (see [here](http://prefix.cc/qb)), so the redirect will need to be forced. As an aside, purl.org also redirects the `https` version of this IRI.

**Comment by jindrichmynarz** [comment]
"Force redirect follow" → "Force to follow redirects"
