### ISSUE TITLE
Graph merger doesn't show a configuration dialog

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#101]
Graph merger DPU doesn't show a configuration dialog. If it shouldn't have a configuration dialog, it should be clear that the dialog isn't available (e.g., by disabling the "Edit" button). If it should have a configuration dialog, then it should show.

Tested on 2b9a0f87522cdddf557ae04a856e7adffb7c2241.

**Comment by jakubklimek** [comment]
This is a more generic issue. It does not have its own configuration, however, it still supports coloring and renaming. Also other components do not offer any configuration. In this case, the configuration tab could be hidden.

**Comment by jindrichmynarz** [comment]
An empty configuration dialog of Graph merger is shown in 447cd92a49734c31343d00f25fe15a2c4adef371, so I think this resolves the issue.
