### ISSUE TITLE
Confusing redirect from / to /#/executions

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#103]
Requests to the front-end's root (i.e. `/`) are redirected to the list of pipeline executions (i.e. `/#/executions`). I would expect this redirect to be routed to `/#/pipelines` instead.

Tested on version 2b9a0f87522cdddf557ae04a856e7adffb7c2241.

**Comment by jakubklimek** [comment]
This is on purpose as typically, you go to LP-ETL to check on executions, not to see a list of pipelines. What makes it confusing is the missing highlight in navigation.

**Comment by jindrichmynarz** [comment]
In my case, I typically go to LP-ETL to check pipelines, not executions. But I see that others may expect the executions view to be the default.

**Comment by jindrichmynarz** [comment]
I'd appreciate if it was possible to configure the LP-ETL instance to default on the pipelines view. Navigating to the pipelines view from the executions view is the first thing I do when I open LP-ETL.

**Comment by skodape** [comment]
@jindrichmynarz Are you ok with current solution (employment of cookies)? We do not support users so far and per instance configurations can lead to conflicts inside teams whether to use /pipelines or /executions. In this way everyone can have a customised experience.

**Comment by jindrichmynarz** [comment]
Sure, that is enough. Actually this is more prominent than what I hoped for. I suspect though that it is a part of a larger plan for enabling personalization, right?
