### ISSUE TITLE
Missing visual distinction between the pipelines and the executions views

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#104]
Visual distinction between the pipelines and the executions views is missing. The current view isn't highlighted in the menu or in another visual way, so that the user needs to tell the current view from the URL or from the context of what is displayed (e.g., ticks or warning signs accompanying pipeline names indicate the executions view). What is the current view should be visually indicated. For example, the name of the current view can be highlighted in the menu.

Tested on 2b9a0f87522cdddf557ae04a856e7adffb7c2241.

**Comment by jakubklimek** [comment]
Resolved by #170
