### ISSUE TITLE
Enhancement proposal: Sort DPUs in the debug view

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#106]
DPUs' inputs and outputs in the debug execution view can be sorted using [topological sort](https://en.wikipedia.org/wiki/Topological_sorting) of the pipeline's dependency graph to allow easier orientation for users.

**Comment by jakubklimek** [comment]
This view is to be replaced by a graphical one in near future.

**Comment by skodape** [comment]
We have updated view (not the graphical one) for execution detail in the debug branch. DPUs should be sorted in same order as they were executed.
