### ISSUE TITLE
SPARQL Construct syntax error causes inconsistency in execution status

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#107]
Syntactically incorrect SPARQL query used in SPARQL Construct component causes the pipeline to fail and causes inconsistencies:

- The exception is reported as caused by component "pipeline" in debug detail
- In the execution list, the execution is seen as failed but behaves as running

**Comment by jakubklimek** [comment]
Now it seems that it only takes a long time between the pipeline fail and the moment when the execution can be deleted

**Comment by skodape** [comment]
@jakubklimek  By "pipeline fail" do you mean the pipeline is finished as failed or that some component fail? As at the end of execution all debug data are saved to the hard drive which takes some time and cause delay at the very end of pipeline execution.

**Comment by jakubklimek** [comment]
Probably not happening anymore
