### ISSUE TITLE
Change the <titile> element according to context

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#112]
The ```<title>``` element is always "LinkedPipes" which is misleading and shows in Google. It should be 

- Executions - LinkedPipes ETL
- Pipelines - LinkedPipes ETL

Similarly to the future breadcrumbs, but reversed

**Comment by jindrichmynarz** [comment]
Additionally, it would be useful to display the pipeline's name in the `<title>` instead of the generic "Pipelines" when editing a specific pipeline.
