### ISSUE TITLE
Text Holder does not pass the prefixes

### ISSUE THREAD

**Issue by skarampatakis** [linkedpipes/etl#113]
Hi all,
while we are waiting for the converter of UV pipeline to LP pipeline we developed a pipeline for LP from scratch. The problem is that Text Holder DPU seems to loose the prefixes we define. As a result the final output does not contain the prefixes and so all IRIs are in their full form.

**Comment by jakubklimek** [comment]
Text holder only writes text to a file, therefore it has nothing to do with prefixes. 
Where they can be lost is when you parse and RDF file to a Sesame RDF data.
Actually, prefixes are not part of the RDF data model at all (they are only in Turtle/TriG/JSON-LD/SPARQL syntaxes), so it is quite natural that they are not the same in the output as they are in the input. Nevertheless, the data means the same thing so this should not be a problem.

The only case where this could be a problem is when you want to display the RDF data in notepad and want it to be pretty. It would have to be a syntax specific pretty-print DPU (similarly to what http://rdf-translator.appspot.com does) where you could define your own prefixes.

**Comment by skarampatakis** [comment]
The actual loss happens when we feed the input of Text Holder to Files to RDF DPU. This behaviour does not happen on UV. While I agree that it's only a matter of prettiness, I prefer the previous behaviour. At least somehow when we extract the RDF to a file the prefixes should be present in every RDF Format (except N-Triples I think). This is a behaviour most LD applications do(for example a Describe query in Virtuoso SPARQL Endpoint).

**Comment by jakubklimek** [comment]
I see your point. We will investigate whether we can do something about it, e.g. by using http://rdf4j.org/doc/4/apidocs/org/openrdf/model/Namespace.html.

**Comment by skarampatakis** [comment]
As of latest develop version this now works as expected. Thank you.
