### ISSUE TITLE
Issues with first run on Mac OS X

### ISSUE THREAD

**Issue by jirihelmich** [linkedpipes/etl#12]
- [x] shell scripts do not have the correct mode:
```
$ ./executor.sh >> executor.log &
fish: The file './executor.sh' is not executable by this user
```
- [x] shell scripts are missing shebang
```
~/d/m/l/e/deploy (master) $ chmod 0777 *.sh
~/d/m/l/e/deploy (master) $ ./executor.sh >> executor.log &
Failed to execute process './executor.sh'. Reason:
exec: Exec format error
The file './executor.sh' is marked as an executable but could not be run by the operating system.
```

RW: http://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang

```#!/usr/bin/env bash``` worked for me

- [ ] I had to create the directories manually, e.g. I got this error:

```
Error: ENOENT: no such file or directory, scandir '/data/lp/etl/components'
```

- [X] Application is not running

- Executor is running
- Executor monitor failed with message 
```
[main] ERROR c.l.c.c.c.b.AbstractConfiguration - Missing configuration property: 'external.fuseki.path'
```
- Frontend started with message "Backend is not running", all I see is navbar and spinner.

![image](https://cloud.githubusercontent.com/assets/174768/12986371/3cd5de28-d0f7-11e5-9f6c-97e563430601.png)

**Comment by jindrichmynarz** [comment]
Instead of `chmod 0777 *.sh` using `chmod +x *.sh` suffices to make the scripts executable.
