### ISSUE TITLE
File name output by the Mustache DPU should be determined from configuration, not template data

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#125]
Name of the file output by the Mustache DPU should be determined from the DPU's configuration, not from the template data (via the *special* property `http://plugins.linkedpipes.com/ontology/t-mustache#fileName`). This is confusing 2 things: DPU configuration and template data.

I see the need for passing the file names via template data when multiple files should be produced, but I thing it couples things unnecessarily.

**Comment by skodape** [comment]
And what should happen in case of multiple output files?

The files would have same name (from user given configuration), so the output would be a single file with semi-random content (the content of the file would correspond to some input resource).

**Comment by jindrichmynarz** [comment]
I see the point (as I mentioned in the issue). However, do we need Mustache DPU to be able to produce multiple files?

**Comment by jakubklimek** [comment]
Potentially yes. I would not remove functionality just for ease of configuration...
