### ISSUE TITLE
Document the special properties used by Mustache DPU

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#126]
The [properties with special meaning for Mustache DPU](https://github.com/linkedpipes/etl/blob/develop/plugins/t-mustache/src/main/java/com/linkedpipes/plugin/transformer/mustache/MustacheVocabulary.java), such as `http://plugins.linkedpipes.com/ontology/t-mustache#fileName` or `http://plugins.linkedpipes.com/ontology/t-mustache#order`, should be documented.

**Comment by jakubklimek** [comment]
http://etl.linkedpipes.com/components/t-mustache#specifics
