### ISSUE TITLE
Pipeline fragment import should allow importing other pipelines from the same LinkedPipes ETL instance

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#127]
Pipeline fragments can be currently imported either via URL or via directly provided JSON-LD. The import should also allow to import other pipelines from the same LinkedPipes ETL instance. For example, a list of the pipelines can be provided in the import dialog.

**Comment by jakubklimek** [comment]
This is possible via URL of the pipelines in the same instance which you can see in pipeline detail.

**Comment by jindrichmynarz** [comment]
OK, then this behaviour should be documented. It would be better though to allow users to import pipelines fragments from the same LP-ETL instance via the dialog instead of copy-pasting their URLs.
