### ISSUE TITLE
Mustache DPU: either document that templated values must be literals or cast them as literals

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#129]
If try to use a non-literal value (e.g., an IRI) in a Mustache template rendered via the Mustache DPU, it is rendered as empty string. This behaviour should be either explicitly documented or the DPU should cast non-literal values to strings.

**Comment by skodape** [comment]
Other than IRI should actually work. The problem with IRI is that it's used as a reference to another object(s).  We can check if the IRI is reference to resource in input data and then bind as an object, else if it's not a reference (there is no resource with given IRI) - store as a string. 

However there might still be a problem when you may need to access the IRI of object (for example in list or top level object) for such case I think we may adopt the JSON-LD notation and store object IRI under @id "property".

Would this be acceptable solution?

**Comment by jindrichmynarz** [comment]
I think it is acceptable to render only strings. It is not a problem to stringify an IRI using SPARQL before passing it to the Mustache DPU. Given your input I think this is the cleanest solution and one that does not require any changes in the code, only documentation of this behaviour.

**Comment by jakubklimek** [comment]
http://etl.linkedpipes.com/components/t-mustache
