### ISSUE TITLE
IRIs are not supported well by Files to RDF DPU

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#131]
The Files to RDF DPU doesn't support well IRIs containing non-ASCII characters. For example, if we load RDF containing an IRI using Greek alphabet, the resulting IRI is mangled. See this example pipeline <https://gist.github.com/jindrichmynarz/46c7d20f63252e02cb2b6fa583f95806>, run it, and look into the output of the Files to RDF DPU. `<http://el.dbpedia.org/resource/Δήμος_Αθηναίων>` becomes `<http://el.dbpedia.org/resource/Î”Î®Î¼Î¿Ï‚_Î‘Î¸Î·Î½Î±Î¯Ï‰Î½>`. The results are the same when RDF is loaded from a file (e.g., [this file](https://github.com/openbudgets/datasets/raw/master/greek-municipalities/municipality-of-athens/dataset/budget-athens-expenditure-2004.ttl)).

Tested using the latest develop version (b6675cc1fa2c9e89aefd61b761b41d6debdb9e45).

**Comment by skodape** [comment]
@jindrichmynarz  Do you use the IRI any further?

When I look through the debug I see what you described (`http://el.dbpedia.org/resource/Î”Î®ÎĽÎżĎ‚_Î‘Î¸Î·Î˝Î±ÎŻĎ‰Î˝`), however when I download the file and open in locally I got what I believe is the right format (`http://el.dbpedia.org/resource/Δήμος_Αθηναίων`).

It seems to work OK on Firefox (display character correctly in debug), but not in Chrome (50.0.2661.94 m) or IE (11.0.9600.18230), or when I convert the RDF back to file, store to local drive and open it.

**Comment by skarampatakis** [comment]
I can confirm that this is happening not only for IRIs but for literals also ftp://demo.etl.linkedpipes.com:2221/b3b23a07-4e39-4fd2-a887-b36e478707d1/060/budget-athens-expenditure-2005ttl

```
terms:title "Ξ ΟΞΏΟΟΞΏΞ»ΞΏΞ³ΞΉΟΞΌΟΟ ΞΞΎΟΞ΄ΟΞ½ ΟΞΏΟ ΞΞ�ΞΌΞΏΟ ΞΞΈΞ·Ξ½ΟΞ½ (ΞΞ»Ξ»Ξ¬Ξ΄Ξ±) Ξ³ΞΉΞ± ΟΞΏ Ξ­ΟΞΏΟ 2005"@el , "Expenditure Budget of Municipality of Athens for the fiscal year 2005"@en ;
```

However if I download the debug file, it seems to be OK.

**Comment by jindrichmynarz** [comment]
@skodape: You're right. This is a bug of Google Chrome that displays the characters incorrectly. You can mark this issue as invalid.
