### ISSUE TITLE
Documentation on how to change pipeline settings.

### ISSUE THREAD

**Issue by skarampatakis** [linkedpipes/etl#132]
For a defined pipeline, I want to change some settings on the pipeline description in order to use it as a template. Except the actual modifications I want to make, what else should I change to avoid confilicts with existing pipelines? If I am guessing right, the pipeline name includes a (UNIX?) timestamp and a hash addition for components? If I change only the timestamp will this work?

**Comment by skodape** [comment]
When you import a pipeline LP updates IRIs of imported resources to avoid IRI collisions (conflicts). So you can import any pipeline as to any pipeline (even one to itself) without any previous preparation of the imported pipeline.

**Comment by skarampatakis** [comment]
Cool...thank you! I will test it.
