### ISSUE TITLE
Change on Tabular configuration fails transformation

### ISSUE THREAD

**Issue by skarampatakis** [linkedpipes/etl#134]
I noticed a problem while changing configuration on Tabular ODCS DPU. It seems that something breaks the transformation. I have made several tests. I have uploaded in Demo three different pipelines. 

1. Municipality of Athens Budget Revenue 2005 not working 

     * This is the pipeline I tried originally. It is actually the same structure as in expenditure so I had to make some small modifications. But the change in tabular breaks the transformation.

2. Municipality of Athens Budget Revenue 2005 working 

     * This is the same pipeline as above but I have changed the configuration of tabular DPU by copying the configuration from an actual expenditure working pipeline.  It works but not with desired result as I have to change the configuration of base URI. If I change it through the frontend the pipeline breaks again

3. Municipality of Athens Budget Revenue 2005 really working test

      * This is the same pipeline as above with changing the tabular configuration through editing the text in notepad. It works and has the desired result. 

I attach the mentioned pipelines as well. I can continue my work but I think this is a bug with Tabular ODCS DPU.

[Pipelines](https://github.com/linkedpipes/etl/files/250042/Downloads.zip)

**Comment by skodape** [comment]
Should be resolved by 5034a5293d6cab95f2432789ca61a460d57c076d , there were also some problems in the uv2lp conversion tool for some properties https://github.com/linkedpipes/uv2etl/commit/68c981d11a88997ef3a93b675cb191c5b2c9459b .
