### ISSUE TITLE
Pipeline rendering is slow

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#139]
Rendering [this pipeline](https://github.com/openbudgets/pipeline-fragments/blob/master/dcv/dcv_validation.jsonld) takes around half a minute (console reports `pipelineToCanvas: 25318.842ms`) in Google Chrome  50.0.2661.94 on 2.4 GHz 4-core and 8 GB RAM machine. Before the pipeline is rendered, there is a blank canvas.

It may be worth investigating if pipeline rendering can be speeded up. Meanwhile, loading indicator can be shown before the pipeline is rendered to indicate that the application is working.

**Comment by jakubklimek** [comment]
This seems to be resolved ([correct link](https://raw.githubusercontent.com/openbudgets/pipeline-fragments/master/dcv/dcv-validation/dcv_validation.jsonld)).
