### ISSUE TITLE
Execution detail hidden

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#144]
In the recent version of LP-ETL (I'm now using the latest develop version bd2be3ec8a29c12228c3751c40b4026a426940a1) the execution detail was hidden from the executions view. Now users must click through "More" (not labelled, by the way) and choose "Execution detail". This could be directly available as a single-click action or even default action when clicking on the execution.

**Comment by jakubklimek** [comment]
Actually, execution detail will be removed completely. It is replaced by its graphical version, which is the default action.

**Comment by jindrichmynarz** [comment]
Will it allow access to intermediate data? This is what I'm looking for when debugging executions.

**Comment by jakubklimek** [comment]
Of course, just click on the data unit you are interested in in the graphical view.

**Comment by jindrichmynarz** [comment]
Currently, accessing intermediate data is not possible via the graphical view:

<img width="556" alt="screen shot 2016-05-12 at 11 21 56" src="https://cloud.githubusercontent.com/assets/198642/15209879/d514ae3e-1833-11e6-850d-23c6776c5c91.png">

**Comment by jakubklimek** [comment]
You are clicking on the component, which gives you the dialog with details on the execution of the component. You need to click on the data unit (the circle).

**Comment by jindrichmynarz** [comment]
OK, the need to click on data unit is not obvious. The UI should highlight it if possible.

**Comment by jakubklimek** [comment]
This functionality is not yet complete nor documented, it may still change before it goes to master.

**Comment by jindrichmynarz** [comment]
OK. I'll leave this issue open until the feature is completed.
