### ISSUE TITLE
Feature request: passing configuration to HTTP GET DPU

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#145]
It would be useful to be able to pass configuration to HTTP GET DPU in a pipeline. For example, we may want to cache data for linked resources locally, so we retrieve their IRIs via SPARQL, dereference them via HTTP GET DPU, and store the results locally.

This is similar to #130.

**Comment by jakubklimek** [comment]
This is already planned and will be a separate component.

**Comment by jakubklimek** [comment]
http://etl.linkedpipes.com/components/e-httpgetfiles
