### ISSUE TITLE
Draggable component detail view

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#155]
The "Component detail" view can be made draggable, which can help in cases with small screen estate; e.g., projectors with low resolution.

**Comment by skodape** [comment]
We casn use something like:
https://gist.github.com/rootscity/fcf909f5820407a67c8e
as the angular material does not support dialog drag.

**Comment by jakubklimek** [comment]
Yes, this cannot be done using the technologies used.
