### ISSUE TITLE
t-excelToCsv: Bigger numbers get converted with exponent

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#159]
15077741,6 => "1.50777416E7"
4079646,24 => "4079646.24"

**Comment by jindrichmynarz** [comment]
Using the latest develop version (902f6aa93c717f7689ae1e8ea1b2dfb27988802c) t-excelToCsv converts larger numbers using the decimal notation. For example, `15077741.6` remains formatted as `15077741.6`.
