### ISSUE TITLE
Avoid sync options for IO

### ISSUE THREAD

**Issue by pwalsh** [linkedpipes/etl#16]
I see that in various places you use the sync versions of Node's IO methods. Example:
- https://github.com/linkedpipes/etl/blob/34ce8224d6f442b1fd4120b1716bed5d89926f8f/frontend/modules/templates.js#L31

This is generally considered bad practice, and, esp. if these functions need to be called during the app's life cycle (and not just as part of a one-off bootstrap when loading) could lead to significant performance issues due to how IO works in Node. Embrace [Promises](https://github.com/petkaantonov/bluebird)

**Comment by skodapetr** [comment]
Frontend used to manage pipelines and templates - the synch IO was used to read the definitions (once). Now this functionality is provided by the Storage component. With this change the IO operations were removed from the Frontend component.
