### ISSUE TITLE
Input type for password should be "password"

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#2]
The `type` attribute of the `input` elements for entering password should be set to `password`. Currently, this is not the case for the Files to SCP DPU.

**Comment by jakubklimek** [comment]
I don't think this is necessarily clear. The passwords are then stored as text in the configuration, this makes it clear that they are not secure there.

**Comment by jakubklimek** [comment]
Now it is password type, but as I said, I think it is confusing.

**Comment by jindrichmynarz** [comment]
Well, the purpose of the input type `password` is to visually obscure passwords when entering them. It provides no guarantee that password isn't stored in plain-text.
