### ISSUE TITLE
Frontend.bat fails to run when install path contains specific characters

### ISSUE THREAD

**Issue by marek-dudas** [linkedpipes/etl#202]
Running frontend.bat on Windows, when storage.components.directory or storage.pipelines.directory paths contain a directory starting with 'n' or 't', leads to "directory not found" error. Seems like in paths like "C:\\nonWinApps", the "C:\\n" gets interpreted as "C:\" and newline for some reason.

**Comment by skodape** [comment]
There are few things to consider:
0) It should be possible to use / even on windows so you would have C\:/nonWinApps
1) Support of \n seems to be a [feature](https://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html) of property file format
2) However the library we use does not support additional escaping ie. \\n , the bad news is that it seems that the library is no longer under active development. 
3) There is another issue that request the change of the property file format #68.

@marek-dudas  Taking all that into account I would preserve the current state for now, if the use of '/' solve the issue for you.

@jakubklimek  We may provide documentation on how to fill in the properties file on windows?

**Comment by jakubklimek** [comment]
@marek-dudas Does the double backslash format specified in the examples (https://github.com/linkedpipes/etl/blob/master/configuration.properties.sample#L59) help? i.e. C:\\nonWinApps as that is the proper format for Windows paths and is already documented by the examples in the file...

**Comment by marek-dudas** [comment]
I solved it previously by renaming the install folder. Checking now, using a single slash ( / ) also works. Thanks.
