### ISSUE TITLE
Unable to set default boolean value to true in component configuration

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#210]
There is no clear way of how to define a default value for a boolean configuration item as ```true``` and in addition, in the existing components, there are at least two places where this seems to be done, but does not work. One is in the configuration class (https://github.com/linkedpipes/etl/blob/develop/plugins/l-sparqlEndpoint/src/main/java/com/linkedpipes/plugin/loader/sparql/endpoint/SparqlEndpointLoaderConfiguration.java#L16) and one in the dialog.js file (https://github.com/linkedpipes/etl/blob/develop/plugins/l-sparqlEndpoint/src/main/resources/dialog.js#L4). 

This is probably caused by the getBoolean function returning "undefined", replacing all these "default" values.

**Comment by jakubklimek** [comment]
In addition, it seems that when in the Config class there is ```true``` set as default and "undefined" comes from the dialog, the value is not overwritten and the component still gets ```true``` when it runs.

**Comment by skodape** [comment]
The default configuration must be presented in the resources/configuration.jsonld file (default configuration). The configuration in dialog is not used - it's overwritten by the default configuration. The configuration in the configuration class is used at runtime, so it has no effect on the dialog. 

In future we could auto-generate the default configuration from the configuration class.
