### ISSUE TITLE
HTTP GET component doesn't follow HTTP 301 redirects

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#220]
Try downloading <https://w3id.org/lodsight/rdf-path#> using the HTTP GET component. This IRI returns the HTTP 302 status code indicating a redirection, which is followed by the HTTP GET component, however, the redirect's IRI responds with the HTTP 301 status code, which is not followed. This may be related to #100.

Tested on the most recent develop version (02a14e96fc8264fc4063b4540865ff96d27e84b8).

**Comment by jakubklimek** [comment]
http://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=http:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2Fcreated-1470248885894&execution=http:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F85deb575-ad2a-4120-99ac-2afed17b7e35

**Comment by jakubklimek** [comment]
Tested on the pipeline above and works

**Comment by jindrichmynarz** [comment]
Fixed in f45912f2460a797f12f66f73a5845f67b77a3133.
