### ISSUE TITLE
When creating template, original configuration is lost for overwritten properties

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#236]
1. Create a text holder, file.csv, "abcde"
2. Create a template from it, with content to be overwritten from the template, config "xyz123"
3. Run, it works, results in "xyz123"
4. Switch off "overwrite" in template
5. Run, you would expect "abcde", but the configuration of the instance content is empty. You dont get abcde, you don't even get an empty file, you get "xyz123".

So there are 2 issues - instance configuration gets deleted and "missing" config vs "empty" config confusion.

**Comment by skodapetr** [comment]
When an instance from a template (with inheritance support) is created, all the control properties are set to inherit. So even when the parent template does not override the instance, the instance still inherit the values from template. 
So in the above mentioned scenario you would still get "xyz123". 
To get "abcde" you need to include step
6. Turn of inheritance in the instance.
