### ISSUE TITLE
Enhancement: Make Virtuoso loader fail if file to load doesn't exist

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#244]
In 349edc6a5e6fcb9f112ade20237a18891ca683ea, Virtuoso loader fails silently when the file to load doesn't exist. It would be useful if the component first checked if the file to load exists and failed with a descriptive error before passing over to Virtuoso.

**Comment by jakubklimek** [comment]
Actually, this is not possible. The component uses an isql connection to the server and issues  Virtuoso commands. It does not access the remote file system. This behavior (no file to load is success) is a feature of Virtuoso bulk loader and in a way makes sense - it loads everything in the bulk load table...

**Comment by jindrichmynarz** [comment]
I see. Since the loaded file can be located at a remote file system, testing if it exists would require an additional SSH connection.
