### ISSUE TITLE
Enhancement proposal: Mass enable/disable loaders

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#259]
I often manually disable or enable all loaders in a pipeline. For example, this can happen when debugging a pipeline that pushes data to a remote server. A nice convenience to have would be an action to enable or disable all loaders in a pipeline.

**Comment by jakubklimek** [comment]
x-virtuoso should also be treated as a loader in this case. The question is whether to change it from "special" to loader or whether to treat it as a special case...

**Comment by jindrichmynarz** [comment]
Perhaps a boolean checkbox would be simpler than this:

<img width="193" alt="screen shot 2017-01-07 at 13 06 22" src="https://cloud.githubusercontent.com/assets/198642/21741561/25e9d790-d4da-11e6-80e7-926aba7be178.png">

**Comment by skodapetr** [comment]
Although probably more verbose then expected, the button corresponds to the actions, disable/enable all. 

IMHO the check box is more of a state or another level options. As of now simple change would result in few undefined "situations/states":

As now implemented this button is equal to manual disable-enable of all loaders. So for example when some loaders are disabled, then used press "Disable loaders" all loaders are disabled, followup "Enable loaders" action then enable all loaders - also those that were originally disabled. I would expect the check box to preserve the original state.

I would expect the checkbox to be auto-checked if all is disabled. I may disable all loaders manually, or I may delete the enabled ones, leaving only the disabled ...

What if I check the disable all and then add new loader, should it be disabled by default?

**Comment by jindrichmynarz** [comment]
Those are good points. As you say, the checkbox should correspond to the application state. Support we a checkbox "Disable all loaders". By default, it is unchecked. In all cases, new loaders start as enabled. Checking the checkbox should result in all loaders being disabled. Manually enabling some loaders should result in the checkbox being unchecked. Manually disabling all loaders should result in the checkbox being checked.

The checkbox is simply a function of the application state (which is simple to do in React and the like).

**Comment by jakubklimek** [comment]
Since we do not use checkboxes in LP-ETL this way anywhere, it would be more confusing than these simple commands, which are more in correspondence with the rest of the UI. 

In addition, a checkbox would have to behave differently when clicked by a user (start action) than when set from the program (only notify, do not start action).

**Comment by jindrichmynarz** [comment]
Why would a checkbox set by a program behave differently?

**Comment by jakubklimek** [comment]
When a user clicks the checkbox, he wants all loaders to be enabled/disabled.
When a user manually enables/disables one loader, the program needs to check/uncheck the checkbox, which this time does not enable/diasble all other loaders

**Comment by jindrichmynarz** [comment]
I don't see why there needs to be a correspondence between a checkbox, as a part of the UI, and an API call. I'm sure you don't want to model the API call as clicking on a checkbox.

In the UI, the *state* of the checkbox is a function of the application state. The *action* of the checkbox is the same as the action of the API.

**Comment by jakubklimek** [comment]
For now, we are keeping it as it is, if this causes any problems, we can reopen the discussion.
