### ISSUE TITLE
Add default configuration

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#269]
A default configuration would be nice, allowing people to just download, mvn install and run. All we now put in /data could be by default put in data under deploy, all iris could be localhost ones. Of course it would not work like this on a server, but it would on a local machind.

**Comment by yesonmect** [comment]
@jakubklimek， i met the same problem with you. As i import triple files to virtuoso，the write process is hang，but the read is ok. And in log file，i found the error “many lock waits”，at the same time，i see the same status report using “status（）；”
Can you tell me how to solve it or give me some suggestion？
Thanks very much！

**Comment by skodapetr** [comment]
The default configuration was added in a30499f0ab04269d82887554bab3701ee03ba4d2 .
