### ISSUE TITLE
Error while deploying LP

### ISSUE THREAD

**Issue by MariaStrotou** [linkedpipes/etl#270]
Hi, 
i am trying to deploy LP-etl on my laptop and I have these errors.

I am on Win7 64bit with latest Java JDK and Maven.

Thank you in advance.

[out.txt](https://github.com/linkedpipes/etl/files/657284/out.txt)

**Comment by jakubklimek** [comment]
Hi,

thanks for trying LP-ETL.

The error suggests that you are not able to access http://uv.opendata.cz/osgi/sesame/sesame-runtime-osgi-4.0.1-SNAPSHOT-custom.jar 

It works from here, can you try it manually? (just downloading the file to make sure your machine can access it)?

Thanks

**Comment by jakubklimek** [comment]
Hi, we are now hosting the jarfile in a more reliable repository, which is now working as expected.

**Comment by MariaStrotou** [comment]
Hi,
thank you very much for supporing me in the process of installation LP-ETL.
It was successfully installed and now it works as expected without any problem.

Thanks again.
