### ISSUE TITLE
Disk space freed only after front-end is shut

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#272]
Disk space used by execution data is not freed when the execution is deleted, but only when the front-end is shut. This can be problematic on long-running instances.

Tested with a35247659f6a51b4be95397eebbe616d0b36ba18.

**Comment by skodapetr** [comment]
By execution data you mean "executor/working" ? 

By frontend do you really mean "frontend"? As this component does not manage any of the working directories.

**Comment by jindrichmynarz** [comment]
Yes, I meant `executor.execution.working_directory`.

However, I found out that the execution data was deleted when the execution was deleted, it was only a bit slow, which originally made me think there was a problem.
