### ISSUE TITLE
Missing field configuration from uv-t-tabular.

### ISSUE THREAD

**Issue by fathoni** [linkedpipes/etl#274]
In uv-t-tabular component, the configuration for "Class for a row entity" field is mysteriously removed (previously it contained skos:Concept or qb:Observation).  This happened to most of the pipelines from OBEU project 8181 server instance. I have to re-add these configs manually again. Unsure how to replicate this bug. 

P.S. This had previously happened in the Files to SCP component, in which the content of "target directory" was also missing.

**Comment by skarampatakis** [comment]
I have the same issue. Just importing a pipeline from url (for instance [Athens Expenditure 2005](https://raw.githubusercontent.com/openbudgets/datasets/master/greek-municipalities/municipality-of-athens/pipelines/Municipality%20of%20Athens%20Budget%20expenses%202005.jsonld) can recreate the problem. I have test on a fresh local installation. 

The property is set in the pipeline as you can see. Once I change configuration on tabular to re-insert row class property, LP adds a few more lines. Find attached the pipelines from my local instance after import from the original. On the second one I have manually added the row class property.


[pipelines.zip](https://github.com/linkedpipes/etl/files/684445/pipelines.zip)
