### ISSUE TITLE
Improper uv-t-tabular mapping

### ISSUE THREAD

**Issue by fathoni** [linkedpipes/etl#277]
The component uv-t-tabular1 in [this pipeline](http://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=http:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2Fcreated-1483537348679&execution=http:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2Fd5f5d3d4-a5b8-4aa5-adb6-539a7385e27c) outputs improper mapping in contrast to defined mapping. This can be seen in the [debugging result] - ftp://demo.etl.linkedpipes.com:2221/d5f5d3d4-a5b8-4aa5-adb6-539a7385e27c/006/data.trig

**Comment by skodapetr** [comment]
@fathoni Could you please check that the http://demo.etl.linkedpipes.com instance now gives you the expected results?

If the problem is resolved I would merge the fix to the master as well.

**Comment by fathoni** [comment]
Seems that the demo server is down. I will check again in around 30 minutes.
