### ISSUE TITLE
Enhancement: GeoTools undocumented IRI pattern

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#285]
The GeoTools component outputs instances of `schema:GeoCoordinates` that follow the IRI pattern of the input resource IRI with `/wgs84` appended. This IRI pattern is not [documented](http://etl.linkedpipes.com/components/t-geotools). It has a few problems.

Perhaps a minor problem is that the component allows to reproject coordinates to several coordinates reference systems, not only WGS84. In that cases the IRI pattern is misleading.

Another minor problem is that the component implicitly expects the identifiers of the reprojected points to be IRIs. When it encounters a blank node, it errors out.

More interesting problem is that the ETL developer needs to be aware of this IRI pattern not to lose the connection between the reprojected points and the resources that link them. Typically, the developer needs to add a SPARQL Update that constructs links to the reprojected points by following the same IRI pattern.

There are several possible solutions to this issues. One of them is to make the GeoTools component work more like SPARQL Update instead of SPARQL CONSTRUCT. In this way, the component would overwrite the provided points with the reprojected coordinates.

Perhaps a clearer solution is to ask the user to provide a predicate that links a resource (e.g., a `schema:Place`) to the reprojected point. Then it would create new triples using this predicate to maintain the links between the reprojected points and the resources that link to them. Currently, there's an option to provide a predicate that links the original point to its reprojected version (`schema:geo` by default). However, this link connects two points instead of linking a place to the reprojected point (e.g., `schema:sameAs` might be a more suitable default).

**Comment by jindrichmynarz** [comment]
372d8a6faf1ee4bcebc0082813552b4f2c216c93 solves the first two minor problems, but leaves the larger problems mentioned later aside.

**Comment by jakubklimek** [comment]
The rest of the issue is about a missing link between the old and the new points, which is actually there, not missing. You can set it in the "Predicate used to connect output entity with" setting (which may be renamed).

**Comment by jindrichmynarz** [comment]
OK, there's a link between the old and new points (e.g., I use `schema:sameAs`). I was asking for a link between the geolocated resource and the new point. This can be also done in a follow-up SPARQL Update/CONSTRUCT, so I think this is fine.

**Comment by jakubklimek** [comment]
Yes, that should be done this way since the geolocated resource itself is out of scope for the component.
