### ISSUE TITLE
Enhancement: Clarify labels for coordinate reference systems in GeoTools component

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#288]
Similarly to #283, it would be useful to clarify the labels of inputs for coordinate reference systems in the GeoTools component. "Default coordinates type" can be "Default coordinate reference system" and "Type of output coordinates" can be "Output coordinate reference system" to make it consistent with the documentation changes in #283.

**Comment by jakubklimek** [comment]
Already done.

**Comment by jindrichmynarz** [comment]
Sorry, I was running an older commit.
