### ISSUE TITLE
End time is not filled in in when watching component execution detail

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#292]
![image](https://cloud.githubusercontent.com/assets/718827/21923117/7ecd81bc-d972-11e6-874e-ae961e7f2190.png)

**Comment by skodapetr** [comment]
Can you provide steps to reproduce?

**Comment by jakubklimek** [comment]
When watching execution in the graphical view, click a component that is currently running (Blue), opening the execution detail dialog as in the screenshot. When this component finishes, the End: remains empty.
