### ISSUE TITLE
Unclear meaning of buttons displayed on hover for DPU instances on canvas

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#3]
The meaning of buttons displayed on hover for DPU instances placed on canvas is unclear. Currently, only the buttons' colours hint their function, see:

<img width="245" alt="screen shot 2016-01-26 at 11 33 28" src="https://cloud.githubusercontent.com/assets/198642/12578373/c812a8f6-c420-11e5-88e4-434c2bd79a12.png">

Icons representing the actions and on hover titles should be added to make the buttons' functionalities clearer.

**Comment by skodape** [comment]
Icons have been added instead of colours.
