### ISSUE TITLE
Feature request: Enable configuration input to components.

### ISSUE THREAD

**Issue by skarampatakis** [linkedpipes/etl#302]
Some components already have the ability to get configuration properties as configuration input from other components. It would be useful this could be possible for other components as well. 
For instance, RDF to file component could get output graph property from a SPARQL component, or pipeline input or even from DCAT-AP component.

**Comment by skodapetr** [comment]
@skarampatakis Should we start with some components (for example RDF to file, ... ) or is it more like a general request to add runtime configuration to all components?

**Comment by skarampatakis** [comment]
Hi, while I believe it could ve useful for every component, tabular, rdf to
file and loaders should be priorities. I think that SPARQL components are
already configurable.

Στις 14 Φεβ 2017 09:21, ο χρήστης "Petr Škoda" <notifications@github.com>
έγραψε:

**Comment by jakubklimek** [comment]
@skarampatakis Is there any other component with missing configuration input that you need fixed?
