### ISSUE TITLE
Enhancement: Better error message for empty input in Graph Store Protocol plugin

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#303]
When provided with empty input, the Graph Store Protocol plugin returns this error: "IllegalArgumentException : Entity may not be null". A more descriptive error that indicates clearly what's wrong may be "Input is empty".

Tested on 41fe992fbd9fee5d17c1cf919aa3f62dfc7aa5d0.

**Comment by skodapetr** [comment]
@jindrichmynarz Do you have a pipeline, or whole stack trace? I tried GraphStoreProtocol with no input without any exception (Fuseki storage).

**Comment by jindrichmynarz** [comment]
I can no longer reproduce the issue in 681c4cd5b48d639cf4716110b81224cb1bc03a29. The current behaviour is that when provided with empty input the Graph Store Protocol plugin runs successfully, however nothing is loaded, as expected.
