### ISSUE TITLE
HTTP Get downloads gzipped file when web server uses compression

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#304]
When downloading files from web servers which use gzip compression, the downloaded file stays gzipped. The expected behavior is (probably) that is will be ungzipped.

**Comment by skodapetr** [comment]
Can you provide the gzipped http source link ? Should this happen by default or should there be a checkbox "decompress compressed content" ?

**Comment by jakubklimek** [comment]
I cannot. will reopen when this happens again.

**Comment by jakubklimek** [comment]
http://seznam.gov.cz/ovm/datafile.do?format=xml&service=seznamovm

**Comment by jakubklimek** [comment]
http://opendata.mzp.cz/api/3/action/package_list

**Comment by jakubklimek** [comment]
See [this execution](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2F1569401891399&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F1569412186573-618-2f528c07-ba62-4f69-8a76-6c38b5e2655a). While the HTTP Get now downloads the file correctly, the HTTP get list downloads nothing and there is a null pointer exception in the Report.
