### ISSUE TITLE
SSL-Handshake error during Maven build

### ISSUE THREAD

**Issue by mlukasch** [linkedpipes/etl#312]
Hello, Im getting an error during the Build via Maven.
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (copy-dependencies) on project dependencies: An Ant BuildException has occured: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching uv.opendata.cz found.
[ERROR] around Ant part ...<get dest="../deploy/osgi/external">... @ 4:39 in /etl/deploy-dependencies/target/antrun/build-main.xml`

**Comment by mlukasch** [comment]
Maybe I have to download the self-signed certificate to trusted CAs on the client side. Can be done by updating the CACERT file in the the JRE_HOME/lib directory.

**Comment by mlukasch** [comment]
Seems to work now by manually downloading the certificate: https://github.com/openbudgets/integration/blob/master/docker-config/linkedpipes/uv.opendata.cz.cert and added it to the jre: https://github.com/openbudgets/integration/blob/master/docker-config/linkedpipes/Dockerfile
This will break however whenever the certificate is exchanged. For a permanent solution it might be better not to use a self signed certificate for the domain uv.opendata.cz

**Comment by jakubklimek** [comment]
We are working on it, moving the file and creating a Let's Encrypt certificate, will be resolved today.

**Comment by mlukasch** [comment]
Thank you

**Comment by jakubklimek** [comment]
Fixed in master branch

**Comment by jakubklimek** [comment]
In current develop, soon to be merged to master, there is a dependency to be downloaded via HTTP with SNI SSL certificate on the server. In order for this to work, Java 8 has to be newer than update 101 and Maven has to be newer than 3.2.5. This is reflected in LP-ETL README.
