### ISSUE TITLE
Build fails on x-virtuoso

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#314]
Building the develop version 734a87b2a5eef4a6e3ffbec051cc342a707d021f fails on x-virtuoso:

```
[ERROR] Failed to execute goal on project x-virtuoso: Could not resolve dependencies for project com.linkedpipes:x-virtuoso:bundle:0.0.0: Failed to collect dependencies at com.openlinksw.virtuoso:virt_rdf4j:jar:20170111: Failed to read artifact descriptor for com.openlinksw.virtuoso:virt_rdf4j:jar:20170111: Could not transfer artifact com.openlinksw.virtuoso:virt_rdf4j:pom:20170111 from/to artefacts.linkedpipes.com (https://artefacts.linkedpipes.com/repository/maven-public/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
```

**Comment by jakubklimek** [comment]
Do you have Java newer than 1.8 update 101?

**Comment by jindrichmynarz** [comment]
I had a slightly minor update of Java 1.8. Now:

```
$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

Compilation now fails with a different error on x-virtuoso:

`[ERROR] Failed to execute goal on project x-virtuoso: Could not resolve dependencies for project com.linkedpipes:x-virtuoso:bundle:0.0.0: Failed to collect dependencies at com.openlinksw.virtuoso:virt_rdf4j:jar:20170111: Failed to read artifact descriptor for com.openlinksw.virtuoso:virt_rdf4j:jar:20170111: Could not transfer artifact com.openlinksw.virtuoso:virt_rdf4j:pom:20170111 from/to artefacts.linkedpipes.com (https://artefacts.linkedpipes.com/repository/maven-public/): hostname in certificate didn't match: <artefacts.linkedpipes.com> != <demo.etl.linkedpipes.com> OR <demo.etl.linkedpipes.com> -> [Help 1]
`

**Comment by jakubklimek** [comment]
OK, now, do you have Maven > 3.2.5?

**Comment by jindrichmynarz** [comment]
OK. After updating to Maven 3.3.9 the compilation succeeded.

It would be great if LP-ETL can specify the required versions of Java and Maven, test them automatically, and return descriptive errors when the requirements are not satisfied.

**Comment by jakubklimek** [comment]
The requirements are now specified in readme in github. As to automatic checking of versions, I am not sure what we can do... @skodapetr ?

**Comment by echondrok** [comment]
BUILD FAILURE on x-virtuoso for both master and develop branches.
I'm using Java 1.8 update 144 and Maven 3.3.9.
```
[ERROR] Failed to execute goal on project x-virtuoso: Could not resolve dependencies for project com.linkedpipes:x-virtuoso:bundle:0.0.0: Failed to collect dependencies at com.openlinksw.virtuoso:virt_rdf4j:jar:20170111: Failed to read artifact descriptor for com.openlinksw.virtuoso:virt_rdf4j:jar:20170111: Could not transfer artifact com.openlinksw.virtuoso:virt_rdf4j:pom:20170111 from/to artefacts.linkedpipes.com (https://artefacts.linkedpipes.com/repository/maven-public/): Failed to transfer file: https://artefacts.linkedpipes.com/repository/maven-public/com/openlinksw/virtuoso/virt_rdf4j/20170111/virt_rdf4j-20170111.pom. Return code is: 502 , ReasonPhrase:Bad Gateway. -> [Help 1]
```

**Comment by jakubklimek** [comment]
@echondrok Fixed. It was on our side, this one jar is hosted in our repository manager, which failed to run with java 9.

**Comment by echondrok** [comment]
Thanks for the immediate reply @jakubklimek . The build was successful!

**Comment by openVeronica** [comment]
How to fix the problem exactly?  I got the same error:

[ERROR] Failed to execute goal on project x-virtuoso: Could not resolve dependencies for project com.linkedpipes:x-virtuoso:bundle:0.0.0: Failed to collect dependencies at com.openlinksw.virtuoso:virt_rdf4j:jar:20170111: Failed to read artifact descriptor for com.openlinksw.virtuoso:virt_rdf4j:jar:20170111: Could not transfer artifact com.openlinksw.virtuoso:virt_rdf4j:pom:20170111 from/to artefacts.linkedpipes.com (https://artefacts.linkedpipes.com/repository/maven-public/): Received fatal alert: handshake_failure -> [Help 1]

I run the install with java 1.8.0_151 and maven 3.5.3.

**Comment by jakubklimek** [comment]
@openVeronica we have recently strengthened the SSL security on the artefacts.linkedpipes.com server and I guess you do not have [JCE](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html) installed. When you install it, the connection should be successful.

**Comment by MBrighty** [comment]
@jakubklimek I'm getting a build failure as a result of x-virtuoso. I am using Java 10.0.1 and Maven 3.5.3. The full error message is:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project x-virtuoso: Compilation failure: Compilation failure: 
[ERROR] Source option 5 is no longer supported. Use 6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :x-virtuoso`

**Comment by jakubklimek** [comment]
@MBrighty Java 10 is not supported yet. Installation instructions mention Java 8 or 9 and you can monitor the issue here: https://github.com/linkedpipes/etl/issues/533
