### ISSUE TITLE
Debug to incorrectly invalidates already run components

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#327]
First, I run a pipeline and it looks like this:
![image](https://cloud.githubusercontent.com/assets/718827/24329069/a82cdcee-11fb-11e7-950e-55b99dbae8f9.png)
Then, I do some changes and debug to on another part of the pipeline:
![image](https://cloud.githubusercontent.com/assets/718827/24329071/c3107fd4-11fb-11e7-8296-29ec8af86876.png)
When the execution fails, I see that the orginal piece of the pipeline is no longer in an "already done" state even though this execution did not touch it:
![image](https://cloud.githubusercontent.com/assets/718827/24329077/f09d34ec-11fb-11e7-8a35-8dc2d7264f84.png)
When I do this again, even less of the pipeline is in "already done" state:
![image](https://cloud.githubusercontent.com/assets/718827/24329078/051923ae-11fc-11e7-9032-0df5c4e39957.png)

**Comment by jakubklimek** [comment]
Happened again. See these executions (in order of execution):

1. https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2Fcreated-1491819645937&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F8f61a149-c9ff-44ef-9546-e1941038a2a3
2. https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2Fcreated-1491819645937&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F290934de-6d90-4a78-a875-f42920ca57ed

In the second execution, the 2 components are invalidated:
![image](https://cloud.githubusercontent.com/assets/718827/24870147/a9df9902-1e15-11e7-9a90-7d816cbd2091.png)

Could it be that XSLT failed before the two were marked as "already run before"?

**Comment by skodapetr** [comment]
It could be, since that time we change the "unpacker" component and while doing so also make the component execution order deterministic.  Both of these changes may fix the issue.
