### ISSUE TITLE
l-sparqlEndpoint ignores HTTPS?

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#328]
When I try to load data to https://nkod.opendata.cz/sparql-auth, I get:
```
Cause: 
Component execution failed.

Root cause: 
RepositoryException : <html>
 <head><title>301 Moved Permanently</title></head>
 <body bgcolor="white">
 <center><h1>301 Moved Permanently</h1></center>
 <hr><center>nginx/1.10.3</center>
 </body>
 </html>

Messages:
```

However, this message can only come from http://nkod.opendata.cz/sparql-auth, which is redirected to https...

**Comment by skodapetr** [comment]
The ```https://nkod.opendata.cz/sparql-auth``` return redirect to ``` https://nkod.opendata.cz/sparql-auth/```. However the POST by default does not follow redirect and thus the execution fail. 

Try to use ``` https://nkod.opendata.cz/sparql-auth``` as endpoint URL.
