### ISSUE TITLE
Progress not shown correctly

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#333]
This component showed 10 and 20% yesterday. Now, I would expect it to show 10, 20 and 30%, but it shows only 30%.
![image](https://cloud.githubusercontent.com/assets/718827/24490690/0542ffbe-1524-11e7-876a-5904d72b9f02.png)

**Comment by skodapetr** [comment]
Do we have a pipeline or steps to reproduce?

**Comment by jakubklimek** [comment]
Happened again now:
![image](https://user-images.githubusercontent.com/718827/26961736-5466bf28-4ce1-11e7-93f2-2761831ab4b6.png)
