### ISSUE TITLE
Possible bug in SPARQL endpoint chunked list

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#336]
Multiple SPARQL endpoints, e.g. ```http://data.semanticweb.org/sparql``` returned the following error:
```
Lexical error at line 11, column 13.  Encountered: \" \" (32), after : \"VALUES\"
```
while other endpoints processed the query OK.

**Comment by skodapetr** [comment]
The endpoint probably does not support SPARQL 1.1
