### ISSUE TITLE
Cannot open HTML CSS dialog in UV import

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#337]
https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2Fcreated-1479731132493

**Comment by skodapetr** [comment]
The references in the configuration are broken (configuration is not valied) - I'm not sure how this happened.

I try to re-import the pipeline from UV, export and import to another instance. everything works fine.

**Comment by jakubklimek** [comment]
Can reopen if this happens again
