### ISSUE TITLE
Enhancement: unstyled empty executions

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#339]
The list of of empty executions contains an unstyled paragraph (notice the default styling of `a:visited`):

<img width="295" alt="screen shot 2017-04-07 at 14 04 52" src="https://cloud.githubusercontent.com/assets/198642/24799431/54cd55fc-1b9b-11e7-8b85-57ac163ca4a8.png">

It may be better to put this in line with the style of the rest of LP-ETL.

Tested using the latest develop version (2cdf1becdb95be5bc78782beab943c81f3763b19).

**Comment by skodapetr** [comment]
@jindrichmynarz What do you mean by "put in line with the style" ? Do you have any example?

**Comment by jindrichmynarz** [comment]
Sure: typical links in LP-ETL are styled in `rgb(33,150,243)` and `Roboto`, such as:

<img width="143" alt="screen shot 2017-04-07 at 22 13 46" src="https://cloud.githubusercontent.com/assets/198642/24818163/a033bc86-1bdf-11e7-813c-7996063086a7.png">

This made me think that perhaps the lack of styling is an omission.

**Comment by skodapetr** [comment]
@jakubklimek Should we use a button-look or stick with a link-style?

**Comment by jakubklimek** [comment]
Actually, buttons are used to indicate actions (run, save, close) and this is indeed a link (go to list of pipelines). I think we should stick to the link.

**Comment by jindrichmynarz** [comment]
I didn't mean to suggest that it should be styled as a button. What I meant is that the inline link style is not consistent with the rest of the styling of LP-ETL. In fact, there is no inline link style, hence the default styling.

**Comment by jakubklimek** [comment]
There are links in some dialogs (e.g. DCAT dataset) and the documentation, typically linking to specifications etc.

**Comment by jindrichmynarz** [comment]
Yes, and these too are not styled. I.e. they use the default CSS for links.

**Comment by jakubklimek** [comment]
That is, however, intentional

**Comment by jindrichmynarz** [comment]
OK, then it's fine.
