### ISSUE TITLE
Value parser throws Invalid type: Values

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#342]
[Value parser](http://etl.linkedpipes.com/components/t-valueparser) throws `com.linkedpipes.etl.executor.api.v1.LpException: Invalid type: Values`.  A [pipeline to replicate the issue](https://github.com/linkedpipes/etl/files/908111/Value.parser.error.jsonld.zip).

Tested using the develop version 2cdf1becdb95be5bc78782beab943c81f3763b19.

**Comment by skodapetr** [comment]
In the pipeline you use \\d while \d should be used to match a decimal. Should we add example to the documentation to make it clear that a single \ is enough?

**Comment by jindrichmynarz** [comment]
The pipeline works with single backslash. As commented elsewhere, I think it should be documented what flavour of regular expressions the component expects. I used the double backslash, since I was expecting regular expressions from SPARQL.

**Comment by jakubklimek** [comment]
Documented

**Comment by jindrichmynarz** [comment]
I think the documentation should be more specific. Instead of writing that it *"is a "single backslash" regex flavor"*, write that it is the [SPARQL syntax](https://www.w3.org/TR/sparql11-query/#func-regex), the [Java syntax](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html), or else.

**Comment by jakubklimek** [comment]
Copied from files filter.
