### ISSUE TITLE
GeoTools: unsupported placeholder CRS

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#344]
The [GeoTools](http://etl.linkedpipes.com/components/t-geotools) component uses `EPSG:5514` as a placeholder coordinate reference system (CRS). However, when this CRS is used, exception is thrown: `NoSuchIdentifierException : No transform for classification "Krovak (North Orientated)".` It would be better to use a supported CRS as a placeholder.

Tested using the develop version 2cdf1becdb95be5bc78782beab943c81f3763b19.

**Comment by skodapetr** [comment]
The component how have select box (instead of plain text input). I also tested example pipeline (from demo.linkedpipes.com), it use "EPSG:5514" as input and it works fine. Can you please re-test?

**Comment by jindrichmynarz** [comment]
I'm unable to test this due to formatting exception. It seems that the component does not support WKT points as it used to. For example, this input:

```ttl
<urn:uuid:1ada760b-3dd9-4d86-9c6b-2ffcb6f9a9eb> <http://www.opengis.net/ont/gml#pos> "POINT(50.0888931 14.4824917)" ;
	<http://www.opengis.net/ont/gml#srsName> "EPSG:4326" ;
	a <http://www.opengis.net/ont/gml#Point> .
```

This exception is thrown:

```
Caused by: java.lang.NumberFormatException: For input string: "POINT(50.0888931"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.linkedpipes.plugin.transformer.geotools.GeoTools.process(GeoTools.java:177)
	... 4 common frames omitted
```

**Comment by skodapetr** [comment]
@jindrichmynarz @jakubklimek Should we also support aforementioned format?

You can see the supported format in the example pipeline at demo.linkedpipes.com .

**Comment by jindrichmynarz** [comment]
Which pipeline?

The supported format should also be [documented](http://etl.linkedpipes.com/components/t-geotools).

**Comment by skodapetr** [comment]
@jindrichmynarz On the documentation page is link to Sample pipeline .

**Comment by jindrichmynarz** [comment]
I found the [demo pipeline](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2Fcreated-1483604174548).

After long digging through the GML's XML schemas (even with the help of an XML IDE) I managed to find that the range of `gml:pos` is indeed a list of `xsd:double`s separated by whitespace. This should be added into the documentation.

**Comment by jindrichmynarz** [comment]
EPSG:5514 is supported in e6850ae954b511710e9699b7d7741657a5a80444.

**Comment by skodapetr** [comment]
@jakubklimek Would you add this information to documentation?

**Comment by jindrichmynarz** [comment]
I already separated the documentation issue to #424.
