### ISSUE TITLE
GeoTools: negative coordinates unsupported

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#345]
The [GeoTools](http://etl.linkedpipes.com/components/t-geotools) component doesn't support negative coordinates. For example `POINT(144.965435 -37.817169)` (Melbourne, Australia) has negative latitude.  When trying to convert this coordinate, an exception is thrown: `java.lang.NumberFormatException: For input string: "POINT(144.965435"` (latitude truncated for some reason). A [pipeline to replicate the issue](https://github.com/linkedpipes/etl/files/908127/Test.GeoTools.negative.coordinates.jsonld.zip).

Tested using the develop version 2cdf1becdb95be5bc78782beab943c81f3763b19.

**Comment by skodapetr** [comment]
The problem is caused by the ```POINT(``` string. 

The components expect the ```http://www.opengis.net/ont/gml#pos``` to be of value ```X Y`` where ```X``` and ```Y``` are numbers.

**Comment by jindrichmynarz** [comment]
OK. I thought that the expected values should be WKT POINTs. I can confirm that the reprojection works with a string of "X Y" coordinates. It should be documented and possibly validated that this is the required format of input coordinates.
