### ISSUE TITLE
Execution view: pipeline name is editable, but not saved

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#346]
You can edit pipeline name from the execution view, however, it is not saved. Editing pipeline name should be either disabled in the execution view or enabled and saved correctly.

Tested using the develop version 2cdf1becdb95be5bc78782beab943c81f3763b19.

**Comment by jakubklimek** [comment]
This is consistent with edit mode, as the new pipeline name is also not saved there until you save the pipeline. When you change the name in execution view, then go to edit mode and save, it is saved. When you do not go to edit mode, there is no way to save the pipeline and therefore the change is not saved.

**Comment by jindrichmynarz** [comment]
I find this confusing. I think it would be clearer if the pipeline name could be edited only in the edit mode, just as other edits.

**Comment by jakubklimek** [comment]
Pipeline name can no longer be edited in execution view.
