### ISSUE TITLE
Tabular: numbers are mapped to strings

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#347]
Tabular maps numbers from CSV to strings instead of a numeric datatype. Here's a 
[pipeline to reproduce the issue](https://github.com/linkedpipes/etl/files/908192/Test.numbers.in.Tabular.jsonld.zip).

Tested using the develop version 2cdf1becdb95be5bc78782beab943c81f3763b19.

**Comment by jindrichmynarz** [comment]
I know that numbers would have to be auto-detected, but I think there was a configuration option to do that.

**Comment by skodapetr** [comment]
So the requirement is to add type auto-detection for each row/cell ~ this would be an "extension" to CSV on the web?

Should we support integers in custom mapping?

**Comment by jindrichmynarz** [comment]
If this feature was not available before, then I think it we can leave the component as is. Casting strings to more specific data types can be done in subsequent SPARQL updates of the generated data.

However, this behaviour should be documented to set the expectations clear. I think users would typically expect an option to auto-detect specific data types, as is the case in tools like Excel or OpenRefine.

**Comment by jakubklimek** [comment]
Documented
