### ISSUE TITLE
Component execution end time not displayed for "executed in other execution"

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#352]
![image](https://cloud.githubusercontent.com/assets/718827/24870885/1cfe4dd2-1e18-11e7-9f44-67a42e9fcb52.png)

**Comment by skodapetr** [comment]
@jakubklimek We can add the "end" however we may somehow emphasise that this is not the execution time of a component, but rather time it took to load content of mapped data units.

**Comment by jakubklimek** [comment]
Actually it should be the end time from the previous execution, I think

**Comment by skodapetr** [comment]
Should be implemented in the current version.
