### ISSUE TITLE
l-sparqlEndpoint error message not UTF-8

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#354]
https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2Fcreated-1489580500989&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F24de4ffc-0201-4b81-980a-ee35bb88efbf
e.g.
```
<https://ruian.linked.opendata.cz/slovnÃ­ky/adresnÃ­-mÃ­sta/AdresnÃ­PoÅ¡ta#76317> <http://www.w3.org/2004/02/skos/core#notation> "76317"^^<http://www.w3.org/2001/XMLSchema#string> . 
```

**Comment by skodapetr** [comment]
l-sparqlEndpoint is using RDF4J library to load into an endpoint. The library has been updated several times since this issue was created. In addition the referenced pipeline fail on extractor so I can not try to reproduce the issue.
