### ISSUE TITLE
l-filesToScp: Tries to clear directory before creating it

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#355]
When both "create" and "clear" directory options are enabled and a non-existent directory is entered, the component first tries to clear the non-existent directory and fails with the wrong "Cannot create directory" exception.

**Comment by skodapetr** [comment]
The directory was created empty. Then rm -r {directory}/* because of empty directory.

**Comment by jakubklimek** [comment]
Now, when "create directory" is enabled an the directory exists, the component fails. We should change this to "create directory if not exists"
