### ISSUE TITLE
Excel to CSV cannot produce multiple CSVs

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#359]
Excel to CSV component cannot produce a CSV for each sheet in the Excel file. If the "Output file name" is left empty, then `LpException : http://plugins.linkedpipes.com/ontology/t-excelToCsv#fileName` is raised. When the "Output file name" is provided, then `LpException : File already exists` is raised.

Tested using the develop version 9a42adc02da86a8cdc00bfa6fdd45ac09f568a05.

**Comment by skodapetr** [comment]
It is missing in the documentation. You can use {FILE} and {SHEET} placeholders in the "Output file name" and thus generate multiple csv files.

@jakubklimek Can you please update documentation?

**Comment by jindrichmynarz** [comment]
I can confirm that when you distinguish the produced CSVs using `{SHEET}`, then the component is able of producing multiple CSVs.
