### ISSUE TITLE
Templated XSL to CSV doesn't support Office 2007+ XML format

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#361]
When used with `*.xslx` files [Templated XSL to CSV](http://etl.linkedpipes.com/components/t-templatedxlstocsv) throws this exception:

> OfficeXmlFileException : The supplied data appears to be in the Office 2007+ XML. You are calling the part of POI that deals with OLE2 Office Documents. You need to call a different part of POI to process this data (eg XSSF instead of HSSF)

Tested using the develop version 9a42adc02da86a8cdc00bfa6fdd45ac09f568a05.

**Comment by jakubklimek** [comment]
This is developed by third party and serves well in CSSZ (for xls). Probably won't be fixed any time soon.

**Comment by jindrichmynarz** [comment]
So perhaps the documentation can say that it's only for older `*.xls` files and not for `*.xlsx`.

**Comment by jakubklimek** [comment]
Done
