### ISSUE TITLE
t-uv-tabular

### ISSUE THREAD

**Issue by patzomir** [linkedpipes/etl#362]
Hi Guys,

Tried using the Tabular ODCS. The simple mapping doesn't seem to work at all. Tried using on/off "Has header". You could use this [pipeline](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2Fcreated-1466585485365&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F7c6492f2-de9e-4c85-a2c6-6d41a837c0cal) to replicate the case.

Best regards,
Patzo

**Comment by jakubklimek** [comment]
Fixed
