### ISSUE TITLE
Excel to CSV throws "Wrong cell type" exception

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#365]
Excel to CSV can throw `java.lang.IllegalArgumentException: Wrong cell type: 2 on row: 557 column: 7`:

```
Caused by: java.lang.IllegalArgumentException: Wrong cell type: 2 on row: 557 column: 7
	at com.linkedpipes.plugin.transformer.excel.to.csv.Parser.getCellValue(Parser.java:225)
	at com.linkedpipes.plugin.transformer.excel.to.csv.Parser.processSheet(Parser.java:146)
	at com.linkedpipes.plugin.transformer.excel.to.csv.Parser.processEntry(Parser.java:70)
	at com.linkedpipes.plugin.transformer.excel.to.csv.ExcelToCsv.execute(ExcelToCsv.java:39)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:44)
	... 2 common frames omitted
```

I am not sure what this error indicates and how to fix it.

[Pipeline to reproduce the issue](https://github.com/linkedpipes/etl/files/952773/Local.Administrative.Units.LAU.2016.jsonld.zip).

Tested using the develop version 9a42adc02da86a8cdc00bfa6fdd45ac09f568a05.

**Comment by skodapetr** [comment]
@jindrichmynarz The component did not support formula evaluation (same as tabular in UV).

**Comment by jindrichmynarz** [comment]
If evaluating formulas is difficult, would it also be an option to allow ignoring formulas?

The formula in this particular spreadsheet is an error, which introduces an additional empty row.

**Comment by skodapetr** [comment]
@jindrichmynarz It's now option to evaluate them - to preserve backwards compatibility to not evaluate by default.
The spreadsheet  has multiple sheet, could you please be more specific?

**Comment by jindrichmynarz** [comment]
In this particular spreadsheet, there is one formula. It is located in the "HR" sheet at the last row. It purports to compute a sum of the "n.a." values.

A workable solution is to have the formula evaluated and then filter out the generated empty row (empty besides the invalid sum) in post-processing. I think this is fine, but perhaps some people might find it useful to be able to ignore formulas. In either case, the behaviour should be documented.

**Comment by jakubklimek** [comment]
I do not see the issue. Excel evaluates the sum to 0, as does the Excel to CSV component (see [execution](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2Fcreated-1495633664254&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2Fb3c7aa1c-c860-435c-a7c9-a8eab5084db0))

**Comment by jindrichmynarz** [comment]
Now that the issue is fixed, the subsequent issue was to document the option to evaluate formulas. This is now documented. In that sense, the issue is resolved.

A follow-up question was concerned with making it possible to ignore formulas. This can be either exposed as an additional configuration or the default behaviour if evaluation of formulas is switched off (currently, the default is to throw an error when a formula is found).

**Comment by jakubklimek** [comment]
OK. 

Since AFAIK Excel does not support switching off formulas and neither does the library, i.e. it would have to be manually checked, I would say that unless we have a use case for this that cannot be solved otherwise, we do not implement this.

**Comment by jindrichmynarz** [comment]
Sure. Then I think this issue is closed.
