### ISSUE TITLE
Excel to CSV: column end incremented

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#367]
The "Column end" option in the Excel to CSV component is incremented by one. For example, when 2 is specified, 3 columns are produced. Pipeline to reproduce the issue is [here](https://github.com/linkedpipes/etl/files/954281/Local.Administrative.Units.LAU.2016-.test.column.end.jsonld.zip).

Tested using the develop version 9050cd725dc037e80aacf50275ac817a843cf82c.

**Comment by skodapetr** [comment]
This was related to #363. "Column end" is now index the of the column to convert. Is this ok, or should we update it to be the "first not converted"?

**Comment by jindrichmynarz** [comment]
Yes, I think it not behaves as users may expect: the column end is the index of the last included column.
