### ISSUE TITLE
Text holder: when no file name is provided, LP-ETL throws the exception "File already exists"

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#380]
When no file name is provided to the Text holder component, LP-ETL throws `LpException : File already exists`. This may indicate that the configuration is not validated, since the file name is required.

Tested using the develop version 1119fce83501aeee0ca73c466d89aa09ac042433.

**Comment by jindrichmynarz** [comment]
In f73314dc3ef7f8ce67a99bda1a88a2eb4c84d98f an execution error "Missing file name" is thrown. Would it be possible to throw validation warnings directly when a component's configuration is saved? I.e. it would also be implemented by the front-end.

**Comment by jakubklimek** [comment]
This is not a trivial task, it would mean duplication of validation rules or development of a non-trivial solution for validation reusable both in frontend and backend.

**Comment by jindrichmynarz** [comment]
It is fairly common for web apps to employ the same validation logic on the client and on the server. It may entail a lot of work, especially if the client's and server's runtimes are different (i.e. JavaScript and Java), but throwing these simple errors early would definitely enhance the usability of LP-ETL.

**Comment by jindrichmynarz** [comment]
I think this issue is now resolved. For a broader discussion on client-side validation I created #388.
