### ISSUE TITLE
Two buttons in pipeline detail have the same color

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#387]
![image](https://cloud.githubusercontent.com/assets/718827/26398369/9707d7fa-4079-11e7-912f-a35c967fedd1.png)

Discard should be gray

**Comment by skodapetr** [comment]
Gray button indicates, that the button is disabled. In current state both buttons are active.
Also https://material.io/guidelines/components/dialogs.html#dialogs-behavior use same color for both buttons.
