### ISSUE TITLE
Large front-end assets for Angular may cause timeout

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#395]
The pipeline view issues 66 HTTP requests transferring 3 MB worth of front-end assets. The largest of these are the `angular.js` (1.1 MB) and `angular-material.css` (525 kB). These assets may fail to load in time, causing a timeout error:

```
Uncaught Error: Load timeout for modules: angular,angular-route,angular-resource,angular-messages,angular-cookies,angular-material,angular-file-upload,angular-ui-notification,angular-animate,angular-aria,jointjs
http://requirejs.org/docs/errors.html#timeout
    at makeError (require.js:165)
    at checkLoaded (require.js:693)
    at require.js:714
```

In case such error occurs, the pipeline view remains blank without informing the users about the error. There are several things that can be done about this. For example:

* Reduce the size of the front-end assets. Currently, the assets are not minified.
* Reduce the number of HTTP requests. Concatenate the JS and CSS files in the JavaScript build pipeline.
* Increase the load timeout or drop it completely.
* Show a loading indicator before the assets are loaded, so that users know what's happening. I experienced load times 1-2 minutes long, so it would be useful to know if the app is loading or if it is dead.
* Catch the timeout error and display its explanation to the user. Include hints what can be done by the users about the error (e.g., reloading the app).

The issue was originally discussed as part of openbudgets/pipeline-fragments#24.

**Comment by jakubklimek** [comment]
I think this is solved by webpack. We do not experience any issues with this.
