### ISSUE TITLE
Missing assets for etl.linkedpipes.com

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#397]
The LP-ETL web is currently missing some assets:

<img width="1280" alt="screen shot 2017-06-01 at 17 05 09" src="https://cloud.githubusercontent.com/assets/198642/26686188/83ba1ebe-46ec-11e7-9397-5ea662048782.png">

I tried reloading the page, emptying its cache, and loading in a different browser, but the errors persist.

**Comment by jakubklimek** [comment]
This was connected to the GitHub problems yesterday - after the last commit, the pages were not generated correctly.
