### ISSUE TITLE
List of DPUs should have an order

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#4]
Currently, it seems that there is no order in the list of available DPUs. For example, see this:

<img width="189" alt="screen shot 2016-01-26 at 11 37 50" src="https://cloud.githubusercontent.com/assets/198642/12578468/5e539be0-c421-11e5-8e9f-a47f0dea0065.png">

The list should be sorted in some order, e.g., alphabetically, and DPUs could be partitioned by their type (extractors, transformers, loaders).

**Comment by jakubklimek** [comment]
Fixed. Now, while dragging and edge first instead of connecting existing DPUs, the DPU list is 
- recommending DPUs sorted by the probability of their appearance in other pipelines .
- filtering DPUs only to those that are compatible
- allowing you to search by DPU tags (try zip, bzip, turtle)
