### ISSUE TITLE
Support HDT input and output

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#404]
Support [HDT ](https://github.com/rdfhdt/hdt-java) input and output, which is currently not supported by RDF4j (https://github.com/eclipse/rdf4j/issues/232). 

These will be separate transformers encapsulating the library.

**Comment by skodapetr** [comment]
What should support HDP input/output?
Should there be HdtToRdf and RdfToHdt component?

**Comment by jakubklimek** [comment]
Yes
