### ISSUE TITLE
Stream compression: missing placeholder for the default compression method

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#407]
The [Stream compression](http://etl.linkedpipes.com/components/t-streamcompression) component is missing a placeholder for the default compression method. By default, the *Format* parameter is empty, which provides no indication what compression format will be used by default. The default compression format should be selected by default.

Tested using the develop version e075246dce28cfab21b0535b7d0691515b659339.

**Comment by jindrichmynarz** [comment]
Still no placeholder in ea55b8f69c5cd5464927f735ad56cc21fa5d6cff.

**Comment by skodapetr** [comment]
Do you test with new or existing component?

**Comment by jindrichmynarz** [comment]
Do you mean new or existing instance of the component?

**Comment by skodapetr** [comment]
Yes

**Comment by jakubklimek** [comment]
Fixed
