### ISSUE TITLE
Virtuoso loader: "Remote directory with ..." label truncated

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#409]
The label of the "Remote directory with ..." parameter of the Virtuoso loader ends up truncated as it is too long to fit in the interface:

<img width="187" alt="screen shot 2017-06-13 at 17 28 32" src="https://user-images.githubusercontent.com/198642/27090591-e7dfc9fa-505d-11e7-85d7-e6aba109dc17.png">

There's no way to reveal the truncated part of the label. This can be resolved in several ways:

* The label can be shortened.
* The allocated screen space for the label can be enlarged.
* Allow the user to reveal the truncated part of the label (e.g., at least on hover via the `title` attribute)

The first option is probably the best.

Tested using the develop version e075246dce28cfab21b0535b7d0691515b659339.

**Comment by jindrichmynarz** [comment]
The issue is still present in ea55b8f69c5cd5464927f735ad56cc21fa5d6cff. How was this issue supposed to be fixed?

**Comment by jakubklimek** [comment]
Seems to me to be fixed. Did you refresh properly?

**Comment by jindrichmynarz** [comment]
Yes. Even after hard refresh I still see this:

<img width="187" alt="screen shot 2017-06-19 at 21 00 04" src="https://user-images.githubusercontent.com/198642/27301081-572658b4-5532-11e7-9ca3-b5510235e6d1.png">

It looks the same both in Chrome 58.0.3029.110 and Firefox 53.0.3 on OS X.

**Comment by jakubklimek** [comment]
And demo.etl.linkedpipes.com?

**Comment by jindrichmynarz** [comment]
The demo instance displays the label fine:

<img width="285" alt="screen shot 2017-06-19 at 22 09 47" src="https://user-images.githubusercontent.com/198642/27303758-16c8f22c-553c-11e7-906c-59b2c65114ab.png">

**Comment by jakubklimek** [comment]
Then I think you did not update properly...

**Comment by jakubklimek** [comment]
Closing as this is fixed in all deployed instances

**Comment by jindrichmynarz** [comment]
Well, in fcffc8a2bb82cfc748f5dada5fea4403c8662586 it is fixed.
