### ISSUE TITLE
Filters on pipelines unapplied when a filtered pipeline is deleted

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#412]
When you filter pipelines via label or tag in the pipelines view and you delete a pipeline from the filtered selection, the selection is lost and all pipelines are shown even though the filter is still filled in. In such case, if you want to return to the filtered view, you have to delete the filter and enter the same filter in.

If possible, the filtered view should be maintained even after deleting its member. Alternatively, to make the UI at least consistent, if the filtered view needs to be reverted to all pipelines, then also the filters should be deleted.

Tested using the develop version e075246dce28cfab21b0535b7d0691515b659339.

**Comment by skodapetr** [comment]
As of now this should be ok. It was fixed as a part of infinity scroll implementation in the pipeline list.
