### ISSUE TITLE
Feature request: RDF difference component

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#419]
RDF difference component would have two input RDF data units `A` and `B` and produce an RDF data unit `C = A \ B` (i.e. the triples in `A` but not in `B`).

This would be useful in case you want to delete a part of data that you already separated via a SPARQL CONSTRUCT query. In such case, you would pipe the part and the original whole to the RDF difference component and have it removed.

Set difference is usually implemented directly by RDF APIs, such as in [Apache Jena](https://jena.apache.org/documentation/javadoc/jena/org/apache/jena/rdf/model/Model.html#difference-org.apache.jena.rdf.model.Model-).

**Comment by skodapetr** [comment]
Sesame also have similar [functionality](http://docs.rdf4j.org/javadoc/latest/org/eclipse/rdf4j/repository/util/RepositoryUtil.html). However as the documentation states:  ```NOTE: this algorithm is currently broken; it doesn't actually map blank nodes between the two models.``` Also this works on whole repository while we need to be restricted to a single graph (content of data unit).

The implemented component use Map and equals to perform the difference operation. Blank nodes are NOT supported. 

We may change the implementation based on the use-cases, especially size of the data.

**Comment by jindrichmynarz** [comment]
Works as expected in 138e91f3c4ac0e3472957a0cc571f4e254638bb7. Tests are [here](https://github.com/linkedpipes/etl-tests/tree/master/pipelines/components/t-rdfDifference).
