### ISSUE TITLE
Enhancement: Enable setting timeouts in HTTP GET list 

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#423]
Some servers have a long timeout, such as half an hour. In cases when we don't want to wait that long it would be useful to be able to configure an explicit timeout in the HTTP GET list component. This could be exposed via an additional RDF property in the component's configuration.

**Comment by skodapetr** [comment]
For simplicity we use single value for a connection timeout and read timeout - is that ok?

**Comment by jindrichmynarz** [comment]
I think it would be better to only consider the connection time. Once a request starts transferring data, it may legitimately take a while if the requested resources is large.

**Comment by jindrichmynarz** [comment]
Moreover, the timeout parameter in the configuration should specify what unit of time it has (milliseconds?).

**Comment by skodapetr** [comment]
@jindrichmynarz Can you please re-test?

**Comment by jindrichmynarz** [comment]
I've set a timeout of 5000 ms and the pipeline with 314 downloads keeps running even after 2 hours. I'll try to setup a more minimal example to test this.

**Comment by jindrichmynarz** [comment]
The timeout parameter doesn't seem to be respected. See this [example pipeline](https://github.com/linkedpipes/etl/files/1124695/Test.HTTP.GET.list-.timeout.jsonld.zip). It requests the URL <http://httpbin.org/delay/10> that delays 10 seconds before responding. The timeout is set to 5000 ms. The file is downloaded even though the delay exceeds the timeout.

**Comment by skodapetr** [comment]
Well probably the connection is established (connection timeout), but it takes 10 seconds before the data are send (read timeout).  So should the read timeout be included after all?

As with the read timeout I got:
```
2017-07-05 15:45:04,462 [pool-2-thread-1] ERROR c.l.p.e.h.UriDownloader - Can't read response code for file: D:\Projects\linkedpipes-data\working\data\a16bce7f-95ad-4f06-ac40-3cb781a31b33\working\temp-12\delay.json
java.net.SocketTimeoutException: Read timed out
```
after 5 seconds.

**Comment by jindrichmynarz** [comment]
The [documentation of httpbin](https://httpbin.org) say that "/delay/:n Delays responding for min(n, 10) seconds". I understand that delaying response means delaying start of transfer.

You can test this using `curl`, for instance:

```sh
curl -s --output /dev/null -w "%{time_starttransfer}" https://httpbin.org/delay/5
```

This output values greater than 5.

**Comment by skodapetr** [comment]
Yes and ```curl -s --output null -w "%{time_connect}" https://httpbin.org/delay/5`` return 0.18 .. the connection timeout is set to 5 seconds, but the connection is established in less then a second, so this is ok. 


But after the connection is established it takes 5 seconds before the data transfer starts ie. before any data are read from the connection. That is what the read timeout is for. If the read timeout is set to 5 seconds and data transfer starts in 10 seconds then the operation time outs. If the read timeout is not set, then the connection remains open and the applications is waiting. 

But you wrote that we should consider only a connection time, which I think on it's own can not solve this issue.

**Comment by jindrichmynarz** [comment]
I'm sorry, I misunderstood what you meant by read time. I thought you mean the transfer time. If the read time is the time that elapses before the transfer starts, then it should be included in the timeout. The semantics of the timeout should be documented to prevent misunderstandings such as this one.

**Comment by skodapetr** [comment]
@jindrichmynarz Can you please re-test?

**Comment by jindrichmynarz** [comment]
Time out works as expected in 1b6ef835dd2bff425b9caa77860c13bf61fd199f.
