### ISSUE TITLE
Missing links to component documentation

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#431]
Two components are missing links to their documentation from the [components page](http://etl.linkedpipes.com/components). These are:

* SPARQL endpoint construct scrollable cursor
* SPARQL endpoint select scrollable cursor

Their documentation is already available, but it is not linked.

**Comment by jindrichmynarz** [comment]
The links to these components are still missing, even after hard refresh and test in different browsers. Perhaps the build of gh-pages is failing again?

**Comment by jakubklimek** [comment]
Not sure what you mean. I see:
![image](https://user-images.githubusercontent.com/718827/29462217-e8d03674-842e-11e7-8113-4bec57787705.png)

**Comment by jindrichmynarz** [comment]
Ah, then perhaps Github pages uses CDNs that are not updated synchronously. I tested the page different browsers, cleared cache, and still I don't see the links:

<img width="925" alt="screen shot 2017-08-18 at 16 14 13" src="https://user-images.githubusercontent.com/198642/29462693-84cff2f2-8430-11e7-80db-5aba3f5bff14.png">

**Comment by jakubklimek** [comment]
Well... these are there for a long time, so this is not a caching isssue.

**Comment by jindrichmynarz** [comment]
What do you mean that "these are there for a long time"? This issue was just resolved, right?

**Comment by jakubklimek** [comment]
Because I just got to it, but these components are there since 8 months ago

**Comment by jindrichmynarz** [comment]
The problem is not in missing component descriptions, but in missing links. As you can see, the links are still missing on my screenshot. However, as we discovered, this is probably a CDN-related issue that can be fixed only by time invalidating the cached content.

**Comment by jakubklimek** [comment]
OK, now I see... Definitely not a CDN related issue. Seems like an Apple/Windows issue, each rendering materializecss fonts and google icons differently....

**Comment by jindrichmynarz** [comment]
Ah, you're right. The links are hidden, because the content overflows its containers. This is a CSS issue.

**Comment by jindrichmynarz** [comment]
The links are hidden when the screen width is from 993px to 1062px. Probably a problem of the responsive CSS classes. This is problematic because that range of screen width is common for laptop users, such as those with 13" displays.

**Comment by jakubklimek** [comment]
How about now?

**Comment by jindrichmynarz** [comment]
That is better. Only the component description is hidden, which is probably fine.

<img width="915" alt="screen shot 2017-08-18 at 17 32 42" src="https://user-images.githubusercontent.com/198642/29465944-4fbe9f68-843b-11e7-98c5-c4dc03789770.png">
