### ISSUE TITLE
Confusing label for invalidation of debug data

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#433]
The control for invalidating debug data is labelled "Enable/disable mapping":

<img width="265" alt="screen shot 2017-07-11 at 16 59 55" src="https://user-images.githubusercontent.com/198642/28075007-71e3fbaa-665a-11e7-897f-6fc32083b2f8.png">

How is it related to mappings? According to the [documentation](http://etl.linkedpipes.com/documentation), this control *"invalidates the old and fresh components and all components following it in the execution order."* The label could be something like "Discard debug data" or "Invalidate debug data".

Tested using the develop version 3ed0e220b0a9c10b561242ae5abc872b915fbb2a.

**Comment by jakubklimek** [comment]
I vote for "Invalidate debug data"

**Comment by skodapetr** [comment]
@jakubklimek The label is fixed, however the action is not. If the mapping is disabled it enable it and vice versa, so the label should reflect this somehow.

**Comment by jakubklimek** [comment]
@skodapetr Lets make it "Toggle data invalidation"

**Comment by jindrichmynarz** [comment]
How would the user know what is the current state if the label is "Toggle data invalidation"? Either the label, the button, or something else must change to indicate the current state.

**Comment by jakubklimek** [comment]
The component border changes from green (valid) to none (invalid) and back.

**Comment by jindrichmynarz** [comment]
OK. I'm still unsure whether the mapping of the validity to colours is apparent, especially to new users.

**Comment by jakubklimek** [comment]
Well, this is an advanced feature anyway, and it is documented, I think it is fine.
