### ISSUE TITLE
Execution cannot save the pipeline

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#435]
In some cases, the execution cannot save the executed pipeline. Instead, it saves an HTML error:

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /api/v1/pipelines/unpack. Reason:
<pre>    org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.14.v20161028</a><hr/>
</body>
</html>
```

Unlike in #393 the executed pipeline is valid (see [here](https://github.com/linkedpipes/etl/files/1144548/csu_code_list_extraction.jsonld.zip)). Since the pipeline is syntactically correct, is it incorrect in other ways that cause the NPE in LP-ETL?

Tested using the develop version b821d22aa6fadc9e3bec3f928de29c26bd77fb99.

**Comment by skodapetr** [comment]
What do you mean by "execution" ?

**Comment by jindrichmynarz** [comment]
When you click "Execute", this happens.

**Comment by skodapetr** [comment]
Can you take a look into the storage log? There should be rest of the exception. 
Do you use debug from? 

I downloaded the pipeline, import it and execute it - it fails on Virtuoso (nothing to load).

**Comment by jindrichmynarz** [comment]
It seems that the issue is not with the pipeline, but with the data from prior executions. When I reimport the pipeline and run it completely, the execution is started without an error.

(The Virtuoso error is a temporary issue: the data the pipeline processes is currently loaded, so the initial SPARQL endpoint extractor retrieves empty data, so the pipeline has nothing to do.)

**Comment by jakubklimek** [comment]
This could be due to various errors that might be fixed since. I suggest reopening when this happens again.
