### ISSUE TITLE
CoachDB: typo in the name

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#439]
In the case of the [CoachDB](https://github.com/linkedpipes/etl/tree/develop/plugins/l-coachDb) component, there is a typo in the name, which should be [CouchDB](http://couchdb.apache.org).

**Comment by skodapetr** [comment]
Just a note the rename breaks all pipelines that use this component. These pipelines need to be manually edited - replace coachDb to couchDb.

**Comment by jindrichmynarz** [comment]
I checked out 4b58403d29bb9b631eb9329d2a1eeca3d5ae8d2f, `mvn clean install`, deleted the `jar-l-coachDb-0.0.0.jar` directory from `{storage.directory}/templates`, started LP-ETL, hard-refreshed the front-end, and Coach-DB component still appears (along with the Couch-DB component). What have I forgot to clean?

**Comment by skodapetr** [comment]
Could you please check the jar (deploy/jar/core) for the old coachDb component?

**Comment by jindrichmynarz** [comment]
Even after deleting the JAR from `deploy/jars/core` both CoachDB and CouchDB components are available (again: tested with hard refresh, in multiple browsers). There must be another location that caches the old component.
