### ISSUE TITLE
Enhancement: log queries executed by the SPARQL CONSTRUCT to file list component

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#440]
The SPARQL CONSTRUCT to file list component could log the queries it executes (along with timestamps), so that it is easier to diagnose what queries cause performance problems.

Motivating example: I have a pipeline that uses the component with hundreds of queries. The pipeline execution gets stuck on this component. However, when I try to run a few of the generated queries separately, they run fine. Since there are hundreds of queries, I'd have to run each query individually to find out its performance characteristics. Having the SPARQL CONSTRUCT to file list component log the queries it executes would help me identify, on which it gets stuck.

**Comment by jindrichmynarz** [comment]
No logs appear in a75fb28f7ad8645d4beb9d1d56baf37472640ee5.

**Comment by jindrichmynarz** [comment]
This sort of beats the purpose of being able to diagnose a problematic query that takes long or fails to execute.

**Comment by skodapetr** [comment]
@jindrichmynarz Can you share the pipeline?

**Comment by jindrichmynarz** [comment]
The pipeline has large input, I'll have to make a smaller one.

**Comment by jindrichmynarz** [comment]
The logs first show `2017-08-08 14:30:40,611 [SPARQL construct to file list] INFO  c.l.e.e.a.v.s.DefaultProgressReport - Progress report (170) ... `, where 170 means the last query, and only after that the first query log appears (`2017-08-08 14:30:40,613 [SPARQL construct to file list] INFO  c.l.p.t.s.c.SparqlConstructToFileList - Executing query:`).

**Comment by jindrichmynarz** [comment]
Fixed in b2ef9323a336a8c6728975f7fabd7b1f3638b2ba.
