### ISSUE TITLE
Component execution detail doesn't support non-ASCII characters

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#442]
Component execution detail doesn't support non-ASCII characters. When you go to the execution view and click a component to see its status, if the component failed and its error message contains non-ASCII characters, they will be shown incorrectly:

```
RepositoryException : Virtuoso 37000 Error SP030: SPARQL compiler, line 2: syntax error at 'SELECT' before '?katastralniUzemi' SPARQL query: PREFIX ruian: <https://ruian.linked.opendata.cz/slovnÃ­k/> SELECT SELECT ?katastralniUzemi WHERE { {SELECT DISTINCT ?katastralniUzemi WHERE { GRAPH <https://ruian.linked.opendata.cz/zdroj/datovÃ¡-sada/rÃºian> { ?katastralniUzemi a ruian:KatastrÃ¡lnÃ­ÃzemÃ­ . } } ORDER BY ?katastralniUzemi } } LIMIT 1000 OFFSET 0
```

When you view the logs in the executor monitor, they reveal that the non-ASCII characters are already mangled there.

Tested using the develop version a8e599812f558baf63c86995d49fc22b78ccedeb.

**Comment by jakubklimek** [comment]
Try running the query directly in Virtuoso. You should get the same string => bug in Virtuoso, not LP-ETL.

**Comment by jindrichmynarz** [comment]
Yes, that is not a problem. The problem is only the printing of the non-ASCII characters. For example, if I want to copy this generated query from the log and run it in Virtuoso, I have to manually correct the non-ASCII characters.

**Comment by jakubklimek** [comment]
Sure, but there is nothing to be done about this when this is how Virtuoso sends the error. You can raise an issue there.

**Comment by jindrichmynarz** [comment]
Ah, now I get this.

**Comment by jindrichmynarz** [comment]
Actually, Virtuoso sends the non-ASCII characters correctly, so this is an issue of the encoding in the LP-ETL's logger.

You may have this invalid query:

```sparql
# properties.rq file
SELECT SELECT DISTINCT ?p
WHERE {
  GRAPH <https://ruian.linked.opendata.cz/zdroj/datová-sada/rúian> {
    [] ?p [] .
  }
}
```

When you execute it using curl:

```bash
curl --data-urlencode query@properties.rq https://ruian.linked.opendata.cz/sparql
```

the response is correctly encoded:

```
Virtuoso 37000 Error SP030: SPARQL compiler, line 1: syntax error at 'SELECT' before 'DISTINCT'

SPARQL query:
SELECT SELECT DISTINCT ?p
WHERE {
  GRAPH <https://ruian.linked.opendata.cz/zdroj/datová-sada/rúian> {
    [] ?p [] .
  }
}
```

**Comment by jakubklimek** [comment]
however, when I do the [request ](https://ruian.linked.opendata.cz/sparql?default-graph-uri=&query=SELECT+SELECT+DISTINCT+%3Fp%0D%0AWHERE+%7B%0D%0A++GRAPH+https%3A%2F%2Fruian.linked.opendata.cz%2Fzdroj%2Fdatov%C3%A1-sada%2Fr%C3%BAian+%7B%0D%0A++++%5B%5D+%3Fp+%5B%5D+.%0D%0A++%7D%0D%0A%7D&format=text%2Fhtml&timeout=0&debug=on )in Chrome or Firefox, the result is wrong. Still seems to me like Virtuoso issue.

**Comment by jindrichmynarz** [comment]
Yes, it is even more complicated. Here's an attempt at analysis.

Virtuoso sends a `Content-Type` without explicitly specifying the charset parameter (e.g., `Content-Type text/plain` instead of `Content-Type text/plain; charset=UTF-8`). [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt) says:

> When no explicit charset parameter is provided by the sender, media subtypes of the "text" type are defined to have a default charset value of "ISO-8859-1" when received via HTTP. Data in character sets other than "ISO-8859-1" or its subsets MUST be labeled with an appropriate charset value.

However, Virtuoso's response (at least in version 7) is encoded in UTF-8. As explained [here](https://stackoverflow.com/a/2349239/385505), most browsers ignore the charset parameter and detect character encoding themselves. Apparently, curl does the same, since it interprets UTF-8 as UTF-8 even though, according to the RFC 2616, it should default to ISO-8859-1. In that light, the LP-ETL's logger does what is correct according to the RFC 2616. However, since this part of the RFC 2616 is so widely ignored for practical reasons, perhaps the LP-ETL's logger can do the same. I would consider that an enhancement, not a bug.

**Comment by skodapetr** [comment]
Virtuoso returns stream in ```UTF-8```, but ```Content-Type text/plain``` as a content type. Rdf4j use 
SPARQLProtocolSession 1197 : ```EntityUtils.toString(response.getEntity())``` with no parameter to ```toString``` method to get the error string (we get back to this later).

The ```EntityUtils``` is a class in ```httpcore-4.4.4``` jar file. Here the ```toString``` tries to:
* detect encoding from the content-type - fail as there is none
* use default charset and fail as no default was given (that was the missing second parameter ```toString``` method).
* use hard coded default Consts.ISO_8859_1  
so the error stream is decoded as ISO_8859_1.

The only option would be get bytes in the ```ISO_8859_1``` encoding and create new string in ```UTF-8``` like this:
```
new String(ex.getMessage().getBytes("ISO_8859_1"), Charset.forName("UTF-8"))
```
however this would break any other encoding,

All the code is in the Rdf4j or httpcore, so in order to fix this we would need to re-implement part of the third party code. As @jindrichmynarz  mentioned this is according to RFC, that is why I see almost no chance that any of the third party libraries would accept such change to their code base.
