### ISSUE TITLE
SPARQL endpoint: MIME not working on Virtuoso 6

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#446]
The MIME type parameter in the SPARQL endpoint chunked does not have an effect. As documented in #445, it is unclear what effect it should have. Nevertheless, neither of the suspected effects appears. Notwithstanding the MIME type specified, the component always obtains Turtle and attempts to parse it as N-Triples (same error as in #441): `RDFParseException : Expected '<' or '_', found: @ [line 1]`

Tested using the develop version f52bd17c9f3ae6fb2ecf5e666af204f393f6fb5a.

**Comment by jindrichmynarz** [comment]
The component works without the MIME type specified on newer Virtuoso 7 endpoints, however fails of older Virtuoso 6 endpoints. It seems as if the value of this parameter is simply ignored.

**Comment by skodapetr** [comment]
@jindrichmynarz Which MIME types and endpoints have you tried?

**Comment by jindrichmynarz** [comment]
I have tried the <https://csu.opendata.cz/sparql/> Virtuoso 6 endpoint with various MIME types (`text/turtle`, `text/plain`, `application/rdf+xml`...).

**Comment by jakubklimek** [comment]
Have you tried the request with the mime type outside of LP-ETL? Maybe it is a Virtuoso 6 issue.

**Comment by jindrichmynarz** [comment]
Yes. For example, this query:

```sparql
# query.rq file
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?concept skos:prefLabel ?prefLabel .
}
WHERE {
  {
    SELECT ?concept ?prefLabel
    WHERE {
      ?concept skos:prefLabel ?prefLabel .
    }
    LIMIT 1
  }
}
```

Execute it with curl, ask for `text/plain`:

```bash
curl -H "Accept:text/plain" --data-urlencode "query@query.rq" https://csu.opendata.cz/sparql/
```

Get this:

```turtle
<https://csu.opendata.cz/zdroj/\u0159\u00EDzen\u00FD-slovn\u00EDk/44/pojem/500054>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Praha 1"@cs .
```

This is not a Virtuoso issue. The issue is that the component either ignores the specified MIME type or always asks for Turtle (the default MIME type in Virtuoso for CONSTRUCT) and then the component attempts to parse the Turtle as N-Triples.

**Comment by jakubklimek** [comment]
This has been either fixed in related issues, or will not be fixed as it is safe to say that Virtuoso 6 does not have to be supported anymore.
