### ISSUE TITLE
"Debug to" can't be continued

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#447]
When you execute a part of a pipeline using "Debug to this component", a subsequent execution of the pipeline will fail with an error like this on the component, to which the debug execution was run:

```
Cause: 
Can't reference content.

Root cause: 
FileNotFoundException : /Users/mynarzjindrich/Dev/linkedpipes/etl-deploy/lp/etl/working/data/5df5961b-4b0a-4252-bc9e-4573b39e064d/working/dataunit-005-7/data/data.json (No such file or directory)
```

A more specific error message should be raised (e.g., "Cannot continue in 'Debug to this component' executions") or the intermediate data should be usable as in case of normal executions.

Tested using the develop version f52bd17c9f3ae6fb2ecf5e666af204f393f6fb5a.

**Comment by skodapetr** [comment]
@jindrichmynarz Could you please also share a pipeline and which component you run debug to?

**Comment by jindrichmynarz** [comment]
I tried to produce a minimal failing example and discovered few clarifications.

"Debug to" execution obsoletes data from previous "Debug to" executions. Any subsequent execution will not be able to reuse data from the first "Debug to" execution. So this problem appears only after at least two "Debug to" executions.

Let's try [this test pipeline](https://github.com/linkedpipes/etl/files/1165056/Test.continue.from.-Debug.to-.jsonld.zip). First, run "Debug to" Files to RDF single graph. Then, run "Debug to" SPARQL endpoint. Finally, run the complete pipeline. This will fail, since the intermediate data of the Files to RDF single graph will not be found (with a similar error to the one above).

**Comment by jindrichmynarz** [comment]
Replicating the above-described scenario in 38e09fb30bd3cf08b802c1ec29196091cceddeaa does not produce an error. I consider this to be fixed.
