### ISSUE TITLE
Enhancement: provide specific User-Agent header

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#449]
When LP-ETL requests URLs, it sends the generic `User-Agent` header with the value `Java/1.8.0_131`. Some services require that this header clearly identifies the requesting application, so requests with a generic header may be rejected. LP-ETL can explicitly identify itself when making HTTP requests by using a specific `User-Agent` header. This relates to the HTTP GET and HTTP GET list components.

Tested using the develop version 4b58403d29bb9b631eb9329d2a1eeca3d5ae8d2f.

**Comment by jindrichmynarz** [comment]
This also turns out to be problematic in context of the OpenBudgets.eu, since Cloudflare bans requests with a generic `User-Agent` (openbudgets/platform#54).

**Comment by jakubklimek** [comment]
@skodapetr This needs to be addressed in each web accessing component separately, right?

**Comment by skodapetr** [comment]
@jakubklimek @jindrichmynarz mentioned only HttpGetFile and HttpGetFileList components.

**Comment by jakubklimek** [comment]
I think this should be addressed at least in all extractors to be consistent. Which means defining the user agent string somewhere in LP-ETL to be reused?

**Comment by skodapetr** [comment]
For e-httpGetFile there is new options. For e-httpGetFiles it should be enough to specify "user-agent" as a header (in configuration).

As a next step we can "define" the configuration string, however there is a question where and how it should be defined. 
Such string will not be part of a pipeline definition, thus in this case if on one instance the user-agent global is set a pipeline will work. Once the pipeline is exported to another instance, where the string is not set, the pipeline will fail.

**Comment by jindrichmynarz** [comment]
Do we have a use case for making the User-Agent configurable?

**Comment by jakubklimek** [comment]
Hmm.. It could happen that a specific User-Agent string needs to be used to download something. So it is probably better to have it as (advanced) configuration.

**Comment by jindrichmynarz** [comment]
Well, I think that needing a configurable User-Agent string is a fairly remote possibility, since it took a long time to encounter this issue, because most servers were fine with LP-ETL providing the default Java User-Agent. If making it configurable incurs undue effort, then I'd say it's not worth making it configurable.
