### ISSUE TITLE
Strict policy on empty language tags

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#455]
When RDF data contains a string with the datatype `rdf:langString` (see [language tags in RDF 1.1](https://www.w3.org/TR/rdf11-concepts/#dfn-language-tagged-string)), parsing the data fails with `IllegalArgumentException : datatype rdf:langString requires a language tag` (see [source code](https://github.com/eclipse/rdf4j/blob/master/core/model/src/main/java/org/eclipse/rdf4j/model/impl/SimpleLiteral.java#L99)). I find this to be a strict policy for several reasons:

* In most RDF syntaxes, there is no way to provide language tag when a datatype is specified. It is therefore impossible to satisfy what the exception requires.
* DBpedia features a lot of literals with `rdf:langString` datatype and empty language tag. Currently, it is impossible to use such data.
* Both LibRaptor and Jena consider it to be valid.

Is it possible that LP-ETL enables a more tolerant parsing that simply treats literals with `rdf:langString` as plain literals?

A pipeline to reproduce the issue is [here](https://github.com/linkedpipes/etl/files/1169905/Test.empty.language.tag.with.langString.jsonld.zip).

Tested using the develop version 622aca9c523d66f65d381b4fa4e3f08b7f0d9a90.

**Comment by jakubklimek** [comment]
This is a property of RDF4J and I see nothing wrong with it. In RDF 1.1 syntaxes when you provide a language tag, the literal is automatically typed rdf:langString and typing a literal rdf:langString is indeed invalid. DBpedia runs on Virtuoso, which allows a lot of invalid things like spaces in URIs. Nevertheless, you can raise an issue with RDF4J.

**Comment by jindrichmynarz** [comment]
So RDF4J does not have a more tolerant parsing mode?

**Comment by jakubklimek** [comment]
I am not sure, but I would say no. @skodapetr ?

**Comment by fellahst** [comment]
Is this issue been solved in the latest version? Is there any parsing property that can be set to allow to handle this use case. Some solution was proposed to replace the valueFactory to work around this problem.
I would appreciate if you can give an update on this matter. Thank you

**Comment by jakubklimek** [comment]
In https://github.com/linkedpipes/etl/issues/591 the option was renamed so that it is more clear what it does:
![image](https://user-images.githubusercontent.com/718827/44573424-e4bf5200-a786-11e8-8d23-8898593062c4.png)
