### ISSUE TITLE
HTTP GET list downloads only one URL

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#456]
In this [simplified pipeline](https://github.com/linkedpipes/etl/files/1169959/HTTP.GET.list-.test.empty.results.jsonld.zip) there are 39 URLs to download, yet the HTTP GET list component downloads only one of them. No errors or unusual logs are reported. *Skip on error* is turned off, so the pipeline should fail if it encounters an invalid response. *Force to follow redirects* is turned on to follow HTTP 301 TLS redirects. Perhaps when such redirect is followed the remaining URLs are ignored?

Tested using the develop version 622aca9c523d66f65d381b4fa4e3f08b7f0d9a90.

**Comment by skodapetr** [comment]
There is also another issue with progress report (although download fails after first item, the last message report full status, ie. all items downloaded), but for that we should created another issue.

**Comment by jindrichmynarz** [comment]
An error is thrown in b2a7a28b1b811ec66f2ebef40eb55560b95e1052.

However, there are other problems, as you indicate. We'll deal with them in other issues.
