### ISSUE TITLE
Autocomplete doesn't work with Enter

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#457]
Autocomplete doesn't work with pressing Enter. When an autocomplete is presented, such as in the following case, pressing Enter closes it, but its suggestion is not applied.

<img width="234" alt="screen shot 2017-07-24 at 16 06 36" src="https://user-images.githubusercontent.com/198642/28527244-3da4161a-708a-11e7-996e-12cb48b75d07.png">

Instead, the current text "tuto" is accepted as the autocompleted item.

Clicking on the autocomplete's suggestion works as expected. It should work the same with Enter or Enter should not work at all; i.e. not close the suggestions.

Tested using the develop version 622aca9c523d66f65d381b4fa4e3f08b7f0d9a90.

**Comment by skodapetr** [comment]
It seems to me, that it works the same way as [material.angularjs.org](https://material.angularjs.org/latest/demo/autocomplete)  You can use arrow up/down to select items from the suggestion list.

If we do not restrict the value to only "suggested items" then it seems to me ok to enable "tuto" as an input.

**Comment by jindrichmynarz** [comment]
You're right. I missed this. The autocomplete works correctly with Enter.
