### ISSUE TITLE
Show last N lines from the logfile

### ISSUE THREAD

**Issue by martinnec** [linkedpipes/etl#459]
On a pipeline execution, there should be an option to "See last N lines from logs" in addition to the option "See logs".

Rationale: Sometimes, logs are long (GBs) and a developer is interested only in the reason why the pipeline has fallen down.

**Comment by jakubklimek** [comment]
The only problem here is that typically, the reason for pipeline failure is not at the end of the log, but near it. So the N needs to be configurable.
It could be an API call with N as a parameter, and in the GUI, N would be given in a dialog.

**Comment by skodapetr** [comment]
We can add another log file with only ERROR level logs.

**Comment by jakubklimek** [comment]
I would start with showing tail with N (default 100) in the GUI and then we could see...
