### ISSUE TITLE
HTTP Request component removed?

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#464]
While the HTTP Request component is still available both in my LP-ETL instance and the demo instance, I cannot find its source code nor its documentation. Has it been removed?

**Comment by skodapetr** [comment]
Source code: https://github.com/linkedpipes/etl/tree/develop/plugins/x-httpRequest

**Comment by jindrichmynarz** [comment]
OK, so this is only an issue of missing documentation.

**Comment by jakubklimek** [comment]
Documentation is already present.
