### ISSUE TITLE
String mapping in Tabular ODCS removes preceding 0

### ISSUE THREAD

**Issue by fathoni** [linkedpipes/etl#466]
String mapping in Tabular ODCS Mapping removes preceding "0" even when the column type declared as a string. For example, in this [execution](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2Fcreated-1501857454123&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2Fbaff9ce6-5ee8-4760-8eaa-0c4cd7a900f3), within the ODCS mapping, "Produkt" is mapped to http://data.openbudgets.eu/ontology/dsd/bonn-budget/dimension/functionalClassification with type declared as string. However, upon debugging, the resulting mapping removes preceding "0"s.

**Comment by skodapetr** [comment]
The "string" type is used for output. Input is still a double, the actual value is indeed 100, the leading 0 is added by formatting. The cell format has been mostly ignored so far.

We added new option "Format numbers with DataFormatter" - which use DataFormatter to format the cell value. In this case the output is "0100" as expected. Applied to other files it may however give unwanted format. For this reason we make it optional (to preserve backward compatibility). We deployed the update to demo instance. Please check take a look at this [execution](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2Fcreated-1501857454123&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2Faa095bea-2d78-4831-99c3-1cd289dbf049), if the output is ok. The update is available in master as well as in develop branch.

**Comment by fathoni** [comment]
Thank you, the component runs as expected now. One minor issue though, the UI within the tabular component state the option as "DateFormatter" instead of "DataFormatter", perhaps it can be updated as "DataFormatter" instead to avoid misunderstanding?
