### ISSUE TITLE
http Get: User agent not working properly with templates

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#471]
As can be seen in https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2Fcreated-1503041825691, the User agent setting is visible even though it is "overwritten" from the template.

**Comment by skodapetr** [comment]
This fix does not apply retrospectively, ie. it does not fix existing templates.

**Comment by jakubklimek** [comment]
Still not working, even for new templates in 44215bf53f351436a6187d44f9998fe13eeca86e
