### ISSUE TITLE
Tabular: does it support TSV?

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#480]
The Tabular component doesn't seem to support [TSV](https://en.wikipedia.org/wiki/Tab-separated_values), because tabulator is not allowed as a value of the *Delimiter* configuration option. If you enter tabulator into the option, it remains marked as invalid, and upon saving the configuration, it is removed.

Tested using the develop version 9cbc090c1c7388534eb6e2f536e5f9f5d4d01ff5.

**Comment by jakubklimek** [comment]
Did you try \t?

**Comment by jindrichmynarz** [comment]
That works. It should be then documented which characters need to be escaped.
