### ISSUE TITLE
t-unpack bzip2 decompression mangles data

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#49]
When I decompress English DBpedia labels bzip2 dump from <http://downloads.dbpedia.org/2015-04/core-i18n/en/labels_en.ttl.bz2> with the t-unpack, the result contains mangled characters, such as the following:

```
<http://dbpedia.org/resource/Contempor√¢neos> <http://www.w3.org/2000/01/rdf-schema#label> "Contempor√¢neo0ë6ug©ÌréHÅö…ñï8fw4‚7⁄ŒóΩ¶}°O‘Öxå ?Ã9Œ~À”÷æ∏®^Óù·Å
ÜÙÖzÚ+4mfı¿Rø≠0µäXgÑ,Ô∂S
4ÀÈ:‰yıúVÂ§°í6;?äœpŸKäÌ{n¬· ;)”f¥HN¯∑«d-e™Õn1äNËà¯F¨∂óQ”x'Jëå…V√‡‡˝‚ÓEH	ÍÄ¬¶‰3V¥-òÛ˜Z"qa˙∏
y£ÉöSk˚2 2ê¡Ê_™¸V™DÌxá©µwÅ‹ˇ€~ÆßáOdùDâ6ö÷#æG˚√]b!ÜíªüÅ}gIﬁE´Êä»b'[’4ä⁄Öõƒl3?ïüIV¬#8Óvø·|Ä¡π„öã Æ X™»ß˙ÿ
˘ç03—g>"∏iI˘”x´}8ªgπn]4’0?0;«`ßG≈
```

This makes the file syntactically invalid.

However, when I decompress the same file with `bzip2` (version 1.0.6) shell tool, the result is OK.

**Comment by skodape** [comment]
Could you please provide me with line number of this invalid string in the labels_en.ttl file?

**Comment by jindrichmynarz** [comment]
Apache Jena Riot locates the error at line: 5585903, col: 77, which seems off.

**Comment by jindrichmynarz** [comment]
However, it seems to me that the error is not precisely reproducible. I have run the extraction several times and each time the mangled characters appeared in different locations in the output file.

**Comment by jindrichmynarz** [comment]
Upon further investigation it shows that the characters are mangled by l-filesToScp instead of t-unpack.
