### ISSUE TITLE
Add new features of "SPARQL endpoint list to single graph" to "SPARQL endpoint chunked list"

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#491]
Namely:

- IRI encoding
- Reporting

No need for grouping as this is naturally given by the tasks and chunking.

**Comment by martinnec** [comment]
And also SPARQL endpoint chunked.

**Comment by jakubklimek** [comment]
The labels should not be "Encode RDF" but "Encode invalid IRIs"
