### ISSUE TITLE
Debug from + new components lead to lost debug data

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#492]
1. Open an execution
2. Add new components (one with error)
3. Execute

The errorneous component is run before components "already run in the last execution" and fails the pipeline. The components which already had data from the previous execution are now marked as "not run" , and therefore will run freshly in the next "debug from".

**Comment by skodapetr** [comment]
Component's IRI is used to sort components, thus if the newly added component has IRI smaller than the existing ones this may happen.

**Comment by skodapetr** [comment]
Will be fixed as a part of #537 .
