### ISSUE TITLE
Date fields in Dataset metadata and Distribution metadata DPUs should have a date picker

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#5]
Date fields in Dataset metadata and Distribution metadata DPUs should have a date picker. Otherwise, users need to guess in what format to provide the date. This is relevant to the fields "Issued" and "Modified".

**Comment by skodape** [comment]
They should have it as they are of type "date" (HTML 5)
```
<input type="date" ..
```
What browser are you using? Do you see date pickers [here](http://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_date)?

**Comment by jindrichmynarz** [comment]
I'm using Firefox 44.0, which doesn't show a date picker on the mentioned link. Chrome seems to support it, so it's probably just a browser incompatibility.

**Comment by jakubklimek** [comment]
This should be resolved by using https://material.angularjs.org/latest/demo/datepicker where applicable

**Comment by jakubklimek** [comment]
Fixed by styling by material design.
