### ISSUE TITLE
No components found

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#501]
On a fresh install LP-ETL finds no components. Is the location of components determined by the  `executor.osgi.lib.directory` or `executor.osgi.working.directory` configuration properties? They seem to be correctly pointed to the directories in `etl/deploy`.  Or is it the `storage.jars.directory` property? Should it point to `etl/deploy/jars` or `etl/deploy/jars/core`?

Tested using the develop version 654d3d6e04dcba5c86afae69e5d42842c02729c9.

**Comment by jakubklimek** [comment]
Works for me (tested on Windows and Debian), therefore, the directories are correctly set in the default configuration.properties... Did you perhaps change something?

**Comment by jindrichmynarz** [comment]
First of all, which configuration property determines where the components are located?

I changed the configuration to use absolute paths instead of the default relative ones. It's true that simply using the default configuration works.
