### ISSUE TITLE
Add e-httpHeadList

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#503]
This component shoud execute HTTP HEAD requests and report the results. To be used for checking of existence of files on the web.

**Comment by skodapetr** [comment]
@jakubklimek Can you given example of URL and expected response?

**Comment by jakubklimek** [comment]
Any URL... But e.g. some download url from nkod. Result should be a report including http response headers.

**Comment by skodapetr** [comment]
Configuration example for HTTP HEAD:
'''
@prefix request : <http://plugins.linkedpipes.com/ontology/x-httpRequest#> .

<http://localhost/resources/01> a request:Task ;
  
  request:url "https://volby.cz/opendata/ps2017/PS2017ciselniky20170905_csv.zip" ;
  request:method "HEAD" ;
  request:outputHeaders true .
''

**Comment by skodapetr** [comment]
We already have x-httpRequest that can be used to make almost arbitrary HTTP request. So with possibility to save response HTTP headers, it can be used for this use-case.

**Comment by jakubklimek** [comment]
Fails when it encounters 404. It should put it in the report and continue. So, "skip on error"?

https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2Fcreated-1509721103503&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2Ffddfea10-0514-4129-86df-6e30fb6d7c33

**Comment by skodapetr** [comment]
Skip on error was added in bbf5cf13459e7aeed98509431f77c4bdef21e741
