### ISSUE TITLE
Add authentication support to x-httpRequest

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#512]
Add authentication support to x-httpRequest as it is in some SPARQL extractors so that it can, for instance, execute pipelines on an instance behind a HTTP authentication proxy.

**Comment by skodapetr** [comment]
What kind of authentication?

**Comment by jakubklimek** [comment]
Basic, so that it works e.g. with etl.opendata.cz

**Comment by skodapetr** [comment]
Basic authentication can be done using custom headers.
