### ISSUE TITLE
t-geoTools does not run

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#518]
Fails to run with Root cause: 
```IllegalArgumentException : org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class```

**Comment by skodapetr** [comment]
Seems to be problem with GeoTools (https://osgeo-org.atlassian.net/browse/GEOT-5289) we can try to update to newer version of the library.

**Comment by skodapetr** [comment]
It's working now
https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2Fcreated-1483604174548&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F1562160306497-549-cb710123-abda-4097-9175-147a7d7a1c66
