### ISSUE TITLE
x-virtuoso Progress not working

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#519]
x-virtuoso logs progress correctly in log, but progress is not shown in the dialog.

https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2Fcreated-1512729271628&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F42fd915b-04db-458a-87eb-d2d16216013e

**Comment by skodapetr** [comment]
From the look into the code, x-virtuoso does not report progress.
Changing to feature request.
