### ISSUE TITLE
How to disable debug data when triggering pipeline from API

### ISSUE THREAD

**Issue by skarampatakis** [linkedpipes/etl#523]
Hi all and Happy New Year!

I am triggering a pipeline through POST request from my python script. The problem is that each execution generates excessive debug data. For instance, for an input of ~1MB and generated output ~10 MB there is also some ~120MB of debug data. 

I know there is an option to execute the pipeline without keeping the debug data from the frontend. I have seen that there is some data posted with the request and tried to replicate that behavior. The code is pretty much this
```python
payload = {
                "@id":"",
                "@type":"http://etl.linkedpipes.com/ontology/ExecutionOptions",
                "http://linkedpipes.com/ontology/saveDebugData":False,
                "http://linkedpipes.com/ontology/deleteWorkingData":True
                }
files = {
           'input':('resource.json', json.dumps(resource))
           }
requests.post(url, files=files, json=payload)
```

But it seems that somehow the configuration is ignored. The pipeline runs and completes successfully but it has the debug data also. 

Any hint about this?

**Comment by jakubklimek** [comment]
Hi, Happy New Year to you too.

How I am doing this is:

```json
{"@id": "http://localhost/base",
"@type" : "http://etl.linkedpipes.com/ontology/ExecutionOptions",
"http://linkedpipes.com/ontology/deleteWorkingData" : true,
"http://linkedpipes.com/ontology/saveDebugData" : false,  
"http://linkedpipes.com/ontology/logPolicy" : { 
"@id" : "http://linkedpipes.com/ontology/log/DeleteOnSuccess" }
}
```

So maybe try lowercasing the boolean values or adding the @id value?

**Comment by jakubklimek** [comment]
We are using this in ```curl``` like this:
```
curl -u user:pass -X POST -H "Content-Type: application/ld+json" -d '{"@id": "http://localhost/base","@type" : "http://etl.linkedpipes.com/ontology/ExecutionOptions","http://linkedpipes.com/ontology/deleteWorkingData" : true,"http://linkedpipes.com/ontology/saveDebugData" : false,  "http://linkedpipes.com/ontology/logPolicy" : { "@id" : "http://linkedpipes.com/ontology/log/DeleteOnSuccess" }}' https://....cz/resources/executions?pipeline=https://....cz/resources/pipelines/created-1501141481822
```

Now you are additionally positing the pipeline in a file, we are investigating if that could be the problem

**Comment by skarampatakis** [comment]
Hi @jakubklimek ,
Thank you for your prompt answer. 

The file I send is used by Pipeline input component. 

I made the changes as you suggested. The lowercase boolean values raised an error in Python as was recognised as variables. So I capitalised the first letter to be an eligible python dictionary. 

Then the json=payload as long as I undestand serializes this as json data to post with the request. 

However the pipeline still runs with the debug data on. It seems to somehow been ignored. Is there somehow logged what was received as request on LP? Maybe this is a python related issue.

**Comment by skodapetr** [comment]
Hi @skarampatakis,

there is a difference in handling configuration for non-multipart and multipart request. In case of multipart requests the configuration is not send as a request body (as in case of @jakubklimek  example) but in a `configuration file`.  I've added curl example to the wiki (at the very bottom)
https://github.com/linkedpipes/etl/wiki/Pipeline-execution-with-curl

Could you please try it out? For your case it should be enough just to take the configuration from the body and move it into the `configuration` file.

**Comment by skarampatakis** [comment]
Hi @skodapetr !
It seems that this did the trick! Thank you a lot!

**Comment by skarampatakis** [comment]
I just add the new code for future reference 

```python
options = {"@id": "http://localhost/base",
               "@type" : "http://etl.linkedpipes.com/ontology/ExecutionOptions",
               "http://linkedpipes.com/ontology/deleteWorkingData" : True,
               "http://linkedpipes.com/ontology/saveDebugData" : False,  
               "http://linkedpipes.com/ontology/logPolicy" : { 
               "@id" : "http://linkedpipes.com/ontology/log/DeleteOnSuccess" }
              }
files = {
           'input':('resource.json', json.dumps(resource)),
           'configuration' : ('options.jsonld', json.dumps(options))
            }
requests.post(url, files=files)
```
