### ISSUE TITLE
Execution detail error - can't load data

### ISSUE THREAD

**Issue by martinnec** [linkedpipes/etl#525]
At fit1:

1) execute https://fit1.opendata.cz/resources/pipelines/created-1517565020466

2) pipeline is running as shown in the list of executions

![bug0](https://user-images.githubusercontent.com/4235208/35775485-aafa2752-0989-11e8-9429-c6d222389f91.png)

3) Click on the execution to see the detail.

4) An error "can't load data" occurs:

![bug1](https://user-images.githubusercontent.com/4235208/35775494-c5c094fe-0989-11e8-8c24-3c1099da3dfd.png)

**Comment by skodapetr** [comment]
This is known error (#524) it should have already been fixed, we'll check the version on fit1 server.

**Comment by jakubklimek** [comment]
Redeployed
