### ISSUE TITLE
Better error message for banned components

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#528]
When you use a banned component (e.g., matching `executor.banned_jar_iri_patterns`), then you don't see any error in the front-end. Time of the execution is replaced  with `,NaN:NaN:NaN`. You can see the error only in the executor log. It should be also visible in the front-end, similarly to other errors.

Alternatively, have you considered filtering out banned components from the *Select component* list, so that they cannot be added to a pipeline in the first place?

Tested using the latest develop branch (519b841ae257610fcc376db32720280914b0ba22).

**Comment by jakubklimek** [comment]
I think we can still do better than this:
![image](https://user-images.githubusercontent.com/718827/44969213-729bf980-af4c-11e8-9435-6fab2a3f61b3.png)

**Comment by jakubklimek** [comment]
Actually, this is probably caused by #601

**Comment by skodapetr** [comment]
Was caused by 601, please try again (clean cache before that).
