### ISSUE TITLE
storage tests failing with rdf4j 2.3.1

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#540]
Failed tests:
 DesignerToExecutorTest.dataUnitGroupTest:155->testUnpacking:217 null
 DesignerToExecutorTest.runPortGroups:176->testUnpacking:217 null
 DesignerToExecutorTest.twoBranchesDebugFrom:127->testUnpacking:217 null
 DesignerToExecutorTest.twoBranchesDebugFromTo:134->testUnpacking:217 null
 DesignerToExecutorTest.twoBranchesDebugTo:120->testUnpacking:217 null

It works fine wiht 2.2.1

**Comment by skodapetr** [comment]
The rdf4j version 3.4.1 requires elasticsearch as a mandatory depdenci, we see whether that was intended before working out on OSGI dependencies.

**Comment by skodapetr** [comment]
As of now we are supporting rdf4j version 2.3.2 with custom bundle (without the elastic dependencies).
