### ISSUE TITLE
Add Cancel to pipeline execution view (next to Close)

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#567]
Add Cancel to pipeline execution view (next to Close)

**Comment by skodapetr** [comment]
The pipeline can be cancelled only if it'is running. So what should be there where it pipeline is in queue.

**Comment by jakubklimek** [comment]
Then there should be "Remove from queue"

**Comment by skodapetr** [comment]
I do not think we have any support for that right now. 
Also, the canvas as of now do now nothing about the monitor status, that is also a reason for #651.
