### ISSUE TITLE
Templates missing in copied pipeline

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#570]
When I copy [this pipeline](https://cssz.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fcssz.opendata.cz%2Fresources%2Fpipelines%2F1533799208127) I get a missing template error. The original opens fine though.

**Comment by skodapetr** [comment]
Can you be more specific? Copy on the same instance? Copy from pipeline list, or into another pipeline.

**Comment by jakubklimek** [comment]
Just the copy button in the pipeline list.
