### ISSUE TITLE
LP-ETL does not work with Firefox 52 ESR

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#571]
LP-ETL does not work with [Firefox 52 ESR](https://www.mozilla.org/en-US/firefox/organizations/all/#legacy). When a pipeline is clicked, its opening ends with (the error message is not entirely correct either) `Can't load templates pipeline.`

Please have a look at what it is, if it is something trivial (can be fixed easily) or not (ESR users need to upgrade to Firefox 60 ESR).

**Comment by skodapetr** [comment]
As of now we are using some newer JS syntax (spread operator) that is not supported in that version of FF.
