### ISSUE TITLE
Execute and Debug To should stay in execution view

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#575]
Execucte and Debug To should stay in execution view. Now, they switch to the list of executions, from where the user needs to open the execution again.

**Comment by skodapetr** [comment]
Should there be some indication? 
As until the first component starts there is no visible progress.  Also user do not see, whether the pipeline is running (starting) or is waiting (queued).

**Comment by jakubklimek** [comment]
The view will be switched from pipeline (blue) to execution (orange).

But it is true that this is not best practice and there should be some textual indication. Maybe we should add an explicit prefix "Execution of " before the pipeline name?
