### ISSUE TITLE
"Use temporal coverage" checkbox for spatial coverage in Dataset metadata DPU

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#6]
The checkbox for spatial coverage in the Dataset metadata DPU is labelled as "Use temporal coverage". This is probably an error caused by copy-pasting the label of temporal coverage. The label should be "Use spatial coverage".

**Comment by skodape** [comment]
You are right, the label is bad, it should be "Use current date as temporal coverage end" - fixed in develop.

**Comment by jindrichmynarz** [comment]
Really? It seems as if the checkbox was intended for the spatial coverage, not the temporal one.
