### ISSUE TITLE
Deleted execution is deleted, but remains in executions list until refresh

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#600]
Deleted execution is deleted, but remains in executions list until hard reload.

1. In Execution list, delete an execution
2. It is still there - subsequent deletes give a 404, because it actually is deleted
3. Refresh - it is gone

**Comment by skodapetr** [comment]
Any more details as I can not reproduce on demo instance. 
Deleting execution from execution list delete the execution from the list.

Do you have the original delete query + subsequential updates?

**Comment by jakubklimek** [comment]
Seems to be working now... maybe some caching issue? We'll see...
