### ISSUE TITLE
Progress reported wrong in execution list

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#610]
![image](https://user-images.githubusercontent.com/718827/45813381-c0498d80-bcd2-11e8-9863-844cb9ad4c01.png)

**Comment by skodapetr** [comment]
Executor counts only components for execution to total number of components to execute.
At the same time however it counts mapped components as components that have been executed, causing number of executed > total.

**Comment by jakubklimek** [comment]
I still think that this is not correct:
![image](https://user-images.githubusercontent.com/718827/47160677-baa29000-d2f0-11e8-849c-85ede2c8f388.png)
There are 4 components not disabled, two to be reused, two to be run (I used debug to on the bottommost one). When the second component is getting mapped, the progress indicated in execution view is already >= 100%.
