### ISSUE TITLE
Import of pipelines from UnifiedViews exports

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#63]
Provide means of importing pipelines from UnifiedViews exports.
This includes
- [ ] Mapping Core UV DPUs to LP-ETL components
- [ ] Detection of non-core UV DPUs
- [ ] Providing means of mapping non-core UV DPUs to custom LP-ETL components
- [ ] Dealing with UV template configurations

**Comment by skodape** [comment]
Solved by uv2elt tool at https://github.com/linkedpipes/uv2etl
