### ISSUE TITLE
Build errors on MacOS 10.13.6

### ISSUE THREAD

**Issue by dmccreary** [linkedpipes/etl#638]
When I run "mvn install" I get the following errors:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project api-executor-v1: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/dmccrea1/Documents/workspace/etl/api-executor-v1/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :api-executor-v1

**java -version**
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**mac:etl$ mvn -version**
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T13:41:47-05:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 1.8.0_144, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"
mac:etl$

**Comment by dmccreary** [comment]
Note that when I do a **mvn install -DskipTests** the process does finish.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:44 min
[INFO] Finished at: 2018-11-17T02:58:53-06:00
[INFO] ------------------------------------------------------------------------

mac:etl$ ls -l deploy
total 72
-rw-r--r--  1 dmccrea1  MS\Domain Users  3818 Nov 17 02:58 configuration.properties
drwxr-xr-x  4 dmccrea1  MS\Domain Users   128 Nov 17 02:57 executor
drwxr-xr-x  4 dmccrea1  MS\Domain Users   128 Nov 17 02:57 executor-monitor
-rw-r--r--  1 dmccrea1  MS\Domain Users    96 Nov 17 02:57 executor-monitor.bat
-rwxr--r--  1 dmccrea1  MS\Domain Users   117 Nov 17 02:57 executor-monitor.sh
-rw-r--r--  1 dmccrea1  MS\Domain Users    80 Nov 17 02:57 executor.bat
-rwxr--r--  1 dmccrea1  MS\Domain Users   101 Nov 17 02:57 executor.sh
drwxr-xr-x  9 dmccrea1  MS\Domain Users   288 Nov 17 02:58 frontend
-rw-r--r--  1 dmccrea1  MS\Domain Users   230 Nov 17 02:58 frontend.bat
-rwxr--r--  1 dmccrea1  MS\Domain Users   225 Nov 17 02:58 frontend.sh
drwxr-xr-x  3 dmccrea1  MS\Domain Users    96 Nov 17 02:58 jars
drwxr-xr-x  4 dmccrea1  MS\Domain Users   128 Nov 17 02:58 osgi
drwxr-xr-x  4 dmccrea1  MS\Domain Users   128 Nov 17 02:57 storage
-rw-r--r--  1 dmccrea1  MS\Domain Users    78 Nov 17 02:57 storage.bat
-rwxr--r--  1 dmccrea1  MS\Domain Users    99 Nov 17 02:57 storage.sh

**Comment by skodapetr** [comment]
@dmccreary Thanks for the report. Can I ask you for the rest of the failing log (it would make fixing it much easier)? As from the one you provided it's not visible wich test have failed.

**Comment by skodapetr** [comment]
Unfortunately, as we were not able to replicate this error (even on Mac) and no additional info was provided there is nothing we can do :(

What is missing are the names of the test that failed.
