### ISSUE TITLE
Add support for SHACL

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#647]
Add support for [SHACL](https://www.w3.org/TR/shacl/) validation.
It should be a new component (`q-shacl`) with 2 inputs - Data graph, Shapes graph and 1 output - Validation report.

- There is some [initial work on SHACL support in RDF4J](https://github.com/eclipse/rdf4j-storage/pull/34), however, the support is in form of a Shacl repository, which I am not sure will be useful to our use case
- The [reference implementation](https://github.com/TopQuadrant/shacl) is based on Apache Jena, so I guess such component would have to work with files, shielding the users from the implementation a bit, unless we are willing to add Jena support and all the related transformers.

Related to #631

**Comment by skodapetr** [comment]
We can consider providing the rules as an input. 
But as of now the used repository is in-memory, so it can not really handle larger data.
A nativ repository can be beter but may cause issues with performance. 
Another alternative is chunked version of this component.
