### ISSUE TITLE
mvn install does not create the executor.sh

### ISSUE THREAD

**Issue by costezki** [linkedpipes/etl#665]
I do not manage to build a complete distribution as I used to 
To reproduce the problem start fresh:
1. git clone https://github.com/linkedpipes/etl
2. cf ./etl
3. mvn install

Expected: in ./deploy folder the find four *.sh files 
Result: only 3 except for *executor.sh*

**Comment by skodapetr** [comment]
Thank you for the report, can you re-test with current develop?

**Comment by costezki** [comment]
Just re-tested ans still only 3 *.sh files are in ./deploy folder
executor-monitor.sh, frontend.sh, storage.sh

**Comment by jakubklimek** [comment]
@costezki this is weird, never happened to me. Can you send your system spec?
OS, Java version, Maven version (`mvn -V`)

**Comment by jakubklimek** [comment]
Cannot reproduce this. We can reopen this, if it still happens somewhere.
