### ISSUE TITLE
RDF to HDT - confusing dialog

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#666]
It is not clear what should be configured in RDF to HDT - the labels and hints are all wrong. I guess the output file will not be named `.ttl`. And what is the second option?
![image](https://user-images.githubusercontent.com/718827/52773321-f3523c00-303a-11e9-80e8-80adf4ea0083.png)

**Comment by skodapetr** [comment]
The output name is fully set by the user, so besides the bad placeholder, it could be named output.ttl.

The second option is default output IRI - it needs to be set to HDT when creating an export.
