### ISSUE TITLE
Cannot download specific files

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#679]
In [this pipeline](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2F1554484163569) there are two http gets. One downloads https://data.gov.cz/otevřené-formální-normy/registr-práv-a-povinností/údaje and ends up with HTTP 404. The other one downloads https://data.gov.cz/otevřené-formální-normy/registr-práv-a-povinností/údaje/ just fine (slash at the end). The same issue is with HTTP Request.

In the nginx log I see:
```
"GET /otev%C5%99en%C3%A9-form%C3%A1ln%C3%AD-normy/registr-pr%C3%A1v-a-povinnost%C3%AD/soukromopr%C3%A1vn%C3%AD-u%C5%BEivatel%C3%A9-%C3%BAdaj%C5%AF HTTP/1.1" 301 170 "-" "Java/11.0.3" "-"

"GET /otev\xC3\x85\xC2\x99en\xC3\x83\xC2\xA9-form\xC3\x83\xC2\xA1ln\xC3\x83\xC2\xAD-normy/registr-pr\xC3\x83\xC2\xA1v-a-povinnost\xC3\x83\xC2\xAD/soukromopr\xC3\x83\xC2\xA1vn\xC3\x83\xC2\xAD-u\xC3\x85\xC2\xBEivatel\xC3\x83\xC2\xA9-\xC3\x83\xC2\xBAdaj\xC3\x85\xC2\xAF/ HTTP/1.1" 404 7694 "-" "Java/11.0.3" "-"
```
There seems to be an issue with decoding the redirect, as without the redirect the file downloads fine.

**Comment by skodapetr** [comment]
A to patří co k čemu? Jakože ta 404 k té první tj. https://data.gov.cz/otevřené-formální-normy/registr-práv-a-povinností/údaje ? 

Čekal bych že tam budou 2 zápisy jeden pro https://data.gov.cz/otevřené-formální-normy/registr-práv-a-povinností/údaje a druhý pro https://data.gov.cz/otevřené-formální-normy/registr-práv-a-povinností/údaje/

takhle mi není jasné jak to je.

**Comment by skodapetr** [comment]
According to answer in https://stackoverflow.com/questions/7654207/what-charset-should-be-used-for-a-location-header-in-a-301-response
```
RFC 2616 specifies that the Location header should contain a URI as defined by RFC 1630, which requires a URI be 7-bit clean ASCII with any special characters URL encoded.
```

This is however not true as the Server return Location value encoded in UTF-8.
Interesting point is that for redirect from HTTP to HTTPS proper value is returned.
