### ISSUE TITLE
Error loading app js scripts

### ISSUE THREAD

**Issue by omare13** [linkedpipes/etl#686]
Hello, 

Thanks for your efforts, I really found LinkedPipes ETL a very interesting tool that I want to introduce to Digital Humanities students...

In any case, I'm trying to serve ETL as a webapp in a server (e.g. http://my.domain.com/etl). I already configured the server to proxypass **/etl** to the specified `frontend.webserver.port`.
After having successfully installed and run the components, the only thing I can see is the LinkedPipes icon and a title on the browser. I get the next error on browser's console when accessing to the app's address:

> [1] The script "my.domain.com/app/modules/vocabulary.js" was loaded even though its mime type (“text/html”) is not a valid javascript mime type
> [2] Loading failed for the <script> with source ”my.domain.com/app/modules/vocabulary.js"
> Error: Script error for "vocabulary", needed by: app/components/templates/template-service
> http://requirejs.org/docs/errors.html#scripterror require.min.js:5:1067
>     makeError my.domain.com/etl/libraries/requirejs/require.min.js:5
>     onScriptError my.domain.com/etl/libraries/requirejs/require.min.js:5
> [3] The same as [1] for jsonld instead of vocabulary
> [4] The same as [2] for jsonld instead of vocabulary

I'm not very experienced with these errors, but I don't understand why [1] seems to try to load a script with an unreachable URL (etl/ is missing), whereas in [2] requireJS says a problem was found when loading the script (whose URL is the appropriate). 

Do you have any suggestion? Thanks in advance!

The configuration of the server is the following:
- Maven 3.6.0
- NPM 5.6.0
- Node 8.10.0
- Java OpenJDK 1.8.0_212

I'll be glad to send you more detailed info if needed.

Regards

**Comment by jakubklimek** [comment]
Hello,
So far, we have no support for running LP-ETL in a subfolder. We could work on that. Nevertheless, until this is fixed (cannot make promises as to the timeline), try to dedicate a subdomain to LP-ETL, such as etl.my.domain.com - this is how we run all our instances.

**Comment by skodapetr** [comment]
Some changes have been made, the configuration need to be updated (domain.uri, executor.execution.uriPrefix).
The FTP server can probably be solved outside of ETL.

**Comment by skodapetr** [comment]
@omare13 Hi,
some of the URLs (for example vocabulary.js, jsonld.js) were absolute meaning the prefix was ignored (that is the cause of the errors). I tried to fix those, but we need to do some testing to make sure that everything works. 

You can either wait or test it yourself on lates develop.

**Comment by jakubklimek** [comment]
Now it works, with reverse proxy configured as so:
```nginx
        location /etl/ {
                proxy_pass http://localhost:8080/;
                proxy_pass_request_headers      on;
                proxy_set_header   X-Real-IP        $remote_addr;
                proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        }
```
