### ISSUE TITLE
Files from local ?

### ISSUE THREAD

**Issue by lolostar** [linkedpipes/etl#687]
Hi,

I know this issue has been treated somme years ago, but I can't find the good way to introduce the good parameters in the good file.

Thank you for helping

Laurent

Component: Files from local
Status: Failed
Start:
End: 2019-06-12 16:29:23
Duration:
Cause: 
Root cause: 
LpException : This component is banned on this instance.

**Comment by jakubklimek** [comment]
Hello,

it is in configuration.properties, https://github.com/linkedpipes/etl/blob/master/configuration.properties.sample#L51

**Comment by lolostar** [comment]
Thanks

**Comment by lolostar** [comment]
Hi,

Hi,

I installed etl on a new machine and I get :

WARNING: An illegal reflective access operation has occurredTL-Frontend@1.0.0-alpha.0~prepare: LP-ETL-Frontend@1.0.0-alpha.0
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/home/centos/Applications/etl/deploy/executor-monitor/lib/spring-core-4.3.20.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
We have started our server on port  8080

although I changed the conf file as indicated 
[configuration.properties.txt](https://github.com/linkedpipes/etl/files/3306328/configuration.properties.txt)

Any idea ?
