### ISSUE TITLE
Debug data invalidation error

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#689]
When clicking on the "Invalidate data" button, the first and third component in the second column is not invalidated, as can be seen in the screenshot.
![image](https://user-images.githubusercontent.com/718827/59662553-7a601e00-91ad-11e9-8c9e-d5de3ecb367f.png)

[Pipeline](https://github.com/linkedpipes/etl/files/3300344/Generate.data.sample.jsonld.txt)

**Comment by skodapetr** [comment]
This was? caused by the presence of non-executed components in the rest of the pipeline.
Therefore, just import of the pipeline, execution and disabling of mapping for the first component does not reproduce the issue.
So next time please include a screen of the whole pipeline.
