### ISSUE TITLE
Add support for cancelling a pipeline

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#69]
We should be able to cancel a long running pipeline

**Comment by jindrichmynarz** [comment]
This would be also useful for cancelling pipelines that you run and later discover they have a bug that makes them run forever.

**Comment by jindrichmynarz** [comment]
Ah, I see there's a button for cancelling pipeline executions in a7d2cb595f26f8d7b5c50900827dadc5f9f980a8. It's a bit hidden under the popup menu.

However, when I cancel the pipeline, the executor logs "c.l.e.e.p.PipelineExecutor - Cancelling component!", but the execution monitor logs "c.l.e.e.m.e.ExecutionChecker -  5db555dd-ac77-43b1-a66a-4f89fa0a96bb : RUNNING" and the pipeline seems to keep running.

**Comment by jakubklimek** [comment]
Yes. It cancels the pipeline only between running 2 components.

**Comment by jindrichmynarz** [comment]
OK, so the currently running component needs to finish before the pipeline is cancelled? If that's sufficient solution, then probably this issue can be closed, right?

I wonder if it is possible to call [`RepositoryConnection#close()`](http://docs.rdf4j.org/javadoc/1.0/org/eclipse/rdf4j/repository/RepositoryConnection.html#close--) to cancel RDF4J transactions.

**Comment by jakubklimek** [comment]
This is only part of the solution. The original intention of having executor separated was to be able to kill it, which is however not implemented yet.

**Comment by jindrichmynarz** [comment]
Perhaps the interface required from components can be extended with a `cancel` method that is called to cancel the execution of the component. The method can be in turn implemented in a component-specific way.

**Comment by jakubklimek** [comment]
Actually, some components, especially the task-based ones, have support for cancellation between tasks.
