### ISSUE TITLE
Wikibase loader: Fix labels

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#691]
- [ ] Endpoint => Wikibase API Endpoint URL
- [ ] Site IRI => Wikibase Entity IRI prefix
- [ ] Placeholders - use `https://your.wikibase.org` in placeholders, instad of `wikibase.localhost.cz`

**Comment by skodapetr** [comment]
Could we get the site IRI from the endpoint URL as the IRIs have predefined structure?
