### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by skodapetr** [linkedpipes/etl#698]
Google font does not include all the icons we used.
This include pipeline status icons and component menu icons, they need to be replaced.
Please specify names for new icons.

**Comment by jakubklimek** [comment]
@skodapetr Can you specify which ones they are? I found the following component menu icons missing:
Enable/Disable = `offline_bolt` (outlined)
Copy = `file_copy` (outlined)

**Comment by skodapetr** [comment]
There might be more, but we can start with:
![image](https://user-images.githubusercontent.com/3341693/60945387-b178a980-a2eb-11e9-89f9-2c54c44c044e.png)

**Comment by jakubklimek** [comment]
That is still `file_copy`

**Comment by jakubklimek** [comment]
Pipeline in queue: `hourglass_empty`
Pipeline running: `play_circle_outline`

**Comment by skodapetr** [comment]
Unfortunately, it seems that the font version of the icons is not maintained.
The [official master](https://github.com/google/material-design-icons/tree/master/iconfont) is from is three years old and even the version from 2019 that can be obtained from google does not include many icons. 
This issue is mentioned for example https://github.com/google/material-design-icons/issues/798.
A solution is to use a [fork](https://github.com/jossef/material-design-icons-iconfont) and https://jossef.github.io/material-design-icons-iconfont/ instead of https://material.io/tools/icons/ .
