### ISSUE TITLE
Debug browser: Missing content-type in API call

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#699]
![image](https://user-images.githubusercontent.com/718827/60645282-97951d80-9e38-11e9-93da-641f512bf5b2.png)

**Comment by skodapetr** [comment]
And should all of that be text or..?

**Comment by jakubklimek** [comment]
Actually, now I am thinking why is the "open in new tab" functionality necessary. Isn't 1) download and 2) open syntax highlighted in a web page enough?

Then it should be clear - when downloading, the content-type should be appropriate for the content (to our best knowledge).

When opening for syntax highlighting (as seen in the screenshot), the API call itself should also specify the content being transferred.

Then we do not have to deal with "text allows opening in new tab" which would lead us to use incorrect media types.

**Comment by skodapetr** [comment]
No, as the preview is limited in size.
So we would need a special button like open even if too big. 

Can you provide a list of mappings extension to mime/type that we should support?

**Comment by jakubklimek** [comment]
Limited how? As I see it, I as a LP-ETL user see a file and its size, and I have 2 options, download or preview. If I see the file is big and still do a preview, that should be my problem.

I would start with the usual:
```
.txt  text/plain
.html text/html
.csv text/csv
.json application/json
.xml application/xml
.jsonld application/ld+json
.ttl text/turtle
.trig application/trig
.rdf application/rdf+xml
.nt application/n-triples
.nq application/n-quads
```
All with `charset=utf-8` in the header.

**Comment by skodapetr** [comment]
As of now there is size limitation, try to see 100MB file.

**Comment by jakubklimek** [comment]
And what is the size limit? This is dependent on the user's device. It is clear that large files cannot be viewed in browser. But the user of LP-ETL should be advanced enough to get that.

**Comment by skodapetr** [comment]
Limit removed mime types added.
