### ISSUE TITLE
Debug browser: Add back button

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#705]
There should be a "back" button in the page title as the left-most item.

**Comment by jakubklimek** [comment]
OK, maybe I could be more specific - now the back button is visible even though it does not lead anywhere, i.e. when coming to the http browser file listing. It should be visible only when it is usable.

**Comment by skodapetr** [comment]
Unfortunately, I do not know about any reliable way how to detect this easily without trying to figure that out our selves - ie. monitoring changes in URL manually and guessing what is happening.
