### ISSUE TITLE
SPARQL SELECT component output not in UTF-8

### ISSUE THREAD

**Issue by rizktouma** [linkedpipes/etl#708]
The SPARQL SELECT component generates a CSV file which is not in UTF-8 so some characters of the result are not displayed correctly. Moreover, the encoding of the output CSV cannot be changed through the component's configuration.

Is this planned to be changed? I need to read the generated CSV by another component and it fails when there are unrecognized UTF-8 characters.

**Comment by jakubklimek** [comment]
@rizktouma Thanks for the report. However, we never had such issues. Can you please provide:
1) ideally a test pipeline on https://demo.etl.linkedpipes.com
2) if possible, the SPARQL endpoint URL and type (GraphDB? Virtuoso?), the query used and the resulting file

**Comment by rizktouma** [comment]
@jakubklimek I uploaded a sample pipeline that depicts the problem I'm having here: [SPARQL Select UTF-8 Problem](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2F1562939394046).

I am not executing the SPARQL SELECT query on an endpoint, rather on the output of a "JSON-LD to RDF" component, which in turn gets the data from some JSON files I have on my local machine. In the example pipeline above, I used a text holder instead of the JSON files.

When executing this pipeline on my machine, the CSV file generated by the SPARQL SELECT component does not correctly depict the accented letters that can be seen in the input text holder.

In other components that output files, such as "JSON to JSON-LD", we can specify the encoding we want for the output files. Can the same be done for the SPARQL SELECT component as well?

**Comment by jakubklimek** [comment]
@rizktouma On the demo instance I see it correctly. Could the problem be that on your machine, you are browsing the CSV file through the FTP browser, which displays UTF-8 data incorrectly, but when you actually download the CSV file, it is in fact correct?
Note that in the latest develop version we switched from FTP browsing to HTTP-based browsing of debug data.

**Comment by rizktouma** [comment]
@jakubklimek that's strange I tried executing the same pipeline on my local LinkedPipe installation and I'm still not getting the correct CSV output.

I will look into it more next week, if it's working fine on the demo instance it might indeed be something with my machine.

**Comment by jakubklimek** [comment]
@rizktouma and have you tried actually downloading the CSV file and opening it on your machine, or do you just view it in the FTP browser?

**Comment by rizktouma** [comment]
@jakubklimek I am opening the file locally. In fact, I am executing the entire pipeline on my local LinkedPipes installation. The output CSV doesn't correctly render UTF-8 characters.

**Comment by jakubklimek** [comment]
@rizktouma can you send the resulting CSV and system specs? OS, Java version,  commit ID and browser version?

**Comment by rizktouma** [comment]
It doesn't allow me to upload a CSV file, so I uploaded it as XLSX, but it has exactly the same output.

- Resulting CSV: [table.xlsx](https://github.com/linkedpipes/etl/files/3391761/table.xlsx)
- OS: Windows 10 Enterprise (64 bits)
- Java version: 1.8.0_201
- Browser: Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by jakubklimek** [comment]
@rizktouma thanks, but the excel file does not tell me anything about what might have happened to the CSV. Can you upload the CSV, only rename the file to some allowed extension?

**Comment by rizktouma** [comment]
Ok there you go: [table.csv.pdf](https://github.com/linkedpipes/etl/files/3391814/table.csv.pdf)

**Comment by jakubklimek** [comment]
OK, thanks.
> which in turn gets the data from some JSON files I have on my local machine. 
Can you send me one of the JSON files you mentioned earlier you are actually using in the pipeline? The provided CSV file is UTF-8 encoded, the characters encoded are, however, wrong. I would like to see if the actual input JSON file is UTF-8 encoded - this information might have been lost when you copy&pasted part of the JSON to the text holder on our demo instance.

**Comment by rizktouma** [comment]
Ok here is a sample of the JSON files I have: [opendata_sample_1.json.pdf](https://github.com/linkedpipes/etl/files/3391868/opendata_sample_1.json.pdf)

I checked their encoding is UTF-8. I am also passing them through a "JSON to JSON-LD" component and the resulting JSON-LD file is also encoded in UTF-8.

**Comment by jakubklimek** [comment]
The JSON file uses "UTF-8 BOM" encoding, which is [illegal in JSON](https://stackoverflow.com/questions/4990095/json-specification-and-usage-of-bom-charset-encoding). Can you try to convert the JSON files to "UTF-8" without BOM and try that file in the pipeline?

**Comment by rizktouma** [comment]
How are you checking the file encoding? I am saving it as UTF-8 (specifically without BOM) and checking the encoding in different text editors and they all say it's UTF-8. Still the characters in the CSV are not rendered correctly.

**Comment by jakubklimek** [comment]
I use [PSPad](http://www.pspad.com/en/) or [Notepad++](https://notepad-plus-plus.org/) - both are showing the JSON file as "UTF-8 BOM".

**Comment by rizktouma** [comment]
I changed the file locally to UTF-8 without BOM and still getting the same problem. I don't think the encoding of the input file is the cause, because the output of the "JSON to JSON-LD" component is correctly encoded in UTF-8 and all characters are rendered just fine.

I will keep looking into this to see if it's a problem with my machine. In my case, even the pipeline with the input text holder is not generating a UTF-8 CSV.

**Comment by jakubklimek** [comment]
When you open the resulting CSV in a text editor, what encoding does it indicate? The file you sent actually is UTF-8, only the characters written in it are the wrong ones...

**Comment by jakubklimek** [comment]
@rizktouma I was able to reproduce the error. It seems that the JSON-LD to RDF component actually mangles the characters on Windows. @skodapetr please take a look at [this pipeline](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2F1562939394046).

**Comment by skodapetr** [comment]
The issue is in semarglproject library (as of now not maintained for few years)  that uses default platform encoding - that is the reason why it was hard to reproduce. 
The default encoding can be changed at the start of java program using ```-Dfile.encoding=...```.
I've changed the encoding to utf-8, but in future, we should consider whether the encoding should not be a part of a (per file?) configuration.

**Comment by jakubklimek** [comment]
Works now. @rizktouma please confirm.

**Comment by rizktouma** [comment]
Yes it is working now thank you for the quick fix. Will you move this commit to master or do I have to keep using the "develop" branch?

**Comment by jakubklimek** [comment]
We have some large changes in develop atm (mainly the http browser and Wikibase loading component) that we need to test some more, so for now, stick to the develop branch. Eventually, the merge to master will happen.
