### ISSUE TITLE
Debug browser: After download cancellation, new one cannot be started right away

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#709]
Debug browser: After download cancellation, new one cannot be started right away.
Repro:
1. Start downloading a larger file and cancel the download
2. Start downloading the file again - it takes considerable time for the download to start again.

**Comment by skodapetr** [comment]
This seems to be connected with behavior (timeouts) and a number of threads in NodeJs as well as Jetty.
However, the approach of the ability to use Nginx to provide static files points on possibilities of modular desing that we should leverage in adressing, not only, this issue.
