### ISSUE TITLE
API for lp-viz integration

### ISSUE THREAD

**Issue by jirihelmich** [linkedpipes/etl#71]
I'd like to open this issue to assemble a list of basic tasks necessary for lp-viz being able to integrate with lp-etl.

As discussed before, both tools will have it's own list of pipelines, mostly because of the fact that lp-viz needs it's LDVM metadata assigned to the pipeline.

Also, we need to find a way how to map LDVM lp-viz components to lp-etl DPUs in order for the lp-viz to be able to assemble a lp-etl pipeline and run it.

Therefore, I would like to talk about what lp-etl could provide and how the API should look like. Let's start with a list of API calls from the high-level POV (no properties, just methods).

```
- ProcessingUnits.list(skip: Int, take: Int) : Seq[ProcessingUnit]
- ProcessingUnits.findByIri(iri: ProcessingUnitIri): Option[ProcessingUnit]
- Pipelines.create(name: String, description: Option[String], ownerId: Option[OwnerId], processingUnits: Seq[ProcessingUnitIri], bindings: Seq[ProcessingUnitBinding]) : PipelineIri
- Pipelines.update(pipelineIri: PipelineIri, name: String, description: Option[String], ownerId: Option[OwnerId], processingUnits: Seq[ProcessingUnitIri], bindings: Seq[ProcessingUnitBinding]) : Unit
- Pipelines.delete(pipelineIri: PipelineIri) : Unit
- Pipelines.evaluate(pipelineIri: PipelineIri) : Option[PipelineEvaluation(evaluationIri: EvaluationIri)]
- Evaluations.cancel(evaluationIri: EvaluationIri) : Unit
- Evaluations.findByIri(evaluationIri: EvaluationIri) : Option[PipelineEvaluation]
- Evaluations.list(pipelineIri: PipelineIri, skip: Int, take: Int) : Seq[PipelineEvaluation]
- Evaluations.delete(evaluationIri: EvaluationIri) : Unit
- Evaluations.getLast(pipelineIri: PipelineIri) : Option[PipelineEvaluation]
- Evaluations.schedule(pipelineIri: PipelineIri, options: SchedulerOptions) : Option[Schedule]
- Pipelines.setVisualization(pipelineIri: PipelineIri, visualizationIri: VisualizationIri) : Unit
```

Notes:
- PipelineEvaluation could optionally contain estimated time of evaluation (based on previous runs)
- PipelineEvaluation contains status of evaluation
- ability to assign the pipeline visualization IRI -> link to LP-VIZ from LP-ETL

**Comment by jakubklimek** [comment]
@skodapetr  @jirihelmich Is there still something missing in the API / is this still valid with the current state of things?
