### ISSUE TITLE
Dataset metadata DPU placeholder in Czech

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#72]
Placeholder for the field "Description in original language" in the Dataset metadata DPU is in Czech (i.e., "Popis mého datasetu") instead of English as is the rest of the LinkedPipes ETL user interface.

**Comment by jakubklimek** [comment]
This is correct, the title, description and keywords in original language are not supposed to be English, unless the original language is English. That is why they are in Czech.

**Comment by jindrichmynarz** [comment]
In this case, "Original language tag" is filled in as "en", therefore the original language is English, right? So it is in fact an issue.

**Comment by jakubklimek** [comment]
I don't think it is an issue. The placeholder for the input field is fixed, not dependent on the filled in language tag. This would mean having a placeholder for every language, which is not realistic.

**Comment by jindrichmynarz** [comment]
Well, from your previous comment I understood that the placeholders change based on the original language. If that is not the case, the same default language should be used throughout the application; this is currently English.

**Comment by jakubklimek** [comment]
I don't think so. The placeholders in Czech demonstrate that the original
language can be anything. Which is better than having the same placeholders
for english and nonenglish fields. Nevertheless, these dpus are to be
replaced anyway, so thete is no point in this discussion.

**Comment by jindrichmynarz** [comment]
> The placeholders in Czech demonstrate that the original language can be anything.

Surely this is not necessary to demonstrate to end users?

But OK, let's close the discussion for now.
