### ISSUE TITLE
Tag autocomplete in pipeline detail does not work

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#723]
In pipeline detail, I can create the tag, but it does not autocomplete.

**Comment by skodapetr** [comment]
So it is not "tag search" but autocomplete in pipeline detail.

**Comment by jakubklimek** [comment]
Now it works only partially. See our demo instance. When I search for tags in pipeline list, I see i.e. "RUIAN". I dont see it in the pipeline detail tag autocomplete.
