### ISSUE TITLE
Wikibase loader uses too generic edit message

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#729]
We should think about the edit message provided by the wikibase loader. Now it says "cleared an item", which is confusing and not helpful. See the [Wikidata Sandbox Item edit history](https://www.wikidata.org/w/index.php?title=Q4115189&action=history)
![image](https://user-images.githubusercontent.com/718827/62778938-16bde700-bab2-11e9-8cb1-4ad24e9c63f6.png)

**Comment by skodapetr** [comment]
The gray text "Clear an item" is provided by the API as a result of our call that replaces the item. Our message is "Edit entity" and can be customized at will.

**Comment by jakubklimek** [comment]
Can we then add textboxes for these to the component?
