### ISSUE TITLE
"Run after" edge not considered in data invalidation

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#730]
When I invalidate some data for "debug from", the invalidation does not propagate along "run after" edges. However, it should, as this is also a dependency.

![image](https://user-images.githubusercontent.com/718827/62779512-bc258a80-bab3-11e9-87a4-10f444e4528a.png)

**Comment by skodapetr** [comment]
The original intention was to invalidate changed components, although I understand this requirement is is not a bug, it is just a change in expected behavior.

**Comment by jakubklimek** [comment]
Now it works when a component is "invalidated". It, however, does not work when a component is added or an edge is removed:
![image](https://user-images.githubusercontent.com/718827/63515470-3bbb4c80-c4eb-11e9-94bd-d58eb432194e.png)
