### ISSUE TITLE
Wikibase loader fails on "GeoShape" data type

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#738]
See [this execution](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1565792886218&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F1565792939937-185-9ae45299-68c4-404d-95b8-6f130606279d). It fails on GeoShape - a .map file on commons:

```
MediaWikiApiErrorException : [modification-failed] Value must start with "Data:" and end with ".map". In addition title should not contain characters like colon, hash or pipe.
```

**Comment by skodapetr** [comment]
As of now this is not implemented in the used library.
