### ISSUE TITLE
Enable to add descriptions to DPU instances

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#74]
In many cases it is useful to document what a DPU instance does by providing it with a description. It is particularly useful for DPUs that have many different uses, such as SPARQL Update or XSLT DPUs. This is especially true if multiple instances of the same DPU are used in a pipeline. Therefore, it would help if pipeline creator could attach a description to DPU instances (just like in UnifiedViews).

**Comment by jakubklimek** [comment]
Something like this?
http://etl.linkedpipes.com/2016/02/28/components-can-have-descriptions.html

**Comment by jindrichmynarz** [comment]
Ah, I didn't expert it in the "General" tab.
