### ISSUE TITLE
Run after edge broken in pipeline

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#744]
In [this](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2Fcreated-1480578518922) pipeline the runafter edge is broken for some reason.

**Comment by skodapetr** [comment]
This is caused by missing component so invalid data - it is not clear from the current state why the data got corrupted.

**Comment by skodapetr** [comment]
Will be adressed by #749.
