### ISSUE TITLE
l-wikibase - automatic property type determination?

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#745]
Based on https://github.com/Wikidata/Wikidata-Toolkit/pull/434 it seems that Wikidata toolkit should be able to determine property types automatically. We need to investigate this because now we require the definitions from the user.

**Comment by skodapetr** [comment]
It is not really automatic, it is just that the query is executed by the component - but we can probably integrate that into a single component to make the pipeline look "simpler".

**Comment by skodapetr** [comment]
But it seems that we have to wait for new version to include this new functionality.
