### ISSUE TITLE
t-filesToRDF: 404 when accessing JSON-LD context

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#747]
See [this](https://data.gov.cz/otevřené-formální-normy/číselníky/draft/schémata/číselníky.context.jsonld) context. It is there.
However, in [this pipeline](https://etl.data-mff.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.data-mff.opendata.cz%2Fresources%2Fpipelines%2F1568103604676) it says 404. This is probably a bug upstream. 

The same thing happens with t-jsonldformat. In the JSON-LD playground, however, this context IRI is resolved OK.

**Comment by skodapetr** [comment]
It might be caused by the "ř" in the URL. 
Update of libraries seems to change the issue to another one.
THe new issue is caused by some problems with certificates, which desapear after repeated execute of the component. 
As the dependencies are not clear, I'll take a look on it later. 
But it might be interesting to test on the same server with good old fashioned, ASCII friendly, URL.

**Comment by jakubklimek** [comment]
That can be done by rewriting the context iri to percent encoded url

**Comment by skodapetr** [comment]
Version update change the exception to 
```
SSLPeerUnverifiedException: peer not authenticated
```
which disappear after the first run and is connected with missing certificates on a local machine.
See http://nerd-ability.blogspot.com/2013/01/tech-how-to-fix-sslpeerunverifiedexcept.html for more information about the required setup.

**Comment by jakubklimek** [comment]
Actually, now [it says](https://etl.data-mff.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.data-mff.opendata.cz%2Fresources%2Fpipelines%2F1568103604676&execution=https:%2F%2Fetl.data-mff.opendata.cz%2Fresources%2Fexecutions%2F1574776481516-7-fc83cb8f-7d99-4884-887e-54348485bc63) `URISyntaxException : Illegal character in path at index 20: https://ofn.gov.cz/ÄÃ­selnÃ­ky/draft/schÃ©mata/ÄÃ­selnÃ­ky.context.jsonld` - pointing at encoding problems.
