### ISSUE TITLE
Issues with running older version of LP

### ISSUE THREAD

**Issue by fathoni** [linkedpipes/etl#750]
Hi @skodapetr  & @jakubklimek,

Is it possible to run older version of LinkedPipes? Using older (early 2017) commits from LinkedPipes, I could not install LinkedPipes due to two problems: one defined [here](https://github.com/linkedpipes/etl/issues/314), and: 

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.7:copy (default) on project dependencies: Unable to resolve artifact.: Could not transfer artifact com.googlecode.efficient-java-matrix-library:core-osgi:jar:0.26 from/to artefacts.linkedpipes.com (https://artefacts.linkedpipes.com/repository/maven-public/): artefacts.linkedpipes.com`

The reason I want to run an older version of LP is that I would like to run several older LP transformation [pipelines](https://github.com/openbudgets/datasets/tree/master/greek-municipalities/municipality-of-thessaloniki/pipelines). The latest version of LP breaks the pipeline, possibly because the plugin [t-tabular-odcs](https://etl.linkedpipes.com/components/t-tabularodcs), which was used in the pipelines, no longer produces <http://linked.opendata.cz/ontology/odcs/tabular/row> .

I am on Maven 3.6.0 and  Java 8 (1.8.0_181).

**Comment by jakubklimek** [comment]
Hi,

No, it is not possible due to removed hosting of older dependencies. However, running the pipeline in the current version should work. If it does not, it is a bug. Could you open an issue for the component?
