### ISSUE TITLE
Plugin t-tabular-odcs does not produce row property

### ISSUE THREAD

**Issue by fathoni** [linkedpipes/etl#751]
According to the WHERE statements in these [pipelines](https://github.com/openbudgets/datasets/tree/master/greek-municipalities/municipality-of-thessaloniki/pipelines), e.g., [here](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-thessaloniki/pipelines/Municipality%20of%20Thessaloniki%20Revenue%20Budget%202015.jsonld):

```
CONSTRUCT {
?myDataset qb:slice ?slice .
...
} 

WHERE {
?slice a qb:Slice .
...
?slice <http://linked.opendata.cz/ontology/odcs/tabular/row> ?row.
...
}
```

the component [t-tabular-odcs ](https://etl.linkedpipes.com/components/t-tabularodcs)is expected to produce http://linked.opendata.cz/ontology/odcs/tabular/row property which would yield a row number as an object literal. After debugging, it can be noticed that running the pipelines on the current version of LP does not provide this property and row number. Is it a bug within the t-tabular-odcs component?

The expected turtle output from the pipeline can be seen [here](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-thessaloniki/dataset/budget-thessaloniki-revenue-2015.ttl). Currently the pipeline produces a different result due to the unsatisfied condition on the SPARQL construct query.

**Comment by skodapetr** [comment]
The configuration were using "wrong" property name which however seems to be around for quite a while. However, it should generate the row property with row number now.

**Comment by jakubklimek** [comment]
@fathoni I tested it and after the fix, it should work with the current version from the develop branch.

**Comment by fathoni** [comment]
After testing the develop branch locally, I can confirm that the bug has been fixed. Thank you.
