### ISSUE TITLE
SPARQL endpoint select scrollable cursor: error on empty filename

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#753]
When the filename in SPARQL endpoint select scrollable cursor is empty, the error says:
`LpException : File already exists: (/data/lp/etl/working/data/1568887717892-319-9ebe2b7d-464a-48c4-8992-92c32125c0af/working/working-outputfiles-6)` which is confusing.

**Comment by skodapetr** [comment]
Pipeline to reproduce?

**Comment by jakubklimek** [comment]
https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1568888009544

**Comment by skodapetr** [comment]
The configuration is missing file name. 
This may call for better validation of the data, but similar issues may be find for all components so should we decide to do it we should do it for all components and in another issue.
