### ISSUE TITLE
etl.linkedpipes.com is not accessible (error code 113)

### ISSUE THREAD

**Issue by gregid** [linkedpipes/etl#758]
There seem to be out of date certificate for all linkedpipes sites making them not accessible.

**Comment by jakubklimek** [comment]
@gregid thanks, but I just checked and the sites work OK for me, also [SSL Labs test says](https://www.ssllabs.com/ssltest/analyze.html?d=etl.linkedpipes.com&s=2606%3a4700%3a30%3a0%3a0%3a0%3a681f%3a4ac7&latest) OK.

May it be the case that your client [does not support TLSv1.3](https://caniuse.com/#search=tls%201.3)? Our servers are configured to work over TLSv1.3 only.

**Comment by gregid** [comment]
Thanks for a quick reaction - it does seem to be a problem on some browsers only (Edge being one of them).
But all recent Chrome, Firefox, Opera do work fine indeed.
