### ISSUE TITLE
l-wikibase: Decimal error: 50 different from 50.0, while RDF treats it as the same

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#759]
See [this pipeline](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1565780216634).
1. It deletes references in the statement
2. It merges one reference
3. It merges the same reference.

When run as a whole, result is a statement with one reference.
However, when the second or third loader is run as "debug from & to", it creates a duplicate reference (probably due to different xsd:decimal interpretation).

**Comment by skodapetr** [comment]
Does it have to be  "debug from & to" can I just run the second branch without the first one?

**Comment by jakubklimek** [comment]
It has to be "debug from & to". When The component gets "fresh" data, not from "debug from & to", it works normally.

**Comment by jakubklimek** [comment]
The problem is illustrated by:
```turtle
wdv:9e8a5281739d5db197ea331c455ee34c a wikibase:QuantityValue ;
	wikibase:quantityAmount "+51.0"^^xsd:decimal ;
	wikibase:quantityUpperBound "+61.0"^^xsd:decimal ;
	wikibase:quantityLowerBound "+5.0"^^xsd:decimal ;
	wikibase:quantityUnit <https://wikibase.opendata.cz/entity/Q2106> .

wdv:ac4c64443007de31e5ba1d4eb5fa6242 a wikibase:QuantityValue ;
	wikibase:quantityAmount "+51"^^xsd:decimal ;
	wikibase:quantityUpperBound "+61"^^xsd:decimal ;
	wikibase:quantityLowerBound "+5"^^xsd:decimal ;
	wikibase:quantityUnit <https://wikibase.opendata.cz/entity/Q2106> .
```
