### ISSUE TITLE
Configuring LP to not store intermediary data files

### ISSUE THREAD

**Issue by rizktouma** [linkedpipes/etl#770]
This is more of an inquiry than an issue. We have recently deployed LinkedPipes in a docker container and we're facing an issue with the intermediate data files taking up a lot of disk space. At the moment we're cleaning up the working directory manually every so often in order to remove all the files that are stored.

Can LP be configured to not persist intermediary data files between the components in a pipeline? Alternatively, is there a way to automatically delete the working directory of an execution once the execution is finalized? I remember reading something about this a while back but I can't find it.

**Comment by jakubklimek** [comment]
It is possible via the [API](https://github.com/linkedpipes/etl/wiki/Pipeline-execution-with-curl#pipeline-from-a-local-instance-with-user-inputs-and-configuration), not via the current frontend UI.
