### ISSUE TITLE
l-wikibase: Output also contains mappings of known Items

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#778]
See [this execution](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1572401813888&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F1574083047650-502-130f06ed-aad4-46c9-a6ce-fdd89489f069). The output of the component contains mappings of ALL Items, not only the newly created ones, making it harder to process.

The output should contain only mappings of newly created Items (and statements).

**Comment by skodapetr** [comment]
We now have mapping for new items only. 
As for the statements the situation is a bit more complex so a new issue should be created.
