### ISSUE TITLE
Add support for cancelling loading to Wikidata

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#785]
l-wikibase should be able to stop, when the pipeline execution is cancelled. This could be done also for other task-based components, but let us start with this one.

Cases when cancel should work:

- between individual tasks
- when waiting for lag to be lower (which can be indefinite (#784 )) - e.g. between retries

**Comment by skodapetr** [comment]
Should be already there, just added cancel support when waiting.
