### ISSUE TITLE
l-wikibase: Unable to create qualifier using Item property

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#786]
See [this execution](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1574780209585&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F1574780535330-629-7342b7fd-feba-4888-b908-b7be0d769b1e). A qualifier should be created (works with qualifiers of different, complex types), but it is not. There is no error in the log.

**Comment by skodapetr** [comment]
Where is this syntax coming from, Wikibase seems to use prov:wasDerivedFrom for references.

**Comment by jakubklimek** [comment]
This is a qualifier, not a reference

**Comment by skodapetr** [comment]
@jakubklimek See
  https://wikibase.opendata.cz/wiki/Item:Q2238
  https://wikibase.opendata.cz/wiki/Special:EntityData/Q2238.ttl
this item has a qualifier still the produced TTL looks like this:
```
wds:Q2238-60A0CD82-D742-4E9A-9BBA-D0DB38C03523 a wikibase:Statement, wikibase:BestRank ;
	prov:wasDerivedFrom wdref:2f09a02a42ccd0fa2b98a39fe443cd58a290e727 .

wdref:2f09a02a42ccd0fa2b98a39fe443cd58a290e727 a wikibase:Reference ;
	pr:P19 wd:Q2212 .
```

Could you please create an example data on wikibase and link them here?

**Comment by jakubklimek** [comment]
When I click the ttl link, I see a qualifier, not a reference.

**Comment by skodapetr** [comment]
Cite: Could you please create an example data on wikibase and link them here?
