### ISSUE TITLE
LinkedPipes Executor API 0.0.0 ..................... FAILURE

### ISSUE THREAD

**Issue by versant2612** [linkedpipes/etl#797]
more /home/cloud-di/etl/api-executor-v1/target/surefire-reports/*FieldLoaderTest.txt
-------------------------------------------------------------------------------
Test set: com.linkedpipes.etl.executor.api.v1.rdf.pojo.FieldLoaderTest
-------------------------------------------------------------------------------
Tests run: 18, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.066 sec <<< FAILURE! - in com.linkedpipes.etl.executor.api.v1.rdf.pojo.FieldLoaderTest
loadDate(com.linkedpipes.etl.executor.api.v1.rdf.pojo.FieldLoaderTest)  Time ela
psed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError: expected:<20> but was:<19>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at com.linkedpipes.etl.executor.api.v1.rdf.pojo.FieldLoaderTest.loadDate
(FieldLoaderTest.java:279)

**Comment by jakubklimek** [comment]
@versant2612 Hello, thanks for reporting an issue.

However, we are not able to reproduce it, also our CI tests run fine. Could you please provide some details?

1. Are you running a Docker build, or a build from source?
2. What is your OS and version?
3. What is your Java and Maven version?
4. Are you building the master or the develop branch?

**Comment by versant2612** [comment]
Thank you for the answer. 
1. build from source
2.  Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-74-generic x86_64)
3. openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
maven 3.6.0-1~18.04.1
4. master

**Comment by jakubklimek** [comment]
@versant2612 OK, we reproduced the issue. It has to do with timezones (works with GMT+1, does not work with GMT-3). As this is an issue in a test, while we work on the fix, you can build LP-ETL with tests disabled using `mvn install -DskipTests`

**Comment by versant2612** [comment]
I've tried mvn install -DskipTests on the same machine and a new error occurred

[INFO] plugin t-shacl 0.0.0 ............................... SUCCESS [  0.361 s]
[INFO] LinkedPipes Plugins 0.0.0 .......................... SUCCESS [  0.003 s]
[INFO] LinkedPipes Deploy Plugins 0.0.0 ................... SUCCESS [ 18.805 s]
[INFO] LinkedPipes Frontend 0.0.0 ......................... FAILURE [  2.467 s]
[INFO] LinkedPipes 0.0.0 .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:43 min
[INFO] Finished at: 2020-02-27T19:39:51-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (npm-install) on project frontend: Command execution failed.: Cannot run program "npm" (in directory "/home/cloud-di/etl/frontend"): error=2, No such file or directory -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :frontend

**Comment by jakubklimek** [comment]
@versant2612 do you have node.js installed?

**Comment by versant2612** [comment]
No, my fault, sorry!
The installation completed successfully

[INFO] LinkedPipes Plugins 0.0.0 .......................... SUCCESS [  0.004 s]
[INFO] LinkedPipes Deploy Plugins 0.0.0 ................... SUCCESS [  0.800 s]
[INFO] LinkedPipes Frontend 0.0.0 ......................... SUCCESS [06:21 min]
[INFO] LinkedPipes 0.0.0 .................................. SUCCESS [  0.003 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:05 min
[INFO] Finished at: 2020-03-02T14:43:13-03:00
[INFO] ------------------------------------------------------------------------
