### ISSUE TITLE
When a pipeline is copied, 2 new are created

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#813]
1. Click on "Copy" pipeline
2. 2 copies are created
![image](https://user-images.githubusercontent.com/718827/84900928-11a2ce80-b0ab-11ea-841a-76a5e59648a0.png)

**Comment by skodapetr** [comment]
@jakubklimek I see this hapenning on demo instace, but I can not reproduce on local host. Can you try to update to latest version and check that all is runing as it should?

**Comment by jakubklimek** [comment]
seems to be fixed on demo after redeploy

**Comment by jakubklimek** [comment]
This is happening again 🤷🏻‍♂️

**Comment by psiotwo** [comment]
> This is happening again 🤷🏻‍♂️

yes, experienced this today.
