### ISSUE TITLE
Invalid placeholder query for t-sparqlSelect

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#82]
t-sparqlSelect uses the following query as a placeholder:

```sparql
SELECT { ?s ?p ?o } WHERE { ?s ?p ?o}
```

This query is syntactically invalid (as can be verified [here](http://sparql.org/query-validator.html)). It was probably created as a result of hasty copy-pasting the default CONSTRUCT query.

A correct placeholder query might be:

```sparql
SELECT *
WHERE {
   ?s ?p ?o .
}
```

**Comment by jakubklimek** [comment]
This is actually not a placeholder, but a default configuration. If you delete it, the placeholder is correct.

**Comment by jindrichmynarz** [comment]
OK. Then the default configuration is incorrect and should be corrected.
