### ISSUE TITLE
Build failing due to broken dependencies

### ISSUE THREAD

**Issue by costezki** [linkedpipes/etl#830]
The build process fails due to broken dependencies in the `geotools` and `rdf4j-storage-light` plugins.

My local environment satisfies all the requirements for Java and Maven versions. 

I would appreciate if you could look into these issues.

**Comment by skodapetr** [comment]
@costezki May I ask about the branch/version you are using?

**Comment by jakubklimek** [comment]
I just did a clean build on the develop branch, Java 11, Ubuntu 20.04 and it works for me.

**Comment by costezki** [comment]
Indeed it works today. Ubuntu 20 Java 11. 
`mvn clean && mvn install`
Perhaps there was some networking maintenance going on yesterday, I cannot explain it otherwise. 
My apologies for raising this issue and many thanks for such a prompt reaction.

**Comment by jakubklimek** [comment]
> Perhaps there was some networking maintenance going on yesterday, I cannot explain it otherwise.

That is, of course, always possible.

Glad it works now.
