### ISSUE TITLE
ERROR: error initializing submodules

### ISSUE THREAD

**Issue by radeknoone** [linkedpipes/etl#832]
I'm running this command from the README, but it fails:
url https://raw.githubusercontent.com/linkedpipes/etl/develop/docker-compose.yml | LP_ETL_PORT=9080 LP_ETL_DOMAIN=http://localhost:9080 docker-compose -f - up

`[root@hvt` hvt_etl]# curl https://raw.githubusercontent.com/linkedpipes/etl/develop/docker-compose.yml | LP_ETL_PORT=9080 LP_ETL_DOMAIN=http://localhost:9080 docker-compose -f - up
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2845  100  2845    0     0  13152      0 --:--:-- --:--:-- --:--:-- 13171
Building storage
ERROR: error initializing submodules: usage: git submodule [--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] deinit [-f|--force] [--] <path>...
   or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--recursive] [--] [<path>...]
: exit status 1`

**Comment by skodapetr** [comment]
Hi, I've just tested on Ubuntu 19.10 and it worked fine. There is also no use of git submodule, so I do not know where does the command comes from.

Perhaps could you try to run ```curl https://raw.githubusercontent.com/linkedpipes/etl/develop/docker-compose.yml | LP_ETL_PORT=9080 LP_ETL_DOMAIN=http://localhost:9080 docker-compose --log-level DEBUG -f - up``` as from the information you provided I'm not sure about the root cause of the error.

Could you please also provide us with information about your system (something like ```lsb_release -a```), docker version (```docker --version```) and docker-compose version (```docker-compose --version```) ?

**Comment by radeknoone** [comment]
Of course:

[root@hvt ~]# docker --version
Docker version 19.03.13, build 4484c46d9d
[root@hvt ~]# docker-compose --version
docker-compose version 1.27.4, build 40524192
[root@hvt ~]# hostnamectl 
   Static hostname: hvt.hlubina.com
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 4c928fe91ba74b1b86132046480a5026
           Boot ID: 3b2fd078eef4445a870ab6b081732f16
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1127.19.1.el7.x86_64
      Architecture: x86-64



[root@hvt hvt_etl]# curl https://raw.githubusercontent.com/linkedpipes/etl/develop/docker-compose.yml | LP_ETL_PORT=9080 LP_ETL_DOMAIN=http://localhost:9080 docker-compose --log-level DEBUG -f - up
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2845  100  2845    0     0   6287      0 --:--:-- --:--:-- --:--:--  6294
Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
No config file found
Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
No config file found
Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
No config file found
http://localhost:None "GET /version HTTP/1.1" 200 881
http://localhost:None "GET /v1.40/networks/hvtetl_default HTTP/1.1" 404 47
http://localhost:None "GET /v1.40/volumes/hvtetl_data-storage HTTP/1.1" 404 54
http://localhost:None "GET /v1.40/volumes/hvtetl_configuration HTTP/1.1" 404 55
http://localhost:None "GET /v1.40/volumes/hvtetl_data-logs HTTP/1.1" 404 51
http://localhost:None "GET /v1.40/volumes/hvtetl_data-execution HTTP/1.1" 404 56
http://localhost:None "GET /v1.40/info HTTP/1.1" 200 None
http://localhost:None "GET /v1.40/networks/hvt_etl_default HTTP/1.1" 200 558
http://localhost:None "GET /v1.40/volumes/hvt_etl_data-logs HTTP/1.1" 200 308
http://localhost:None "GET /v1.40/volumes/hvt_etl_data-logs HTTP/1.1" 200 308
http://localhost:None "GET /v1.40/volumes/hvt_etl_data-execution HTTP/1.1" 200 323
http://localhost:None "GET /v1.40/volumes/hvt_etl_data-execution HTTP/1.1" 200 323
http://localhost:None "GET /v1.40/volumes/hvt_etl_data-storage HTTP/1.1" 200 317
http://localhost:None "GET /v1.40/volumes/hvt_etl_data-storage HTTP/1.1" 200 317
http://localhost:None "GET /v1.40/volumes/hvt_etl_configuration HTTP/1.1" 200 320
http://localhost:None "GET /v1.40/volumes/hvt_etl_configuration HTTP/1.1" 200 320
http://localhost:None "GET /v1.40/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dhvt_etl%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
http://localhost:None "GET /v1.40/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dhvtetl%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
http://localhost:None "GET /v1.40/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dhvt_etl%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
http://localhost:None "GET /v1.40/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dhvtetl%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
http://localhost:None "GET /v1.40/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dhvt_etl%22%2C+%22com.docker.compose.service%3Dstorage%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
http://localhost:None "GET /v1.40/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dhvtetl%22%2C+%22com.docker.compose.service%3Dstorage%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
http://localhost:None "GET /v1.40/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dhvt_etl%22%2C+%22com.docker.compose.service%3Dfrontend%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
http://localhost:None "GET /v1.40/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dhvtetl%22%2C+%22com.docker.compose.service%3Dfrontend%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
http://localhost:None "GET /v1.40/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dhvt_etl%22%2C+%22com.docker.compose.service%3Dexecutor-monitor%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
http://localhost:None "GET /v1.40/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dhvtetl%22%2C+%22com.docker.compose.service%3Dexecutor-monitor%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
http://localhost:None "GET /v1.40/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dhvt_etl%22%2C+%22com.docker.compose.service%3Dexecutor%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
http://localhost:None "GET /v1.40/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dhvtetl%22%2C+%22com.docker.compose.service%3Dexecutor%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
http://localhost:None "GET /v1.40/images/lp/etl/storage/json HTTP/1.1" 404 82
Building storage
Looking for auth config
No auth config in memory - loading from filesystem
Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
No config file found
Sending auth config ()
http://localhost:None "POST /v1.40/build?t=lp%2Fetl%2Fstorage&remote=https%3A%2F%2Fgithub.com%2Flinkedpipes%2Fetl.git%23master%3Astorage&q=False&nocache=False&rm=True&forcerm=False&pull=False&buildargs=%7B%22LP_ETL_BUILD_BRANCH%22%3A+%22master%22%2C+%22LP_ETL_BUILD_JAVA_TEST%22%3A+%22-DskipTests%22%2C+%22LP_ETL_USER%22%3A+%225987%22%7D HTTP/1.1" 500 802
ERROR: error initializing submodules: usage: git submodule [--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] deinit [-f|--force] [--] <path>...
   or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--recursive] [--] [<path>...]
: exit status 1
[root@hvt hvt_etl]# 


Thanks for taking care!

**Comment by skodapetr** [comment]
Ok, that does not help as hoped it would :( 

So unfortunately you we may need to result to a sort of debugging session:
The first option would be to try and build the image jsut for the storage using: 
```docker build  https://github.com/linkedpipes/etl.git#master:storage --no-cache --force-rm --rm```

The second is to try and run docker-compose locally after you clone the respository. 

Btw, I assume that you can run and build some other Docker images and iamges from github.
As from the log is seems like there is an issue communicating the the Docker backend. 
It also seems there are some issue reported on other project related to Centos like https://github.com/moby/moby/issues/36965#issuecomment-388248035 .

**Comment by radeknoone** [comment]
Goood job Petře! It was the issue you mentioned. This can help:
yum remove git
yum install https://repo.ius.io/ius-release-el7.rpm 
yum install git224.x86_64
