### ISSUE TITLE
HTML to RDF conversion

### ISSUE THREAD

**Issue by versant2612** [linkedpipes/etl#836]
Is there any tutorial or pipeline example of converting a table from HTML file into triples?

**Comment by jakubklimek** [comment]
@versant2612 I added a sample pipeline to the [component documentation](https://etl.linkedpipes.com/components/t-htmlcssuv). It shows basic usage of the component on a page. The page itself is, unfortunately, in Czech, but the usage of the selectors and the sequence of the necessary steps should be clear, when read together with the specification.
