### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by VranekPavel** [linkedpipes/etl#837]
Component Tabular doesn't decode files with encoding UTF-8 BOM correctly. I had problem with this [file](https://data.mfcr.cz/katalog/sites/default/files/2_DPH_V_TISICICH_KC_ZA_ZDANOVACI_OBDOBI.csv).

**Comment by jakubklimek** [comment]
@VranekPavel I tried to replicate the problem in [this pipeline](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2F1610086979906&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F1610087162488-1224-c3b70568-2d0c-4d63-a6ae-51bc50b40576). What exactly seems to be the problem?

Of course, UTF-8 BOM is not a valid CSV encoding, so I would not be surprised if there were problems. On the other hand, I would expect BOM to manifest at most as extra characters in the first header column, which, in this case, it does not.

**Comment by VranekPavel** [comment]
Well, it seems to me that predicats are not decoded correctly, which is just small inconvenience, but, based on your reply, it seems that it should be this way.

So I gonna close this issue. Thank you for your effort, LinkedPipes is good tool.
