### ISSUE TITLE
Docker-compose not working on Windows

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#851]
![image](https://user-images.githubusercontent.com/718827/113669063-79b2b780-96b3-11eb-9a04-e42e157513d1.png)

**Comment by skodapetr** [comment]
May be related to https://github.com/moby/buildkit/issues/1684

**Comment by skodapetr** [comment]
A workaround is to [disable use of buildkit](https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds), to do so set env. variable ```DOCKER_BUILDKIT``` to 0.

**Comment by panasenco** [comment]
Can confirm that the workaround works for me, thanks @skodapetr 

![image](https://user-images.githubusercontent.com/5506411/114127599-68ce9580-98af-11eb-986b-9179bf8eb13f.png)
