### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by panasenco** [linkedpipes/etl#852]
Please [enable GitHub Discussions](https://docs.github.com/en/discussions/quickstart) on this repo. 🙂 

I am a data warehouse architect interested in contributing data to Wikidata. My first step will be to adapt my [script that downloads solar astrophysics coauthorship data](https://github.com/panasenco/networks/blob/master/solar/build_solar_coauthorship.py) to load the data [into Wikidata ](https://www.wikidata.org/wiki/Q13442814) instead of a local file. 

Before I jump into coding though, I think it'd be immensely helpful to have a public discussion about [your vision for using LinkedPipes with Wikidata](https://meta.wikimedia.org/wiki/Grants:Project/MFFUK/Wikidata_%26_ETL).

**Comment by jakubklimek** [comment]
Done

**Comment by panasenco** [comment]
That was fast!
