### ISSUE TITLE
Investigate options of using Apache Jena tdb2.tdbloader

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#867]
Bulk loading data into Apache Jena's TDB2 is **much** more efficient using [tdb2.tdbloader](https://jena.apache.org/documentation/tdb2/tdb2_cmds.html) than via Fuseki's HTTP. We need to investigate options of utilizing tdbloader from LP-ETL - either via developing a new component, or via utilizing a remote service.

**Comment by skodapetr** [comment]
There is an implementation as a component introduced in 7a7459b1d50076343e1ac281c64c2b72ebad39ab
