### ISSUE TITLE
tdbloader: add write access to group to created files

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#874]
tdb loader creates files with `-rw-r--r--` access rights.
This is problematic, when fuseki runs under the `fuseki` user and LP-ETL runs under the `lpetl` user. Even when I add `fuseki` to the `lpetl` group, it cannot write to anything, which is required.

Could the files be created with `-rw-rw-r--` (664) permissions and folders (Data-001) with `drwxrwxr-x` (775) or is this out of scope of the component?

**Comment by skodapetr** [comment]
The file is created by the library, but we can manually set the permissions. But it may be better to add this options to filesToLocal.
It may be something like https://stackoverflow.com/questions/664432/how-do-i-programmatically-change-file-permissions

**Comment by jakubklimek** [comment]
OK, that seems reasonable.
