### ISSUE TITLE
Add option to set permissions to files to local

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#875]
Based on #874 , we need to add support for setting permissions to files outputted by files to local.

> tdb loader creates files with -rw-r--r-- access rights.
> This is problematic, when fuseki runs under the fuseki user and LP-ETL runs under the lpetl user. Even when I add fuseki to the lpetl group, it cannot write to anything, which is required.
> Could the files be created with -rw-rw-r-- (664) permissions and folders (Data-001) with drwxrwxr-x (775) or is this out of scope of the component?

**Comment by skodapetr** [comment]
The file permissions are set using the string representing the permissions, ie. ```rwxr-x---````.  Some file systems does not support this operation. As a result in case of ```UnsupportedOperationException``` the exception is silently ignored, only a warn log messages is printed. The reason behind this decision is to allow transfer of pipelines from Linux to Windows without the need to manually remote this option for all components.

**Comment by jakubklimek** [comment]
Tested and works on Linux, however, we will need a separate set of permissions for directories, as they typically differ.
