### ISSUE TITLE
Usability enhancement: enable to rename pipeline copy

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#89]
Using the latest develop version (2b9a0f87522cdddf557ae04a856e7adffb7c2241), when you copy a pipeline the copy is named the same, which makes it difficult to distinguish from the original pipeline. It would be better if a dialog enabling to rename the copy was shown when a pipeline is copied.

**Comment by jakubklimek** [comment]
Actually, now "Copy of" is added to the pipeline name. This means the pipeline can be renamed later, if necessary.
