### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by tim-coder** [linkedpipes/etl#901]
Hey gang,

Great Project!

I noticed today that the demo is no longer working.

https://demo.etl.linkedpipes.com/

The URL returns: "502 Bad Gateway"

Is there another way to run the demo?

Thanks,
Tim

**Comment by jakubklimek** [comment]
Sorry about that, we upgraded to Node 17, which is not supported yet. I downgraded to 16 for the moment and started the demo instance again.

You can also run your own instance [using the provided docker images](https://github.com/linkedpipes/etl#docker).
