### ISSUE TITLE
l-couchdb sets user and admin roles to _admin

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#905]
After loading to couchdb 3.2.0, the loaded databases get the `_admin` role assigned both as admin and user, making the db no longer public.
![image](https://user-images.githubusercontent.com/718827/148768259-8365369e-73d2-455c-9ad5-b863e015421a.png)

**Comment by skodapetr** [comment]
This is default behavior of CouchDB, we will need to manually remove all the users after a database is created.
