### ISSUE TITLE
Installing LinkedPipes: build from source

### ISSUE THREAD

**Issue by marianadsalgueiro** [linkedpipes/etl#908]
Hello!

I've been trying to install LinkedPipes on my VM but I keep getting the following error:

[INFO] LinkedPipes Deploy Plugins 0.0.0 ................... SUCCESS [  1.336 s]
[INFO] LinkedPipes Frontend 0.0.0 ......................... FAILURE [02:26 min]
[INFO] LinkedPipes 0.0.0 .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:43 min
[INFO] Finished at: 2022-02-01T13:37:24-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (npm-build) on project frontend: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :frontend

I've installed Maven, Java and Node.js on the machine so I'm guessing maybe there's a problem with the versions I've installed those dependencies. 
Maven: Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Java version: 17.0.1
Node.js: v16.13.1

Thank you in advance!

**Comment by jakubklimek** [comment]
Hello, could you

1. identify your OS
2. try with Node.js 17
3. provide a longer tail of the build log?

I just tested on Ubuntu 21.10, JDK 17.0.1, Node.js 17.4.0 and Maven 3.6.3 and the build went OK

Thank you

**Comment by marianadsalgueiro** [comment]
Hi!

My OS version is:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

I've tried using Node.js 17 but still nothing.

I checked the longer tail of the log just as you asked and I got:
_[INFO] --- exec-maven-plugin:1.6.0:exec (npm-install) @ frontend ---
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated eslint-loader@4.0.2: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated formidable@1.2.2: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 1452 packages, and audited 1453 packages in 1m

134 packages are looking for funding
  run `npm fund` for details

18 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:exec (npm-build) @ frontend ---

> linkedpipes-etl-web-client@1.0.0-alpha.0 build
> cross-env NODE_ENV=production NODE_OPTIONS='--max-old-space-size=2048' webpack --config build/webpack.production.js

[BABEL] Note: The code generator has deoptimised the styling of /home/cloud-di/etl/frontend/node_modules/vuetify/dist/vuetify.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /home/cloud-di/etl/frontend/node_modules/angular-material/angular-material.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /home/cloud-di/etl/frontend/node_modules/angular/angular.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /home/cloud-di/etl/frontend/node_modules/lodash/lodash.js as it exceeds the max of 500KB.

<--- Last few GCs --->

[4513:0x4cf5300]    55498 ms: Scavenge 2026.0 (2074.6) -> 2023.2 (2076.6) MB, 6.2 / 0.0 ms  (average mu = 0.763, current mu = 0.520) allocation failure
[4513:0x4cf5300]    55538 ms: Scavenge 2027.5 (2076.6) -> 2024.6 (2079.3) MB, 7.5 / 0.0 ms  (average mu = 0.763, current mu = 0.520) allocation failure
[4513:0x4cf5300]    55591 ms: Scavenge 2030.6 (2079.3) -> 2027.6 (2096.8) MB, 14.0 / 0.0 ms  (average mu = 0.763, current mu = 0.520) allocation failure


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb2e680 node::Abort() [webpack]
 2: 0xa40252 node::FatalError(char const*, char const*) [webpack]
 3: 0xd1f52e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [webpack]
 4: 0xd1f8a7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [webpack]
 5: 0xed8d05  [webpack]
 6: 0xeea14d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [webpack]
 7: 0xeece7e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [webpack]
 8: 0xeae89a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [webpack]
 9: 0x122ecf8 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [webpack]
10: 0x1632179  [webpack]
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] LinkedPipes Backend Pom 0.0.0 ...................... SUCCESS [  0.091 s]
[INFO] LinkedPipes Plugin Pom 0.0.0 ....................... SUCCESS [  0.008 s]
[INFO] LinkedPipes GeoTools 21.0 .......................... SUCCESS [  6.745 s]
[INFO] LinkedPipes Rdf4j Storage Light 3.7.0 .............. SUCCESS [  6.017 s]
[INFO] LinkedPipes Plugin Libraries 0.0.0 ................. SUCCESS [  0.006 s]
[INFO] LinkedPipes Vocabulary 0.0.0 ....................... SUCCESS [  0.601 s]
[INFO] LinkedPipes Plugin Loader 0.0.0 .................... SUCCESS [  1.589 s]
[INFO] LinkedPipes Executor API 0.0.0 ..................... SUCCESS [  0.326 s]
[INFO] LinkedPipes Plugin Loader 0.0.0 .................... SUCCESS [  0.224 s]
[INFO] LinkedPipes Dataunit 0.0.0 ......................... SUCCESS [  1.258 s]
[INFO] LinkedPipes RDF Utils 0.0.0 ........................ SUCCESS [  0.510 s]
[INFO] LinkedPipes RDF Utils Rdf4j 0.0.0 .................. SUCCESS [  0.586 s]
[INFO] LinkedPipes Executor Monitor 0.0.0 ................. SUCCESS [  2.218 s]
[INFO] LinkedPipes Storage 0.0.0 .......................... SUCCESS [  0.405 s]
[INFO] LinkedPipes Executor 0.0.0 ......................... SUCCESS [  0.695 s]
[INFO] LinkedPipes Test Environment 0.0.0 ................. SUCCESS [  0.033 s]
[INFO] plugin l-wikibase 0.0.0 ............................ SUCCESS [  2.178 s]
[INFO] plugin t-chunkedToGraph 0.0.0 ...................... SUCCESS [  0.273 s]
[INFO] plugin t-excelToCsv 0.0.0 .......................... SUCCESS [  0.691 s]
[INFO] plugin t-filesFilter 0.0.0 ......................... SUCCESS [  0.504 s]
[INFO] plugin l-filesToScp 0.0.0 .......................... SUCCESS [  0.659 s]
[INFO] plugin e-datasetMetadata 0.0.0 ..................... SUCCESS [  0.468 s]
[INFO] plugin e-dcatAp11Dataset 0.0.0 ..................... SUCCESS [  0.612 s]
[INFO] plugin e-distributionMetadata 0.0.0 ................ SUCCESS [  0.455 s]
[INFO] plugin e-dcatAp11Distribution 0.0.0 ................ SUCCESS [  0.643 s]
[INFO] plugin e-voidDataset 0.0.0 ......................... SUCCESS [  0.564 s]
[INFO] plugin l-dcatAp11ToCkan 0.0.0 ...................... SUCCESS [  0.708 s]
[INFO] plugin l-lodCloud 0.0.0 ............................ SUCCESS [  0.698 s]
[INFO] plugin t-filesToRdf 0.0.0 .......................... SUCCESS [  0.509 s]
[INFO] plugin t-filesToRdfChunked 0.0.0 ................... SUCCESS [  0.478 s]
[INFO] plugin t-filesToRdfGraph 0.0.0 ..................... SUCCESS [  0.486 s]
[INFO] plugin t-filesToStatements 0.0.0 ................... SUCCESS [  0.479 s]
[INFO] plugin t-graphMerger 0.0.0 ......................... SUCCESS [  0.246 s]
[INFO] plugin t-packZip 0.0.0 ............................. SUCCESS [  0.449 s]
[INFO] plugin t-rdfToFile 0.0.0 ........................... SUCCESS [  0.441 s]
[INFO] plugin t-rdfToFileChunked 0.0.0 .................... SUCCESS [  0.433 s]
[INFO] plugin t-sparqlConstruct 0.0.0 ..................... SUCCESS [  0.374 s]
[INFO] plugin t-sparqlConstructChunked 0.0.0 .............. SUCCESS [  0.381 s]
[INFO] plugin t-sparqlLinkerChunked 0.0.0 ................. SUCCESS [  0.372 s]
[INFO] plugin t-sparqlSelect 0.0.0 ........................ SUCCESS [  0.451 s]
[INFO] plugin t-sparqlUpdate 0.0.0 ........................ SUCCESS [  0.386 s]
[INFO] plugin t-sparqlPerGraphUpdate 0.0.0 ................ SUCCESS [  0.419 s]
[INFO] plugin t-sparqlUpdateChunked 0.0.0 ................. SUCCESS [  0.447 s]
[INFO] plugin t-tabular 0.0.0 ............................. SUCCESS [  0.538 s]
[INFO] plugin t-tabularChunked 0.0.0 ...................... SUCCESS [  0.509 s]
[INFO] plugin t-unpack 0.0.0 .............................. SUCCESS [  0.728 s]
[INFO] plugin t-unpackZip 0.0.0 ........................... SUCCESS [  0.529 s]
[INFO] plugin t-xslt 0.0.0 ................................ SUCCESS [  1.639 s]
[INFO] plugin x-virtuoso 0.0.0 ............................ SUCCESS [  0.529 s]
[INFO] plugin e-httpGetFile 0.0.0 ......................... SUCCESS [  0.479 s]
[INFO] plugin e-sparqlEndpoint 0.0.0 ...................... SUCCESS [  0.475 s]
[INFO] plugin e-sparqlEndpointChunked 0.0.0 ............... SUCCESS [  0.497 s]
[INFO] plugin e-sparqlEndpointSelect 0.0.0 ................ SUCCESS [  0.415 s]
[INFO] plugin e-sparqlEndpointSelectScrollableCursor 0.0.0  SUCCESS [  0.405 s]
[INFO] plugin e-sparqlEndpointConstructScrollableCursor 0.0.0 SUCCESS [  0.403 s]
[INFO] plugin e-textHolder 0.0.0 .......................... SUCCESS [  0.402 s]
[INFO] plugin l-dcatApToCkan 0.0.0 ........................ SUCCESS [  0.543 s]
[INFO] plugin l-graphStoreProtocol 0.0.0 .................. SUCCESS [  0.443 s]
[INFO] plugin l-sparqlEndpoint 0.0.0 ...................... SUCCESS [  0.412 s]
[INFO] plugin t-filesBase64Decode 0.0.0 ................... SUCCESS [  0.463 s]
[INFO] plugin t-mustache 0.0.0 ............................ SUCCESS [  0.489 s]
[INFO] plugin q-sparqlAsk 0.0.0 ........................... SUCCESS [  0.458 s]
[INFO] plugin l-filesToLocal 0.0.0 ........................ SUCCESS [  0.181 s]
[INFO] plugin e-ftpFiles 0.0.0 ............................ SUCCESS [  0.402 s]
[INFO] plugin l-ftpFiles 0.0.0 ............................ SUCCESS [  0.371 s]
[INFO] plugin e-filesFromLocal 0.0.0 ...................... SUCCESS [  0.403 s]
[INFO] plugin t-tabularUv 0.0.0 ........................... SUCCESS [  0.738 s]
[INFO] plugin t-singleGraphUnion 0.0.0 .................... SUCCESS [  0.230 s]
[INFO] plugin e-httpGetFiles 0.0.0 ........................ SUCCESS [  0.377 s]
[INFO] plugin e-pipelineInput 0.0.0 ....................... SUCCESS [  0.165 s]
[INFO] plugin t-sparqlSelectMulti 0.0.0 ................... SUCCESS [  0.184 s]
[INFO] plugin t-filesRenamer 0.0.0 ........................ SUCCESS [  0.440 s]
[INFO] plugin t-templatedXlsToCsv 0.0.0 ................... SUCCESS [  0.565 s]
[INFO] plugin t-fileHasher 0.0.0 .......................... SUCCESS [  0.216 s]
[INFO] plugin x-virtuosoExtractor 0.0.0 ................... SUCCESS [  0.565 s]
[INFO] plugin t-valueParser 0.0.0 ......................... SUCCESS [  0.447 s]
[INFO] plugin x-deleteDirectory 0.0.0 ..................... SUCCESS [  0.462 s]
[INFO] plugin x-graphStorePurger 0.0.0 .................... SUCCESS [  0.430 s]
[INFO] plugin t-htmlCssUv 0.0.0 ........................... SUCCESS [  0.597 s]
[INFO] plugin t-modifyDate 0.0.0 .......................... SUCCESS [  0.431 s]
[INFO] plugin t-geoTools 0.0.0 ............................ SUCCESS [  0.432 s]
[INFO] plugin l-sparqlEndpointChunked 0.0.0 ............... SUCCESS [  0.475 s]
[INFO] plugin t-bingTranslator 0.0.0 ...................... SUCCESS [  0.483 s]
[INFO] plugin t-chunkedToTurtle 0.0.0 ..................... SUCCESS [  0.226 s]
[INFO] plugin t-streamCompression 0.0.0 ................... SUCCESS [  1.050 s]
[INFO] plugin t-jsonToJsonLd 0.0.0 ........................ SUCCESS [  0.372 s]
[INFO] plugin t-jsonLdFormat 0.0.0 ........................ SUCCESS [  1.396 s]
[INFO] plugin e-sparqlEndpointList 0.0.0 .................. SUCCESS [  0.485 s]
[INFO] plugin e-sparqlEndpointChunkedList 0.0.0 ........... SUCCESS [  0.295 s]
[INFO] plugin t-sparqlConstructToFileList 0.0.0 ........... SUCCESS [  0.505 s]
[INFO] plugin c-files 0.0.0 ............................... SUCCESS [  0.145 s]
[INFO] plugin l-solr 0.0.0 ................................ SUCCESS [  0.502 s]
[INFO] plugin t-chunkedToFiles 0.0.0 ...................... SUCCESS [  0.481 s]
[INFO] plugin x-httpRequest 0.0.0 ......................... SUCCESS [  0.261 s]
[INFO] plugin l-coachDb 0.0.0 ............................. SUCCESS [  0.489 s]
[INFO] plugin t-mustacheChunked 0.0.0 ..................... SUCCESS [  0.520 s]
[INFO] plugin t-chunkSplitter 0.0.0 ....................... SUCCESS [  0.442 s]
[INFO] plugin t-rdfToWrappedJsonLdChunked 0.0.0 ........... SUCCESS [  0.445 s]
[INFO] plugin t-rdfDifference 0.0.0 ....................... SUCCESS [  0.223 s]
[INFO] plugin t-xmlToChunks 0.0.0 ......................... SUCCESS [  0.473 s]
[INFO] plugin c-rdfSingleGraph 0.0.0 ...................... SUCCESS [  0.200 s]
[INFO] plugin c-rdfChunkedTriples 0.0.0 ................... SUCCESS [  0.199 s]
[INFO] plugin t-propertyLinkerChunked 0.0.0 ............... SUCCESS [  0.479 s]
[INFO] plugin t-jsonLdToRdf 0.0.0 ......................... SUCCESS [  1.281 s]
[INFO] plugin t-jsonLdToRdfChunked 0.0.0 .................. SUCCESS [  0.822 s]
[INFO] plugin t-hdtToRdf 0.0.0 ............................ SUCCESS [  0.819 s]
[INFO] plugin t-rdfToHdt 0.0.0 ............................ SUCCESS [  0.712 s]
[INFO] plugin t-shacl 0.0.0 ............................... SUCCESS [  0.454 s]
[INFO] plugin t-shacl-jena 0.0.0 .......................... SUCCESS [  0.828 s]
[INFO] plugin t-hierarchicalDataTransformation 0.0.0 ...... SUCCESS [  0.647 s]
[INFO] plugin t-jsonLdFormatTitanium 0.0.0 ................ SUCCESS [  0.578 s]
[INFO] plugin t-jsonLdToRdfTitanium 0.0.0 ................. SUCCESS [  0.577 s]
[INFO] plugin t-jenaTdbLoader 0.0.0 ....................... SUCCESS [  0.737 s]
[INFO] LinkedPipes Plugins 0.0.0 .......................... SUCCESS [  0.008 s]
[INFO] LinkedPipes Deploy Plugins 0.0.0 ................... SUCCESS [  1.224 s]
[INFO] LinkedPipes Frontend 0.0.0 ......................... FAILURE [02:18 min]
[INFO] LinkedPipes 0.0.0 .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:32 min
[INFO] Finished at: 2022-02-02T19:13:05-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (npm-build) on project frontend: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :frontend_

So I've tried fixing the javascript error. 
Firstly, i tried increasing the memory of node:
_export NODE_OPTIONS=--max_old_space_size=4096
export NODE_OPTIONS=--max_old_space_size=5120_

I tried both options with 4gb and 5gb but both of them didn't work. 
Then i tried:
_(base) cloud-di@vmm-template:~/etl$ npm install -g increase-memory-limit

added 12 packages, and audited 13 packages in 2s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
(base) cloud-di@vmm-template:~/etl$ increase-memory-limit
'node_modules/.bin/acorn' written successfully.
'node_modules/.bin/browserslist' written successfully.
'node_modules/.bin/eslint' written successfully.
'node_modules/.bin/js-yaml' written successfully.
'node_modules/.bin/nanoid' written successfully.
'node_modules/.bin/node-which' written successfully.
'node_modules/.bin/rimraf' written successfully.
'node_modules/.bin/semver' written successfully.
'node_modules/.bin/sshpk-conv' written successfully.
'node_modules/.bin/sshpk-sign' written successfully.
'node_modules/.bin/sshpk-verify' written successfully.
'node_modules/.bin/terser' written successfully.
'node_modules/.bin/uuid' written successfully.
'node_modules/.bin/webpack' written successfully._

The error changed but i still had a memory problem.

So i reduced my memory size with '_export NODE_OPTIONS=--max_old_space_size=2048_' and tried running '_increase-memory-limit_' and then tried building and got another memory error.

All of the websites that i searched for to try to resolve the problem suggested that i had to increase memory, so i tried with 8gb and then 16gb but still got nothing.

Maybe there's some parameter on compilation that can help??

Thank you so much.

**Comment by jakubklimek** [comment]
Thanks, this is interesting. Just for the record, we are regularly building on a 8GB machine, so that should definitely be enough.

**Comment by jakubklimek** [comment]
@marianadsalgueiro Hello, I just retested this on Ubuntu 18.04.6, JDK 17.0.1, nodejs 17.4 and Maven 3.8.4 on a VM with 4 cores and 8GB RAM - and it worked for me.
Just out of curiosity, how did you install Maven 3.8.x on your Ubuntu 18.04? The reason I am asking is that by default, on Ubuntu 18.04, there is Maven 3.6, which is not compatible with JDK 17 and there are [some guides](https://github.com/m-thirumal/installation_guide/blob/master/maven/upgrade_maven.md) on how to install Maven 3.8, which, for some reason, restrict Maven heap. Have you checked for that?

**Comment by marianadsalgueiro** [comment]
Hi!

Just for the record my VM also has 4 cores but 16GB RAM.

Yes, i've actually installed it using exactly the guide you linked. 

I have this other VM that has Linked Pipes installed but with older versions of maven, jdk, nodejs (Ubuntu 18.04.6, JDK 11.0.13, nodejs v8.10.0 and Maven 3.6.0)... i'm thinking about trying those specifications on this new VM, just so that i can check if it works.
What do you think?

Thank you again.

**Comment by jakubklimek** [comment]
@marianadsalgueiro ok, so you also have the memory settings for maven in your `~/.profile` according to the guide? Have you tried removing them (and logoff/logon again)?

**Comment by jakubklimek** [comment]
Well, I am out of ideas on what can be wrong, as it works for me on exactly the same configuration. Could you maybe try to freshly install ubuntu (maybe a newer version?) on the vm to avoid any issues with possible system-wide settings limiting memory usage by node.js?
