### ISSUE TITLE
x-httpRequest does not work with IDN

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#916]
See [this execution](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2F1649669309814&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F1649669383674-1821-a7fd3838-dd28-48e2-b834-54f45800f988). It tries to access the URL https://obchodní-rejstřík.stirdata.opendata.cz/soubor/or.hdt and fails.

When "Encode input URL" is disabled, it apparently tried to access the unencoded URL (especially the IDN part) and fails DNS resolution.
When "Encodie input URL" is enabled, it encodes the domain part using percent encoding, which is incorrect, and also fails DNS resolution.

The correct behavior would be to detect unicode characters in the domain part of the URL and use Punycode to encode that part.

**Comment by skodapetr** [comment]
This is not a bug but rather a feature request and is not limited to this single component. Such problem is probably everywhere in the application and may requires solution on low-enough level. Luckily there seems to be a solution in form of a [IDN](https://docs.oracle.com/javase/8/docs/api/java/net/IDN.html) class. Yet further research needs to be done on how this should be systematically addressed. 

The connection to the "Encode input URL" here is that the encoding should not be used to the domain name.

**Comment by skodapetr** [comment]
It should be solved for the HTTP-related components, yet the same issue may be when using any other component with URL. But that is bigger change with scope outside of this issue.
