### ISSUE TITLE
Loading quads into SPARQL endpoints

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#917]
We need to implement a way of loading RDF quads into SPARQL endpoints.
Our current use case is loading RDF quads into Ontotext GraphDB, however, the chosen approach could be universal, as AFAIK there is no universal solution in LP-ETL at the moment.

Based on the short analysis below, I suggest implementing a task-based SPARQL Graph Store Protocol loader (input: config, tasks, set of turtle files linked from tasks) first and see how it performs.

Current state of things
-------------------------
Currently, we are not able to hold RDF quads in a data unit. However, we are able to create an RDF TriG file using [SPARQL Construct to file list](https://etl.linkedpipes.com/components/t-sparqlconstructtofilelist). Once we have the TriG file, we can load it into OpenLink Virtuoso via [Virtuoso loader](https://etl.linkedpipes.com/components/x-virtuoso), or we can use the Jena TDB loader and replace a database of Apache Jena Fuseki, and restart it via a webhook. Other than that, we are able to load RDF triples using [SPARQL endpoint](https://etl.linkedpipes.com/components/l-sparqlendpoint) and [SPARQL Graph Store Protocol](https://etl.linkedpipes.com/components/l-graphstoreprotocol) loaders into one pre-configured graph.

Possible solutions
-------------------
Input
1. either a TriG/N-Quads dump or
2. a data unit capable of holding RDF quads (with the appropriate loaders of course).
3. or a set of TTL files (triples) with graph information in e.g. configuration - this we can do using [SPARQL Construct to file list](https://etl.linkedpipes.com/components/t-sparqlconstructtofilelist) as well (this might be preferred due to better output implementation).

Output
1. Output could be to a regular SPARQL Update endpoint, dynamically changing the graph to which we load the individual triples (this could have a huge HTTP-related overhead) or,
2. Using input option 3 (set of ttl files + configuration), we could simply create a task-based graph store protocol loader
3. We could also do some preprocessing of quads data units or trig dumps like splitting the input into individual graphs (easier for quad-based data unit, doable for dumps) and then using output option number 2.

**Comment by skodapetr** [comment]
For short term I agree with the component, yet we should consider support for quads. The support may be implemented using per data-unit repository which is now the de-facto standard and will become default as it is required by resuming components.
