### ISSUE TITLE
Typo in frontend server code causes errors when trying to process multipart request

### ISSUE THREAD

**Issue by gkostkowski** [linkedpipes/etl#931]
Hi!

I was not able to send multipart request (created when e.g. using pipeline input component). After a quite long investigation, I finally found the reason. There is a typo in [execution-factory.js](https://github.com/linkedpipes/etl/blob/develop/frontend/server/execution-factory.js#L151): _parseUrl_  function returns object with ``hostname`` field, not ``postname``. As the effect, ``undefined`` value is used instead of the name of ``executor-monitor`` host. 

As I can see in logs, in the time of sending the request, this is finally resolved as ``127.0.0.1``. I guess that https://demo.etl.linkedpipes.com instance has different network configuration and that's why it works fine.

**Comment by skodapetr** [comment]
Thank you for providing such a detail report on the issue. The typo should be fixed now, could you please test it?

**Comment by gkostkowski** [comment]
Could you upload built Docker image into Dockerhub?

**Comment by skodapetr** [comment]
There should now be new version of "develop" tag for all components.

**Comment by gkostkowski** [comment]
Unfortunately, I cannot launch any pipeline using latest container (develop). I'm not sure whether it's a bug or my configuration is not suitable for the newer version. Version which works for me is 6370d54f624df405452207ef0641f46d8041b5e0. As far as i remember, i had same issue with previous image from develop, that's why i'm using 6370d54f624df405452207ef0641f46d8041b5e0 version. Thus, i don't think that below error is caused by your latest change.

Stack trace from executor:
```
executor_1          | com.linkedpipes.etl.executor.ExecutorException: Missing definition file!
executor_1          |   at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.locatePipelineDefinitionFile(PipelineExecutor.java:184)
executor_1          |   at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.loadPipeline(PipelineExecutor.java:173)
executor_1          |   at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.initialize(PipelineExecutor.java:136)
executor_1          |   at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.execute(PipelineExecutor.java:93)
executor_1          |   at com.linkedpipes.etl.executor.web.servlet.ExecutionServlet.lambda$execute$0(ExecutionServlet.java:71)
executor_1          |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
executor_1          |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
executor_1          |   at java.base/java.lang.Thread.run(Thread.java:833)
executor_1          | 09:45:01 [asynchExecutor-1] ERROR c.l.e.e.p.PipelineExecutor - Can't cleanup after pipeline execution!
executor_1          | java.lang.NullPointerException: Cannot invoke "com.linkedpipes.etl.executor.pipeline.Pipeline.save(java.io.File)" because "this.pipeline" is null
executor_1          |   at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.terminate(PipelineExecutor.java:361)
executor_1          |   at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.execute(PipelineExecutor.java:102)
executor_1          |   at com.linkedpipes.etl.executor.web.servlet.ExecutionServlet.lambda$execute$0(ExecutionServlet.java:71)
executor_1          |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
executor_1          |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
executor_1          |   at java.base/java.lang.Thread.run(Thread.java:833)
executor_1          | 09:45:01 [asynchExecutor-1] INFO  c.l.e.e.p.PipelineExecutor - PipelineExecutor.execute ... done
```

Anyway, I can confirm that for 6370d54f624df405452207ef0641f46d8041b5e0 version fixing the typo resolved the reported issue.

**Comment by bencomp** [comment]
After some investigation into the errors above (not the original issue), I found that the docker-compose.yml file specifies the wrong paths for volumes. That causes the errors about not finding files. The paths in the docker-compose file should be `/data/lp-etl/...` instead of `/data/lp/etl/...`.

Earlier I thought it could be an issue with the `linkedpipes` user being specified in the Dockerfiles, but not on the host system, which might cause file permission issues. But when I looked inside a container, I noticed that there were different directories inside `/data/`.

**Comment by skodapetr** [comment]
@bencomp Thank you for your investigation, you are absolutely right. I'll fix the paths in docker-compose file tomorrow.

As of the user it may be an issue if you map the volume to your machine. It is not a problem if the user does not exist as long as they have required access to the directories.
