### ISSUE TITLE
Version and tags in docker-compose.yml

### ISSUE THREAD

**Issue by EmidioStani** [linkedpipes/etl#952]
Hello,

I started to use the docker compose following the instructions but the yml file seems wrong, I get errors while doing "docker compose up":

- version should be a string, so it should be '3'

- each image by default point to the latest tag but on Docker Hub the there are tags "main" and "develop", so I personally used "main"

**Comment by skodapetr** [comment]
@EmidioStani Thank you for bringing that to our attention. The version is fixed in develop and there are now versions for the image ("main" by default). Does it work after those modifications, rr do you encounter other issues?

**Comment by EmidioStani** [comment]
No worries, I modified by myself, it was just to tell you.
Thanks
