### ISSUE TITLE
Cannot trigger pipeline execution from a local instance

### ISSUE THREAD

**Issue by viktor-ribchev** [linkedpipes/etl#953]
Hi,
 
I have deployed the ETL locally via the docker-compose you've provided and created a simple pipeline. 
The config is: 
```
LP_ETL_DOMAIN=http://localhost:7777
LP_ETL_PORT=7777
LP_VERSION=main
```

When I try to trigger the pipeline via cURL as shown [here](https://github.com/linkedpipes/etl/wiki/Pipeline-execution-with-curl/f225caf8a4d9f274a23b20fa298a70edf9e4db3b)

`curl -i -X POST http://localhost:7777/resources/executions?pipeline=http://localhost:7777/resources/pipelines/1667194442821`

I get: 
```
HTTP/1.1 404 Not Found
X-Powered-By: Express
Content-Security-Policy: default-src 'none'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 160
Date: Mon, 31 Oct 2022 05:38:44 GMT
Connection: keep-alive
Keep-Alive: timeout=5

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /resources/executions</pre>
</body>
</html>
```

Can you tell me what I'm missing?

**Comment by jakubklimek** [comment]
Hello,
if you are using the develop branch, the API path has changed (not documented yet, sorry). Try `http://localhost:7777/api/v1/executions`

**Comment by viktor-ribchev** [comment]
@jakubklimek Thanks for the fast response, I'm using the main branch, but the example you gave works :) 
Thanks!
