### ISSUE TITLE
Update dependencies, and JSON-LD Titanium in particular

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#983]
https://github.com/filip26/titanium-json-ld/releases/tag/v1.4.0

Also RDF4j 4.3.11+, Apache Jena 5.0.0+
Java 21, 22

**Comment by skodapetr** [comment]
Unfortunately it seems that [jena-osgi has been depracated](https://github.com/apache/jena/blob/main/archived-modules.md). As a result, in order to update to 5.0.0 we need to create cusom OSGI bundle.

**Comment by jakubklimek** [comment]
OK, so skip Jena for now.

**Comment by skodapetr** [comment]
I've created [another issue](https://github.com/linkedpipes/etl/issues/991) for Jena.
